import { ArrayXMLField,  StringXMLField, ObjectXMLField, EnumXMLField } from '@aurahelper/core';

export function botInvocation(invocationName: string, invocationLabel: string, minApi?: number | string) {
    return new ObjectXMLField(invocationName, invocationLabel)
        .setEditable()
        .setMinApi(minApi)
        .setFieldKey('invocationActionName')
        .addField('invocationActionName', new StringXMLField('invocationActionName', 'Invocation Action Name')
            .setEditable()
        )
        .addField('invocationActionType', new EnumXMLField('invocationActionType', 'Invocation Action Type')
            .setEditable()
            .addEnumValue('Apex', 'apex')
            .addEnumValue('Flow', 'flow')
            .addEnumValue('Standard Invocable Action', 'standardInvocableAction')
        )
        .addField('invocationMappings', new ArrayXMLField('invocationMappings', 'Invocation Mappings')
            .setEditable()
            .setFieldKey('parameterName')
            .addField('parameterName', new StringXMLField('parameterName', 'Parameter Name')
                .setEditable()
                .setRequired()
            )
            .addField('type', new EnumXMLField('type', 'Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Input', 'Input')
                .addEnumValue('Output', 'Output')
            )
            .addField('value', new StringXMLField('value', 'Value')
                .setEditable()
            )
            .addField('variableName', new StringXMLField('variableName', 'Variable Name')
                .setEditable()
            )
            .addField('variableType', new EnumXMLField('variableType', 'Variable Type')
                .setEditable()
                .addEnumValue('Conversation Variable', 'ConversationVariable')
                .addEnumValue('Context Variable', 'ContextVariable')
            )
        );
}