const { StringXMLField, EnumXMLField, BooleanXMLField } = require('../../factory/xmlFactory');

module.exports = function (type, shortcutName, shortcutLabel, minApi, maxApi) {
    return new type(shortcutName, shortcutLabel)
        .setMinApi(minApi)
        .setMaxApi(maxApi)
        .setEditable()
        .addField('action', new StringXMLField('action', 'Action')
            .setEditable()
            .setRequired()
        )
        .addField('active', new BooleanXMLField('active', 'Active')
            .setEditable()
            .setRequired()
        )
        .addField('keyCommand', new EnumXMLField('keyCommand', 'Key Command')
            .setEditable()
            .setRequired()
            .addEnumValue('SHIFT', 'SHIFT')
            .addEnumValue('CTRL', 'CTRL')
            .addEnumValue('ALT', 'ALT')
            .addEnumValue('META', 'META')
            .addEnumValue('TAB', 'TAB')
            .addEnumValue('ENTER', 'ENTER')
            .addEnumValue('PAUSE/BREAK', 'PAUSE/BREAK')
            .addEnumValue('CAPS LOCK', 'CAPS LOCK')
            .addEnumValue('ESC', 'ESC')
            .addEnumValue('SPACE', 'SPACE')
            .addEnumValue('PAGE UP', 'PAGE UP')
            .addEnumValue('PAGE DOWN', 'PAGE DOWN')
            .addEnumValue('END', 'END')
            .addEnumValue('END', 'END')
            .addEnumValue('LEFT ARROW', 'LEFT ARROW')
            .addEnumValue('UP ARROW', 'UP ARROW')
            .addEnumValue('RIGHT ARROW', 'RIGHT ARROW')
            .addEnumValue('DOWN ARROW', 'DOWN ARROW')
            .addEnumValue('PRINT SCREEN', 'PRINT SCREEN')
            .addEnumValue('INSERT', 'INSERT')
            .addEnumValue('DELETE', 'DELETE')
            .addEnumValue('RIGHT WINDOW', 'RIGHT WINDOW')
            .addEnumValue('NUMPAD 0', 'NUMPAD 0')
            .addEnumValue('NUMPAD 1', 'NUMPAD 1')
            .addEnumValue('NUMPAD 2', 'NUMPAD 2')
            .addEnumValue('NUMPAD 3', 'NUMPAD 3')
            .addEnumValue('NUMPAD 4', 'NUMPAD 4')
            .addEnumValue('NUMPAD 5', 'NUMPAD 5')
            .addEnumValue('NUMPAD 6', 'NUMPAD 6')
            .addEnumValue('NUMPAD 7', 'NUMPAD 7')
            .addEnumValue('NUMPAD 8', 'NUMPAD 8')
            .addEnumValue('NUMPAD 9', 'NUMPAD 9')
            .addEnumValue('MULTIPLY', 'MULTIPLY')
            .addEnumValue('ADD', 'ADD')
            .addEnumValue('SUBTRACT', 'SUBTRACT')
            .addEnumValue('DECIMAL POINT', 'DECIMAL POINT')
            .addEnumValue('DIVIDE', 'DIVIDE')
            .addEnumValue('F1', 'F1')
            .addEnumValue('F2', 'F2')
            .addEnumValue('F3', 'F3')
            .addEnumValue('F4', 'F4')
            .addEnumValue('F5', 'F5')
            .addEnumValue('F6', 'F6')
            .addEnumValue('F7', 'F7')
            .addEnumValue('F8', 'F8')
            .addEnumValue('F9', 'F9')
            .addEnumValue('F10', 'F10')
            .addEnumValue('F11', 'F11')
            .addEnumValue('F12', 'F12')
            .addEnumValue('NUM LOCK', 'NUM LOCK')
            .addEnumValue('SCROLL LOCK', 'SCROLL LOCK')
            .addEnumValue(',', ';')
            .addEnumValue('=', '=')
            .addEnumValue(',', ',')
            .addEnumValue('-', '-')
            .addEnumValue('.', '.')
            .addEnumValue('/', '/')
            .addEnumValue('`', '`')
            .addEnumValue('[', '[')
            .addEnumValue(']', ']')
            .addEnumValue('\\', '\\')
            .addEnumValue('\'', '\'')
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('eventName', new StringXMLField('eventName', 'Event Name')
            .setEditable()
            .setRequired()
        )
}

