const { StringXMLField, ObjectXMLField, EnumXMLField, ArrayXMLField, DoubleXMLField, BooleanXMLField, IntegerXMLField } = require('@ah/core').Types;
const { MetadataTypes, DataValues } = require('@ah/core').Values;

module.exports = function (type, dashboardComponentName, dashboardComponentLabel, minApi) {
    return new type(dashboardComponentName, dashboardComponentLabel)
        .setMinApi(minApi)
        .setEditable()
        .setRequired()
        .setFieldKey('title')
        .setSortOrder(undefined)
        .addField('chartAxisRange', new EnumXMLField('chartAxisRange', 'Chart Axis Range')
            .setEditable()
            .addEnumValue('Auto', 'auto')
            .addEnumValue('Manual', 'manual')
        )
        .addField('chartAxisRangeMax', new DoubleXMLField('chartAxisRangeMax', 'Chart Axis Range Max')
            .setEditable()
        )
        .addField('chartAxisRangeMin', new DoubleXMLField('chartAxisRangeMin', 'Chart Axis Range Min')
            .setEditable()
        )
        .addField('chartSummary', new ObjectXMLField('chartSummary', 'ChartSummary')
            .setEditable()
            .setFieldKey('column')
            .setSortOrder(undefined)
            .addField('aggregateType', new EnumXMLField('aggregateType', 'Aggregate Type')
                .setEditable()
                .setRequired()
                .setDefaultValue('None')
                .setEnumValues(DataValues.REPORT_SUMMARY_TYPES)
            )
            .addField('axisBinding', new EnumXMLField('axisBinding', 'Axis Binding')
                .setEditable()
                .addEnumValue('x', 'x')
                .addEnumValue('y', 'y')
                .addEnumValue('y2', 'y2')
            )
            .addField('column', new StringXMLField('column', 'Column')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
        )
        .addField('componentType', new EnumXMLField('componentType', 'Component Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Bar', 'Bar')
            .addEnumValue('Bar Grouped', 'BarGrouped')
            .addEnumValue('Bar Stacked', 'BarStacked')
            .addEnumValue('Bar Stacked 100', 'BarStacked100')
            .addEnumValue('Column', 'Column')
            .addEnumValue('Column Grouped', 'ColumnGrouped')
            .addEnumValue('Column Line', 'ColumnLine')
            .addEnumValue('Column Line Grouped', 'ColumnLineGrouped')
            .addEnumValue('Column Line Stacked', 'ColumnLineStacked')
            .addEnumValue('Column Line Stacked 100', 'ColumnLineStacked100')
            .addEnumValue('Column Stacked', 'ColumnStacked')
            .addEnumValue('Column Stacked 100', 'ColumnStacked100')
            .addEnumValue('Donut', 'Donut')
            .addEnumValue('Flex Table', 'FlexTable')
            .addEnumValue('Funnel', 'Funnel')
            .addEnumValue('Gauge', 'Gauge')
            .addEnumValue('Line', 'Line')
            .addEnumValue('Line Cumulative', 'lineCumulative')
            .addEnumValue('Line Grouped', 'LineGrouped')
            .addEnumValue('Line Grouped Cumulative', 'lineGroupedCumulative')
            .addEnumValue('Metric', 'Metric')
            .addEnumValue('Pie', 'Pie')
            .addEnumValue('Scatter', 'Scatter')
            .addEnumValue('Scatter Grouped', 'ScatterGrouped')
            .addEnumValue('S-Control', 'Scontrol')
            .addEnumValue('Table', 'Table')
        )
        .addField('dashboardFilterColumns', new ArrayXMLField('dashboardFilterColumns', 'Dashboard Filter Columns')
            .setMinApi(23)
            .setEditable()
            .setFieldKey('column')
            .addField('column', new StringXMLField('column', 'Column')
                .setEditable()
                .setRequired()
            )
        )
        .addField('dashboardTableColumn', new ArrayXMLField('dashboardTableColumn', 'Dashboard Table Column')
            .setMinApi(14)
            .setEditable()
            .setFieldKey('column')
            .addField('aggregateType', new EnumXMLField('aggregateType', 'Aggregate Type')
                .setEditable()
                .setRequired()
                .setDefaultValue('None')
                .setEnumValues(DataValues.REPORT_SUMMARY_TYPES)
            )
            .addField('column', new StringXMLField('column', 'Column')
                .setEditable()
                .setRequired()
            )
            .addField('showTotal', new BooleanXMLField('showTotal', 'Show Total')
                .setMinApi(19)
                .setEditable()
            )
            .addField('sortBy', new EnumXMLField('sortBy', 'Sort By')
                .setEditable()
                .addEnumValue('Row Label Ascending', 'RowLabelAscending')
                .addEnumValue('Row Label Descending', 'RowLabelDescending')
                .addEnumValue('Row Value Ascending', 'RowValueAscending')
                .addEnumValue('Row Value Descending', 'RowValueDescending')
            )
        )
        .addField('displayUnits', new EnumXMLField('displayUnits', 'DisplayUnits')
            .setEditable()
            .addEnumValue('Auto', 'Auto')
            .addEnumValue('Integer', 'Integer')
            .addEnumValue('Hundreds', 'Hundreds')
            .addEnumValue('Thousands', 'Thousands')
            .addEnumValue('Millions', 'Millions')
            .addEnumValue('Billions', 'Billions')
            .addEnumValue('Trillions', 'Trillions')
        )
        .addField('drillDownUrl', new StringXMLField('drillDownUrl', 'Drill Down Url')
            .setEditable()
            .setRequired()
        )
        .addField('drillEnabled', new BooleanXMLField('drillEnabled', 'Drill Enabled')
            .setMinApi(17)
            .setEditable()
        )
        .addField('drillToDetailEnabled', new BooleanXMLField('drillToDetailEnabled', 'Drill To Detail Enabled')
            .setMinApi(20)
            .setEditable()
        )
        .addField('enableHover', new BooleanXMLField('enableHover', 'Enable Hover')
            .setMinApi(17)
            .setEditable()
        )
        .addField('expandOthers', new BooleanXMLField('expandOthers', 'Expand Others')
            .setMinApi(17)
            .setEditable()
        )
        .addField('flexComponentProperties', new ObjectXMLField('flexComponentProperties', 'Flex Component Properties')
            .setMinApi(41)
            .setEditable()
            .setFieldKey('flexTableColumn')
            .setSortOrder(undefined)
            .addField('flexTableColumn', new ObjectXMLField('flexTableColumn', 'Flex Table Column')
                .setEditable()
                .setFieldKey('type')
                .setSortOrder(undefined)
                .addField('breakPoint1', new DoubleXMLField('breakPoint1', 'Break Point 1')
                    .setEditable()
                )
                .addField('breakPoint2', new DoubleXMLField('breakPoint2', 'Break Point 2')
                    .setEditable()
                )
                .addField('breakPointOrder', new DoubleXMLField('breakPointOrder', 'Break Point Order')
                    .setEditable()
                )
                .addField('highRangeColor', new IntegerXMLField('highRangeColor', 'High Range Color')
                    .setEditable()
                )
                .addField('lowRangeColor', new IntegerXMLField('lowRangeColor', 'Low Range Color')
                    .setEditable()
                )
                .addField('midRangeColor', new IntegerXMLField('midRangeColor', 'Middle Range Color')
                    .setEditable()
                )
                .addField('reportColumn', new StringXMLField('reportColumn', 'Report Column')
                    .setEditable()
                    .setRequired()
                )
                .addField('showTotal', new BooleanXMLField('showTotal', 'Show Total')
                    .setEditable()
                )
                .addField('type', new EnumXMLField('type', 'Type')
                    .setEditable()
                    .addEnumValue('Details', 'Details')
                    .addEnumValue('Aggregates', 'Aggregates')
                    .addEnumValue('Grouping', 'Grouping')
                )
            )
            .addField('flexTableSortInfo', new ObjectXMLField('flexTableSortInfo', 'Flex Table Sort Info')
                .setEditable()
                .setFieldKey('ComponentSortColumn')
                .setSortOrder(undefined)
                .addField('ComponentSortColumn', new StringXMLField('ComponentSortColumn', 'Component Sort Column')
                    .setEditable()
                )
                .addField('sortOrder', new EnumXMLField('sortOrder', 'Sort Order')
                    .setEditable()
                    .addEnumValue('Ascending', 'Ascending')
                    .addEnumValue('Descending', 'Descending')
                )
            )
            .addField('hideChatterPhotos', new BooleanXMLField('hideChatterPhotos', 'Fide Chatter Photos')
                .setEditable()
            )
            .addField('decimalPrecision', new IntegerXMLField('decimalPrecision', 'Decimal Precision')
                .setEditable()
            )
        )
        .addField('footer', new StringXMLField('footer', 'Footer')
            .setEditable()
            .setMaxLength(255)
        )
        .addField('gaugeMax', new DoubleXMLField('gaugeMax', 'Gauge Max')
            .setEditable()
        )
        .addField('gaugeMin', new DoubleXMLField('gaugeMin', 'Gauge Min')
            .setEditable()
        )
        .addField('groupingColumn', new StringXMLField('groupingColumn', 'Grouping Column')
            .setMinApi(25)
            .setEditable()
        )
        .addField('GroupingSortProperties', new ObjectXMLField('GroupingSortProperties', 'Grouping Sort Properties')
            .setMinApi(46)
            .setEditable()
            .setFieldKey('groupingSorts')
            .setSortOrder(undefined)
            .addField('groupingSorts', new ObjectXMLField('groupingSorts', 'Grouping Sorts')
                .setEditable()
                .setFieldKey('sortColumn')
                .setSortOrder(undefined)
                .addField('groupingLevel', new StringXMLField('groupingLevel', 'Grouping Level')
                    .setEditable()
                )
                .addField('inheritedReportGroupingSort', new BooleanXMLField('inheritedReportGroupingSort', 'Inherited Report Grouping Sort')
                    .setEditable()
                )
                .addField('sortColumn', new StringXMLField('sortColumn', 'Sort Column')
                    .setEditable()
                )
                .addField('sortOrder', new EnumXMLField('sortOrder', 'Sort Order')
                    .setEditable()
                    .addEnumValue('Ascending', 'Ascending')
                    .addEnumValue('Descending', 'Descending')
                )
            )
        )
        .addField('header', new StringXMLField('header', 'Header')
            .setEditable()
            .setMaxLength(80)
        )
        .addField('indicatorBreakpoint1', new DoubleXMLField('indicatorBreakpoint1', 'Indicator Breakpoint 1')
            .setEditable()
        )
        .addField('indicatorBreakpoint2', new DoubleXMLField('indicatorBreakpoint2', 'Indicator Breakpoint 2')
            .setEditable()
        )
        .addField('indicatorHighColor', new StringXMLField('indicatorHighColor', 'Indicator High Color')
            .setEditable()
        )
        .addField('indicatorLowColor', new StringXMLField('indicatorLowColor', 'Indicator Low Color')
            .setEditable()
        )
        .addField('indicatorMiddleColor', new StringXMLField('indicatorMiddleColor', 'Indicator Middle Color')
            .setEditable()
        )
        .addField('legendPosition', new EnumXMLField('legendPosition', 'Legend Position')
            .setEditable()
            .addEnumValue('Bottom', 'Bottom')
            .addEnumValue('On Chart', 'OnChart')
            .addEnumValue('Right', 'Right')
        )
        .addField('maxValuesDisplayed', new IntegerXMLField('maxValuesDisplayed', 'Max Values Displayed')
            .setEditable()
        )
        .addField('metricLabel', new StringXMLField('metricLabel', 'Metric Label')
            .setEditable()
        )
        .addField('page', new StringXMLField('page', 'Page')
            .setEditable()
            .setMetadataType(MetadataTypes.APEX_PAGE)
        )
        .addField('pageHeightInPixels', new IntegerXMLField('pageHeightInPixels', 'Page Height In Pixels')
            .setEditable()
        )
        .addField('report', new StringXMLField('report', 'Report')
            .setEditable()
            .setMetadataType(MetadataTypes.REPORTS)
        )
        .addField('scontrol', new StringXMLField('scontrol', 'S-Control')
            .setEditable()
            .setMetadataType(MetadataTypes.S_CONTROL)
        )
        .addField('scontrolHeightInPixels', new IntegerXMLField('scontrolHeightInPixels', 'S-Control Height In Pixels')
            .setEditable()
        )
        .addField('showPercentage', new BooleanXMLField('showPercentage', 'Show Percentage')
            .setEditable()
        )
        .addField('showPicturesOnCharts', new BooleanXMLField('showPicturesOnCharts', 'Show Pictures On Charts')
            .setEditable()
        )
        .addField('showPicturesOnTables', new BooleanXMLField('showPicturesOnTables', 'Show Pictures On Tables')
            .setEditable()
        )
        .addField('showTotal', new BooleanXMLField('showTotal', 'Show Total')
            .setEditable()
        )
        .addField('showValues', new BooleanXMLField('showValues', 'Show Values')
            .setEditable()
        )
        .addField('sortBy', new EnumXMLField('sortBy', 'Sort By')
            .setEditable()
            .addEnumValue('Row Label Ascending', 'RowLabelAscending')
            .addEnumValue('Row Label Descending', 'RowLabelDescending')
            .addEnumValue('Row Value Ascending', 'RowValueAscending')
            .addEnumValue('Row Value Descending', 'RowValueDescending')
        )
        .addField('title', new StringXMLField('title', 'Title')
            .setEditable()
            .setMaxLength(40)
        )
        .addField('useReportChart', new BooleanXMLField('useReportChart', 'Use Report Chart')
            .setEditable()
        )
}