const { EnumXMLField, StringXMLField, ArrayXMLField, ObjectXMLField } = require('../../factory/xmlFactory');

module.exports = function (intentName, intentApi, minApi) {
    return new ArrayXMLField(intentName, intentApi)
        .setMinApi(minApi)
        .setEditable()
        .setFieldKey('developerName')
        .addField('dataType', new EnumXMLField('dataType', 'Data Type')
            .setEditable()
            .addEnumValue('Text', 'Text')
            .addEnumValue('Number', 'Number')
            .addEnumValue('Boolean', 'Boolean')
            .addEnumValue('Date', 'Date')
            .addEnumValue('DateTime', 'DateTime')
            .addEnumValue('Currency', 'Currency')
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('developerName', new StringXMLField('developerName', 'Developer Name')
            .setEditable()
            .setRequired()
            .setUnique()
        )
        .addField('extractionRegex', new StringXMLField('extractionRegex', 'Extraction Regex')
            .setEditable()
        )
        .addField('extractionType', new EnumXMLField('extractionType', 'Extraction Type')
            .setEditable()
            .addEnumValue('Pattern', 'Pattern')
            .addEnumValue('Value', 'Value')
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('mlSlotClassValues', new ArrayXMLField('mlSlotClassValues', 'Machine Learning Slot Class Values')
            .setEditable()
            .addField('synonymGroup', new ObjectXMLField('synonymGroup', 'synonymGroup')
                .setEditable()
                .addField('languages', new EnumXMLField('languages', 'Languages')
                    .setEditable()
                    .setRequired()
                )
                .addField('terms', new StringXMLField('terms', 'Terms')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('value', new StringXMLField('value', 'Value')
                .setEditable()
            )
        )
} 