const { StringXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField, BooleanXMLField, XMLDependencyField, EnumXMLField } = require('@aurahelper/core').Types;
const { DataValues } = require('@aurahelper/core').Values;

module.exports = function (navigationLinkSetName, navigationLinkSetLabel, minApi, maxApi) {
    return new ObjectXMLField(navigationLinkSetName, navigationLinkSetLabel)
        .setMinApi(minApi)
        .setMaxApi(maxApi)
        .setEditable()
        .setFieldKey('navigationMenuItem')
        .setSortOrder(undefined)
        .addField('navigationMenuItem', new ArrayXMLField('navigationMenuItem', 'Navigation Menu Item')
            .setEditable()
            .setFieldKey('label')
            .addField('defaultListViewId', new StringXMLField('defaultListViewId', 'Default List View Id')
                .setEditable()
                .linkFieldToSObject('ListView')
            )
            .addField('label', new StringXMLField('label', 'Label')
                .setEditable()
                .setRequired()
            )
            .addField('navigationMenuItemBranding', new StringXMLField('navigationMenuItemBranding', 'Navigation Menu Item Branding')
                .setMinApi(47)
                .setEditable()
            )
            .addField('position', new IntegerXMLField('position', 'Position')
                .setEditable()
                .setRequired()
            )
            .addField('publiclyAvailable', new BooleanXMLField('publiclyAvailable', 'Publicly Available')
                .setEditable()
            )
            .addField('subMenu', new ObjectXMLField('subMenu', 'Sub Menu')
                .setEditable()
                .setRequired()
                .setDefinitionReference('this>navigationMenuItem')
            )
            .addField('target', new StringXMLField('target', 'Target')
                .setEditable()
                .setRequired()
                .addDependencyField(new XMLDependencyField('type', ['ExternalLink', 'InternalLink', 'SalesforceObject'], DataValues.NOT_NULL))
            )
            .addField('targetPreference', new EnumXMLField('targetPreference', 'Target Preference')
                .setEditable()
                .addEnumValue('None', 'None')
                .addEnumValue('Open In External Tab', 'OpenInExternalTab')
            )
            .addField('type', new EnumXMLField('type', 'Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Salesforce Object', 'SalesforceObject')
                .addEnumValue('External Link', 'ExternalLink')
                .addEnumValue('Internal Link', 'InternalLink')
                .addEnumValue('Menu Label', 'MenuLabel', 39)
                .addEnumValue('Navigational Topic', 'NavigationalTopic')
            )
        );
} 