import { StringXMLField, BooleanXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField } from '@aurahelper/core';

export const ActionPlanTemplate = {
    actionPlanTemplateItem: new ObjectXMLField('actionPlanTemplateItem', 'Action Plan Template Item')
        .setMinApi(47)
        .setEditable()
        .setFieldKey('name')
        .addField('actionPlanTemplateItemValue', new ArrayXMLField('actionPlanTemplateItemValue', 'Action Plan Template Item Value')
            .setEditable()
            .setFieldKey('name')
            .addField('itemEntityType', new StringXMLField('itemEntityType', 'Item Entity Type')
                .setEditable()
                .setRequired()
            )
            .addField('name', new StringXMLField('name', 'Name')
                .setUnique()
                .setEditable()
                .setRequired()
            )
            .addField('valueFormula', new StringXMLField('valueFormula', 'Value Formula')
                .setEditable()
            )
            .addField('valueLiteral', new StringXMLField('valueLiteral', 'Value Literal')
                .setEditable()
            )
        )
        .addField('displayOrder', new IntegerXMLField('displayOrder', 'Display Order')
            .setEditable()
            .setUnique()
        )
        .addField('isRequired', new BooleanXMLField('isRequired', 'Is Required')
            .setEditable()
            .setRequired()
            .setDefaultValue(true)
        )
        .addField('itemEntityType', new StringXMLField('itemEntityType', 'Item Entity Type')
            .setMinApi(48)
            .setEditable()
            .setRequired()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('uniqueName', new StringXMLField('uniqueName', 'Unique Name')
            .setUnique()
            .setEditable()
            .setRequired()
        ),
    description: new StringXMLField('description', 'Description')
        .setMinApi(47)
        .setEditable(),
    name: new StringXMLField('name', 'Name')
        .setMinApi(47)
        .setEditable()
        .setRequired(),
    targetEntityType: new StringXMLField('targetEntityType', 'Target Entity Type')
        .setMinApi(47)
        .setEditable()
        .setRequired(),
    uniqueName: new StringXMLField('uniqueName', 'Unique Name')
        .setMinApi(47)
        .setUnique()
        .setEditable()
        .setRequired()
};