const { StringXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField, BooleanXMLField, XMLDependencyField } = require('@ah/core').Types;
const { DataValues } = require('@ah/core').Values;

module.exports = {
    audienceName: new StringXMLField('audienceName', 'Audience Name')
        .setMinApi(44)
        .setEditable()
        .setRequired(),
    container: new StringXMLField('container', 'Container')
        .setMinApi(44)
        .setEditable()
        .setRequired(),
    criteria: new ObjectXMLField('criteria', 'Criteria')
        .setMinApi(47)
        .setEditable()
        .setRequired()
        .setFieldKey('criterion')
        .setSortOrder(undefined)
        .addField('criterion', new ArrayXMLField('criterion', 'Criterion')
            .setEditable()
            .setFieldKey('criteriaNumber')
            .addField('criteriaNumber', new IntegerXMLField('criteriaNumber', 'Criteria Number')
                .setMinApi(45)
                .setEditable()
            )
            .addField('criterionValue', new ObjectXMLField('criterionValue', 'Criterion Value')
                .setEditable()
                .setFieldKey('isEnabled')
                .setSortOrder(undefined)
                .addField('city', new StringXMLField('city', 'City')
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['Domain', 'Profile', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
                )
                .addField('country', new StringXMLField('country', 'Country')
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['Domain', 'Profile', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
                )
                .addField('domain', new StringXMLField('domain', 'Domain')
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['Domain'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Profile', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
                )
                .addField('entityField', new StringXMLField('entityField', 'Entity Field')
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['FieldBased'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'Permission'], DataValues.NOT_AVAILABLE))
                )
                .addField('entityType', new StringXMLField('entityType', 'Entity Type')
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['FieldBased'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'Permission'], DataValues.NOT_AVAILABLE))
                )
                .addField('fieldValue', new StringXMLField('fieldValue', 'Field Value')
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['FieldBased'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'Permission'], DataValues.NOT_AVAILABLE))
                )
                .addField('isEnabled', new StringXMLField('isEnabled', 'Is Enabled')
                    .setMinApi(45)
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['Permission'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'FieldBased'], DataValues.NOT_AVAILABLE))
                )
                .addField('permissionName', new StringXMLField('permissionName', 'Permission Name')
                    .setMinApi(45)
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['Permission'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'FieldBased'], DataValues.NOT_AVAILABLE))
                )
                .addField('permissionType', new StringXMLField('permissionType', 'Permission Type')
                    .setMinApi(45)
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['Permission'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'FieldBased'], DataValues.NOT_AVAILABLE))
                )
                .addField('profile', new StringXMLField('profile', 'Profile')
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['Profile'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
                )
                .addField('subdivision', new StringXMLField('subdivision', 'Subdivision')
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('type', ['GeoLocation'], DataValues.AVAILABLE))
                    .addDependencyField(new XMLDependencyField('type', ['Domain', 'Profile', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
                )
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .addEnumValue('Equal', 'Equal')
                .addEnumValue('Not Equal', 'NotEqual')
                .addEnumValue('Less Than', 'LessThan')
                .addEnumValue('Greater Than', 'GreaterThan')
                .addEnumValue('Less Or Equal', 'LessThanOrEqual')
                .addEnumValue('Greater Or Equal', 'GreaterThanOrEqual')
                .addEnumValue('Contains', 'Contains')
                .addEnumValue('Starts With', 'StartsWith')
                .addEnumValue('Includes', 'Includes', 45)
                .addEnumValue('Not Includes', 'NotIncludes', 45)
            )
            .addField('type', new EnumXMLField('type', 'Type')
                .setEditable()
                .addEnumValue('Geo Location', 'GeoLocation')
                .addEnumValue('Domain', 'Domain')
                .addEnumValue('Profile', 'Profile')
                .addEnumValue('Field Based', 'FieldBased')
                .addEnumValue('Permission', 'Permission', 45)
                .addEnumValue('Default', 'Default', 47)
            )
        ),
    criterion: new ArrayXMLField('criterion', 'Criterion')
        .setMinApi(44)
        .setMaxApi(46)
        .setEditable()
        .setFieldKey('criteriaNumber')
        .addField('criteriaNumber', new IntegerXMLField('criteriaNumber', 'Criteria Number')
            .setMinApi(45)
            .setEditable()
        )
        .addField('criterionValue', new ObjectXMLField('criterionValue', 'Criterion Value')
            .setEditable()
            .setFieldKey('isEnabled')
            .setSortOrder(undefined)
            .addField('city', new StringXMLField('city', 'City')
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['Domain', 'Profile', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
            )
            .addField('country', new StringXMLField('country', 'Country')
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['Domain', 'Profile', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
            )
            .addField('domain', new StringXMLField('domain', 'Domain')
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['Domain'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Profile', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
            )
            .addField('entityField', new StringXMLField('entityField', 'Entity Field')
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['FieldBased'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'Permission'], DataValues.NOT_AVAILABLE))
            )
            .addField('entityType', new StringXMLField('entityType', 'Entity Type')
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['FieldBased'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'Permission'], DataValues.NOT_AVAILABLE))
            )
            .addField('fieldValue', new StringXMLField('fieldValue', 'Field Value')
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['FieldBased'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'Permission'], DataValues.NOT_AVAILABLE))
            )
            .addField('isEnabled', new StringXMLField('isEnabled', 'Is Enabled')
                .setMinApi(45)
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['Permission'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'FieldBased'], DataValues.NOT_AVAILABLE))
            )
            .addField('permissionName', new StringXMLField('permissionName', 'Permission Name')
                .setMinApi(45)
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['Permission'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'FieldBased'], DataValues.NOT_AVAILABLE))
            )
            .addField('permissionType', new StringXMLField('permissionType', 'Permission Type')
                .setMinApi(45)
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['Permission'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'Profile', 'FieldBased'], DataValues.NOT_AVAILABLE))
            )
            .addField('profile', new StringXMLField('profile', 'Profile')
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['Profile'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation', 'Domain', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
            )
            .addField('subdivision', new StringXMLField('subdivision', 'Subdivision')
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['GeoLocation'], DataValues.AVAILABLE))
                .addDependencyField(new XMLDependencyField('type', ['Domain', 'Profile', 'FieldBased', 'Permission'], DataValues.NOT_AVAILABLE))
            )
        )
        .addField('operator', new EnumXMLField('operator', 'Operator')
            .setEditable()
            .addEnumValue('Equal', 'Equal')
            .addEnumValue('Not Equal', 'NotEqual')
            .addEnumValue('Less Than', 'LessThan')
            .addEnumValue('Greater Than', 'GreaterThan')
            .addEnumValue('Less Or Equal', 'LessThanOrEqual')
            .addEnumValue('Greater Or Equal', 'GreaterThanOrEqual')
            .addEnumValue('Contains', 'Contains')
            .addEnumValue('Starts With', 'StartsWith')
            .addEnumValue('Includes', 'Includes', 45)
            .addEnumValue('Not Includes', 'NotIncludes', 45)
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .addEnumValue('Geo Location', 'GeoLocation')
            .addEnumValue('Domain', 'Domain')
            .addEnumValue('Profile', 'Profile')
            .addEnumValue('Field Based', 'FieldBased')
            .addEnumValue('Permission', 'Permission', 45)
            .addEnumValue('Default', 'Default', 47)
        ),
    description: new StringXMLField('description', 'Description')
        .setMinApi(44)
        .setEditable(),
    formula: new StringXMLField('formula', 'Formula')
        .setMinApi(45)
        .setEditable(),
    formulaFilterType: new EnumXMLField('formulaFilterType', 'Formula Filter Type')
        .setMinApi(44)
        .setEditable()
        .addEnumValue('All Criteria Match', 'AllCriteriaMatch')
        .addEnumValue('Any Criterion Matches', 'AnyCriterionMatches')
        .addEnumValue('Custom Logic Matches', 'CustomLogicMatches', 45),
    isDefaultAudience: new BooleanXMLField('isDefaultAudience', 'Is Default Audience')
        .setMinApi(48)
        .setEditable(),
    targets: new ObjectXMLField('targets', 'Targets')
        .setMinApi(47)
        .setEditable()
        .setFieldKey('target')
        .addField('target', new ArrayXMLField('target', 'Target')
            .setMinApi(47)
            .setEditable()
            .setFieldKey('groupName')
            .addField('groupName', new StringXMLField('groupName', 'Group Name')
                .setEditable()
                .setRequired()
            )
            .addField('priority', new IntegerXMLField('priority', 'Priority')
                .setEditable()
            )
            .addField('targetType', new EnumXMLField('targetType', 'Target Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Experience Variation', 'ExperienceVariation', 47)
                .addEnumValue('Navigation Link Set', 'NavigationLinkSet', 49)
                .addEnumValue('Report', 'Report', 49)
                .addEnumValue('Dashboard', 'Dashboard', 49)
            )
            .addField('targetValue', new StringXMLField('targetValue', 'Target Value')
                .setEditable()
                .setRequired()
            )
        )
}