const { StringXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField, BooleanXMLField, XMLDependencyField } = require('@ah/core').Types;
const { MetadataTypes, DataValues } = require('@ah/core').Values;

module.exports = {
    aggregates: new ArrayXMLField('aggregates', 'Aggregates')
        .setMinApi(51)
        .setEditable()
        .setFieldKey('name')
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('fields', new ArrayXMLField('fields', 'Fields')
            .setEditable()
            .setRequired()
            .setFieldKey('sourceFieldName')
            .addField('aggregateFunction', new EnumXMLField('aggregateFunction', 'Aggregate Function')
                .setEditable()
                .setRequired()
                .addEnumValue('Unique', 'Unique')
                .addEnumValue('Sum', 'Sum')
                .addEnumValue('Max', 'Max')
                .addEnumValue('Min', 'Min')
                .addEnumValue('Average', 'Avg')
                .addEnumValue('Standard Deviation', 'Std')
                .addEnumValue('Standard Deviation with Population Variance', 'Stdp')
                .addEnumValue('Variance', 'Var')
                .addEnumValue('Variance with Population', 'VarP')
                .addEnumValue('Count', 'Count')
            )
            .addField('alias', new StringXMLField('alias', 'Alias')
                .setEditable()
                .setRequired()
            )
            .addField('sourceFieldName', new StringXMLField('sourceFieldName', 'Source Field Name')
                .setEditable()
                .setRequired()
            )
        )
        .addField('groupBy', new ArrayXMLField('groupBy', 'Group By')
            .setEditable()
            .setRequired()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('sourceName', new StringXMLField('sourceName', 'Source Name')
            .setEditable()
            .setRequired()
        ),
    appends: new ArrayXMLField('appends', 'Appends')
        .setMinApi(51)
        .setEditable()
        .setFieldKey('name')
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('isDisjointedSchema', new BooleanXMLField('isDisjointedSchema', 'Is Disjointed Schema')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
        )
        .addField('sources', new ArrayXMLField('sources', 'Sources')
            .setEditable()
        ),
    datasources: new ArrayXMLField('datasources', 'Data Sources')
        .setMinApi(51)
        .setEditable()
        .setFieldKey('name')
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('fields', new ArrayXMLField('fields', 'Fields')
            .setEditable()
            .setRequired()
            .setFieldKey('name')
            .addField('alias', new StringXMLField('alias', 'Alias')
                .setEditable()
            )
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('sourceName', new StringXMLField('sourceName', 'Source Name')
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .setRequired()
            .setDefaultValue('StandardObject')
            .addEnumValue('Standard Object', 'StandardObject')
        ),
    description: new StringXMLField('description', 'Description')
        .setMinApi(51)
        .setEditable(),
    filter: new ArrayXMLField('filter', 'Filter')
        .setMinApi(51)
        .setEditable()
        .setFieldKey('name')
        .addField('criteria', new ArrayXMLField('criteria', 'Criteria')
            .setEditable()
            .setFieldKey('inputVariable')
            .addField('inputVariable', new StringXMLField('inputVariable', 'Input Variable')
                .setEditable()
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Equals', 'Equals')
                .addEnumValue('Not Equals', 'NotEquals')
                .addEnumValue('Greater Than', 'GreaterThan')
                .addEnumValue('Greater Than Or Equal', 'GreaterThanOrEqual')
                .addEnumValue('Less Than', 'LessThan')
                .addEnumValue('Less Than Or Equal', 'LessThanOrEqual')
                .addEnumValue('Starts With', 'StartsWith')
                .addEnumValue('Ends With', 'EndsWith')
                .addEnumValue('Contains', 'Contains')
                .addEnumValue('Does Not Contain', 'DoesNotContain')
                .addEnumValue('Is Null', 'IsNull')
                .addEnumValue('Is Not Null', 'IsNotNull')
            )
            .addField('sequence', new IntegerXMLField('sequence', 'Sequence')
                .setEditable()
                .setRequired()
            )
            .addField('sourceFieldName', new StringXMLField('sourceFieldName', 'Source Field Name')
                .setEditable()
                .setRequired()
            )
            .addField('value', new IntegerXMLField('value', 'Value')
                .setEditable()
            )
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('filterCondition', new StringXMLField('filterCondition', 'filterCondition')
            .setEditable()
            .setRequired()
            .addDependencyField(new XMLDependencyField('isDynamicFilter', true, DataValues.NULL))
        )
        .addField('filterParameterName', new StringXMLField('filterParameterName', 'Filter Parameter Name')
            .setEditable()
        )
        .addField('isDynamicFilter', new BooleanXMLField('isDynamicFilter', 'Is Dynamic Filter')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('sourceName', new StringXMLField('sourceName', 'Source Name')
            .setEditable()
            .setRequired()
        ),
    isTemplate: new BooleanXMLField('isTemplate', 'Is Template')
        .setMinApi(51)
        .setEditable(),
    joins: new ArrayXMLField('joins', 'Joins')
        .setMinApi(51)
        .setEditable()
        .setFieldKey('name')
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('fields', new ArrayXMLField('fields', 'Fields')
            .setEditable()
            .setFieldKey('alias')
            .addField('alias', new StringXMLField('alias', 'Alias')
                .setEditable()
                .setRequired()
            )
            .addField('sourceFieldName', new StringXMLField('sourceFieldName', 'Source Field Name')
                .setEditable()
                .setRequired()
            )
            .addField('sourceName', new StringXMLField('sourceName', 'Source Name')
                .setEditable()
                .setRequired()
            )
        )
        .addField('joinKeys', new ArrayXMLField('joinKeys', 'Join Keys')
            .setEditable()
            .setFieldKey(['primarySourceFieldNam', 'secondarySourceFieldName'])
            .setSortOrder(['primarySourceFieldName', 'secondarySourceFieldName'])
            .addField('primarySourceFieldName', new StringXMLField('primarySourceFieldName', 'Primary Source Field Name')
                .setEditable()
                .setRequired()
            )
            .addField('secondarySourceFieldName', new StringXMLField('secondarySourceFieldName', 'Secondary Source Field Name')
                .setEditable()
                .setRequired()
            )
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('primarySourceName', new StringXMLField('primarySourceName', 'Primary Source Name')
            .setEditable()
            .setRequired()
        )
        .addField('secondarySourceName', new StringXMLField('secondarySourceName', 'Secondary Source Name')
            .setEditable()
            .setRequired()
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Left Outer', 'LeftOuter')
            .addEnumValue('Right Outer', 'RightOuter')
            .addEnumValue('Inner', 'Inner')
            .addEnumValue('Outer', 'Outer')
            .addEnumValue('Lookup', 'Lookup')
        ),
    label: new StringXMLField('label', 'Label')
        .setMinApi(51)
        .setEditable(),
    parameters: new ArrayXMLField('parameters', 'Parameters')
        .setMinApi(51)
        .setEditable()
        .setFieldKey('name')
        .addField('dataType', new EnumXMLField('dataType', 'Data Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Text', 'Text')
            .addEnumValue('Numeric', 'Numeric')
            .addEnumValue('Date', 'Date')
            .addEnumValue('DateTime', 'DateTime')
            .addEnumValue('Filter', 'Filter')
        )
        .addField('defaultValue', new StringXMLField('defaultValue', 'Default Value')
            .setEditable()
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('isMultiValue', new BooleanXMLField('isMultiValue', 'Is Multi Value')
            .setEditable()
        )
        .addField('label', new BooleanXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('name', new BooleanXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        ),
    processType: new EnumXMLField('processType', 'Process Type')
        .setMinApi(51)
        .setEditable()
        .addEnumValue('Data Processing Engine', 'DataProcessingEngine')
        .addEnumValue('Rebates', 'Rebates')
        .addEnumValue('FSC Hierarchy Roll Up', 'FSCHierarchyRollUp')
        .addEnumValue('Loyalty', 'Loyalty'),
    status: new EnumXMLField('status', 'Status')
        .setMinApi(51)
        .setEditable()
        .addEnumValue('Active', 'Active')
        .addEnumValue('Inactive', 'Inactive'),
    transforms: new ArrayXMLField('transforms', 'Transforms')
        .setMinApi(51)
        .setEditable()
        .setFieldKey('name')
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('droppedFields', new ArrayXMLField('droppedFields', 'Dropped Fields')
            .setEditable()
            .setFieldKey('sourceFieldName')
            .addField('sourceFieldName', new StringXMLField('sourceFieldName', 'Source Field Name')
                .setEditable()
            )
        )
        .addField('expressionFields', new ArrayXMLField('expressionFields', 'Expression Fields')
            .setEditable()
            .setFieldKey('alias')
            .addField('alias', new StringXMLField('alias', 'Alias')
                .setEditable()
                .setRequired()
            )
            .addField('dataType', new EnumXMLField('dataType', 'Data Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Text', 'Text')
                .addEnumValue('Numeric', 'Numeric')
                .addEnumValue('Date', 'Date')
                .addEnumValue('DateTime', 'DateTime')
            )
            .addField('decimalPlaces', new IntegerXMLField('decimalPlaces', 'Decimal Places')
                .setEditable()
            )
            .addField('expression', new StringXMLField('expression', 'Expression')
                .setEditable()
                .setRequired()
            )
            .addField('length', new IntegerXMLField('length', 'Length')
                .setEditable()
                .setRequired()
                .addDependencyField(new XMLDependencyField('dataType', ['Date', 'DateTime'], DataValues.NULL))
            )
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('sourceName', new StringXMLField('sourceName', 'Source Name')
            .setEditable()
            .setRequired()
        )
        .addField('transformType', new EnumXMLField('transformType', 'Transform Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Expression', 'Expression')
            .addEnumValue('Slice', 'Slice')
        ),
    writebacks: new ArrayXMLField('writebacks', 'Writebacks')
        .setMinApi(51)
        .setEditable()
        .setFieldKey('name')
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('fields', new ArrayXMLField('fields', 'Fields')
            .setEditable()
            .setFieldKey('sourceFieldName')
            .addField('parentName', new StringXMLField('parentName', 'Parent Name')
                .setEditable()
                .setRequired()
                .addDependencyField(new XMLDependencyField('relationshipName', DataValues.NULL, DataValues.NULL))
            )
            .addField('relationshipName', new StringXMLField('relationshipName', 'Relationship Name')
                .setEditable()
            )
            .addField('sourceFieldName', new StringXMLField('sourceFieldName', 'Source Field Name')
                .setEditable()
                .setRequired()
            )
            .addField('targetFieldName', new StringXMLField('targetFieldName', 'Target Field Name')
                .setEditable()
                .setRequired()
            )
        )
        .addField('isChangedRow', new BooleanXMLField('isChangedRow', 'Is Changed Row')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('operationType', new EnumXMLField('operationType', 'Operation Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Insert', 'Insert')
            .addEnumValue('Update', 'Update')
            .addEnumValue('Upsert', 'Upsert')
        )
        .addField('sourceName', new StringXMLField('sourceName', 'Source Name')
            .setEditable()
            .setRequired()
        )
        .addField('targetObjectName', new StringXMLField('targetObjectName', 'Target Object Name')
            .setEditable()
            .setRequired()
        )
        .addField('writebackSequence', new IntegerXMLField('writebackSequence', 'Writeback Sequence')
            .setEditable()
        )
        .addField('writebackUser', new StringXMLField('writebackUser', 'Writeback User')
            .setEditable()
        )

}