const { StringXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField, BooleanXMLField, XMLDependencyField } = require('@ah/core').Types;
const { DataValues } = require('@ah/core').Values;
const BotInvocationType = require('./types/botInvocation');
const BotMessageType = require('./types/botMessage');
const BotNavigationType = require('./types/botNavigation');

module.exports = {
    botDialogGroups: new ArrayXMLField('botDialogGroups', 'Bot Dialog Groups')
        .setMinApi(43)
        .setEditable()
        .setFieldKey('developerName')
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('developerName', new StringXMLField('developerName', 'Developer Name')
            .setEditable()
            .setRequired()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        ),
    botDialogs: new ArrayXMLField('botDialogs', 'Bot Dialogs')
        .setMinApi(43)
        .setEditable()
        .setFieldKey('developerName')
        .addField('botDialogGroup', new StringXMLField('botDialogGroup', 'Bot Dialog Group')
            .setEditable()
        )
        .addField('botSteps', new ArrayXMLField('botSteps', 'Bot Steps')
            .setEditable()
            .setFieldKey('type')
            .setSortOrder(undefined)
            .addField('booleanFilter', new StringXMLField('booleanFilter', 'Boolean Filter')
                .setEditable()
            )
            .addField('botInvocation', BotInvocationType('botInvocation', 'Bot Invocation')
            )
            .addField('botMessages', BotMessageType('botMessages', 'Bot Messages'))
            .addField('botNavigation', BotNavigationType('botNavigation', 'Bot Navigation'))
            .addField('botStepConditions', new ArrayXMLField('botStepConditions', 'Bot Step Conditions')
                .setEditable()
                .setFieldKey('leftOperandType')
                .setSortOrder(undefined)
                .addField('leftOperandName', new StringXMLField('leftOperandName', 'Left Operand Name')
                    .setEditable()
                    .setRequired()
                )
                .addField('leftOperandType', new EnumXMLField('leftOperandType', 'Left Operand Type')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Conversation Variable', 'ConversationVariable')
                    .addEnumValue('Context Variable', 'ContextVariable')
                )
                .addField('operatorType', new EnumXMLField('operatorType', 'Operator Type')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Equals', 'Equals')
                    .addEnumValue('Not Equals', 'NotEquals')
                    .addEnumValue('Is Not Set', 'IsNotSet')
                    .addEnumValue('Greater Than', 'GreaterThan', 47)
                    .addEnumValue('Less Than', 'LessThan', 47)
                    .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo', 47)
                    .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo', 47)
                )
                .addField('rightOperandValue', new StringXMLField('rightOperandValue', 'Right Operand Value')
                    .setEditable()
                    .addDependencyField(new XMLDependencyField('operatorType', ['IsNotSet', 'IsSet'], DataValues.NOT_AVAILABLE))
                )
            )
            .addField('botSteps', new ArrayXMLField('botSteps', 'Bot Steps')
                .setEditable()
                .setDefinitionReference('this>botVersions>botDialogs>botSteps')
            )
            .addField('botVariableOperation', new ArrayXMLField('botVariableOperation', 'Bot Variable Operation')
                .setEditable()
                .setFieldKey('botInvocation')
                .setSortOrder(undefined)
                .addField('botInvocation', BotInvocationType('botInvocation', 'Bot Invocation'))
                .addField('botMessages', BotMessageType('botMessages', 'Bot Messages'))
                .addField('botQuickReplyOptions', new ArrayXMLField('botQuickReplyOptions', 'Bot Quick Reply Options')
                    .setEditable()
                    .setFieldKey('literalValue')
                    .setSortOrder(undefined)
                    .addField('literalValue', new StringXMLField('literalValue', 'Literal Value')
                        .setEditable()
                        .setRequired()
                    )
                )
                .addField('botVariableOperands', new ArrayXMLField('botVariableOperands', 'Bot Variable Operands')
                    .setEditable()
                    .setFieldKey('targetName')
                    .addField('disableAutoFill', new BooleanXMLField('disableAutoFill', 'Disable Auto Fill')
                        .setEditable()
                    )
                    .addField('sourceName', new StringXMLField('sourceName', 'Source Name')
                        .setEditable()
                    )
                    .addField('sourceType', new EnumXMLField('sourceType', 'Source Type')
                        .setEditable()
                        .addEnumValue('Standard Conversation Variable', 'StandardConversationVariable')
                        .addEnumValue('Conversation Variable', 'ConversationVariable')
                        .addEnumValue('Context Variable', 'ContextVariable')
                        .addEnumValue('Machine Learning Slot Class', 'MlSlotClass', 45)
                        .addEnumValue('Standard Machine Learning Slot Class', 'StandardMlSlotClass', 45)
                        .addEnumValue('Value', 'Value', 45)
                    )
                    .addField('sourceValue', new StringXMLField('sourceValue', 'Source Value')
                        .setEditable()
                    )
                    .addField('targetName', new StringXMLField('targetName', 'Target Name')
                        .setEditable()
                        .setRequired()
                    )
                    .addField('targetType', new EnumXMLField('targetType', 'Target Type')
                        .setEditable()
                        .setRequired()
                        .addEnumValue('Conversation Variable', 'ConversationVariable')
                        .addEnumValue('Context Variable', 'ContextVariable')
                    )
                )
                .addField('invalidInputBotNavigation', BotNavigationType('invalidInputBotNavigation', 'Invalid Input Bot Navigation'))
                .addField('optionalCollect', new BooleanXMLField('optionalCollect', 'Optional Collect')
                    .setMinApi(48)
                    .setEditable()
                )
                .addField('quickReplyOptionTemplate', new StringXMLField('quickReplyOptionTemplate', 'Quick Reply Option Template')
                    .setEditable()
                )
                .addField('quickReplyType', new EnumXMLField('quickReplyType', 'Quick Reply Type')
                    .setEditable()
                    .addEnumValue('Static', 'Static')
                    .addEnumValue('Dynamic', 'Dynamic')
                )
                .addField('quickReplyWidgetType', new EnumXMLField('quickReplyWidgetType', 'Quick Reply Widget Type')
                    .setEditable()
                    .addEnumValue('Menu', 'Menu')
                    .addEnumValue('Buttons', 'Buttons')
                )
                .addField('retryMessages', BotMessageType('retryMessages', 'Retry Messages', 48))
                .addField('sourceVariableName', new StringXMLField('sourceVariableName', 'Source Variable Name')
                    .setMinApi(47)
                    .setEditable()
                )
                .addField('sourceVariableType', new EnumXMLField('sourceVariableType', 'Source Variable Type')
                    .setMinApi(47)
                    .setEditable()
                    .addEnumValue('Conversation Variable', 'ConversationVariable')
                    .addEnumValue('Context Variable', 'ContextVariable')
                )
                .addField('type', new EnumXMLField('type', 'Type')
                    .setEditable()
                    .addEnumValue('Set', 'Set')
                    .addEnumValue('Unset', 'Unset')
                    .addEnumValue('Collect', 'Collect')
                )
            )
            .addField('conversationRecordLookup', new ArrayXMLField('conversationRecordLookup', 'Conversation Record Lookup')
                .setMinApi(46)
                .setEditable()
                .setFieldKey('SObjectType')
                .setSortOrder(undefined)
                .addField('lookupFields', new ArrayXMLField('lookupFields', 'Lookup Fields')
                    .setEditable()
                    .setFieldKey('fieldName')
                    .addField('fieldName', new StringXMLField('fieldName', 'Field Name')
                        .setEditable()
                    )
                )
                .addField('maxLookupResults', new IntegerXMLField('maxLookupResults', 'Max Lookup Results')
                    .setEditable()
                    .setRequired()
                )
                .addField('SObjectType', new StringXMLField('SObjectType', 'SObject Type')
                    .setEditable()
                    .setRequired()
                )
                .addField('sourceVariableName', new StringXMLField('sourceVariableName', 'Source Variable Name')
                    .setEditable()
                    .setRequired()
                )
                .addField('sourceVariableType', new EnumXMLField('sourceVariableType', 'Source Variable Type')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Conversation Variable', 'ConversationVariable')
                    .addEnumValue('Context Variable', 'ContextVariable')
                )
                .addField('targetVariableName', new StringXMLField('targetVariableName', 'Target Variable Name')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('conversationSystemMessage', new ArrayXMLField('conversationSystemMessage', 'Conversation System Message')
                .setEditable()
                .setFieldKey('systemMessageMappings')
                .setSortOrder(undefined)
                .addField('systemMessageMappings', new ObjectXMLField('systemMessageMappings', 'System Message Mappings')
                    .setEditable()
                    .setFieldKey('variableName')
                    .addField('mappingType', new EnumXMLField('mappingType', 'Mapping Type')
                        .setEditable()
                        .setRequired()
                        .addEnumValue('Input', 'Input')
                        .addEnumValue('Output', 'Output')
                    )
                    .addField('parameterType', new EnumXMLField('parameterType', 'Parameter Type')
                        .setEditable()
                        .setRequired()
                        .addEnumValue('Transfer', 'Transfer')
                    )
                    .addField('variableName', new StringXMLField('variableName', 'Variable Name')
                        .setEditable()
                        .setRequired()
                    )
                )
            )
            .addField('type', new EnumXMLField('type', 'Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Navigation', 'Navigation')
                .addEnumValue('Invocation', 'Invocation')
                .addEnumValue('Variable Operation', 'VariableOperation')
                .addEnumValue('Message', 'Message')
                .addEnumValue('Wait', 'Wait')
                .addEnumValue('Group', 'Group')
                .addEnumValue('Record Lookup', 'RecordLookup', 48)
            )
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('developerName', new StringXMLField('developerName', 'Developer Name')
            .setEditable()
            .setRequired()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('mlIntent', new StringXMLField('mlIntent', 'Machine Learning Intent')
            .setEditable()
            .setRequired()
        )
        .addField('mlIntentTrainingEnabled', new BooleanXMLField('mlIntentTrainingEnabled', 'Machine Learning Intent Training Enabled')
            .setMinApi(46)
            .setEditable()
            .setRequired()
        )
        .addField('showInFooterMenu', new BooleanXMLField('showInFooterMenu', 'Show In Footer Menu')
            .setEditable()
            .setRequired()
        ),
    conversationSystemDialogs: new ArrayXMLField('conversationSystemDialogs', 'Conversation System Dialogs')
        .setMinApi(48)
        .setEditable()
        .setFieldKey('dialog')
        .setSortOrder(undefined)
        .addField('dialog', new StringXMLField('dialog', 'Dialog')
            .setEditable()
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .addEnumValue('Transfer Failed', 'TransferFailed')
        ),
    conversationVariables: new ArrayXMLField('conversationVariables', 'Conversation Variables')
        .setMinApi(44)
        .setEditable()
        .setFieldKey('developerName')
        .addField('collectionType', new EnumXMLField('collectionType', 'Collection Type')
            .setEditable()
            .addEnumValue('List', 'List')
        )
        .addField('dataType', new EnumXMLField('dataType', 'Data Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Boolean', 'Boolean')
            .addEnumValue('Currency', 'Currency')
            .addEnumValue('Date', 'Date')
            .addEnumValue('DateTime', 'DateTime')
            .addEnumValue('Id', 'Id', 45)
            .addEnumValue('Object', 'Object')
            .addEnumValue('Number', 'Number')
            .addEnumValue('Text', 'Text')
        )
        .addField('developerName', new StringXMLField('developerName', 'Developer Name')
            .setEditable()
            .setRequired()
            .setUnique()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('SObjectType', new EnumXMLField('SObjectType', 'SObject Type')
            .setEditable()
            .addEnumValue('Bot Definition', 'Bot Definition')
            .addEnumValue('Queue', 'Queue')
        ),
    entryDialog: new StringXMLField('entryDialog', 'Entry Dialog')
        .setEditable()
        .setRequired(),
    mainMenuDialog: new StringXMLField('mainMenuDialog', 'Main Menu Dialog')
        .setEditable()
        .setRequired(),
    nlpProviders: new ArrayXMLField('nlpProviders', 'Natural Language Processor Providers')
        .setEditable()
        .setRequired()
        .setFieldKey('nlpProviderName')
        .addField('language', new StringXMLField('language', 'Language')
            .setEditable()
            .setRequired()
        )
        .addField('nlpProviderName', new StringXMLField('nlpProviderName', 'Natural Language Processor Provider Name')
            .setEditable()
            .setRequired()
        )
        .addField('nlpProviderType', new EnumXMLField('nlpProviderType', 'Natural Language Processor Provider Type')
            .setEditable()
            .setRequired()
            .setDefaultValue('EinsteinAi')
            .addEnumValue('Einstein AI', 'EinsteinAi')
            .addEnumValue('Apex', 'Apex')
        ),
    responseDelayMilliseconds: new IntegerXMLField('responseDelayMilliseconds', 'Response Delay Milliseconds')
        .setEditable()
}