const { StringXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField } = require('@ah/core').Types;


module.exports = {
    briefcaseRules: new ArrayXMLField('briefcaseRules', 'Briefcase Rules')
        .setMinApi(50)
        .setEditable()
        .setFieldKey('targetEntity')
        .addField('briefcaseRuleFilters', new ArrayXMLField('briefcaseRuleFilters', 'Briefcase Rule Filters')
            .setEditable()
            .setRequired()
            .setFieldKey('targetEntityField')
            .addField('filterOperator', new EnumXMLField('filterOperator', 'Filter Operator')
                .setEditable()
                .addEnumValue('Ends with', 'd')
                .addEnumValue('Equals', 'e')
                .addEnumValue('Greater than', 'g')
                .addEnumValue('Greater than or equal', 'h')
                .addEnumValue('Less than', 'l')
                .addEnumValue('Less than or equal', 'm')
                .addEnumValue('Starts with', 's')
            )
            .addField('filterSeqNumber', new IntegerXMLField('filterSeqNumber', 'Filter Sequence Number')
                .setEditable()
                .setRequired()
            )
            .addField('filterValue', new StringXMLField('filterValue', 'Filter Value')
                .setEditable()
                .setRequired()
            )
            .addField('targetEntityField', new StringXMLField('targetEntityField', 'Target Entity Field')
                .setEditable()
                .setRequired()
            )
        )
}