const { StringXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField } = require('@aurahelper/core').Types;


module.exports = {
    businessProcessDefinitions: new ArrayXMLField('businessProcessDefinitions', 'Business Process Definitions')
        .setMinApi(49)
        .setEditable()
        .setFieldKey('developerName')
        .addField('businessProcessFeedbacks', new ArrayXMLField('businessProcessFeedbacks', 'Business Process Feedbacks')
            .setEditable()
            .setFieldKey('actionName')
            .addField('actionName', new StringXMLField('actionName', 'Action Name')
                .setEditable()
                .setRequired()
            )
            .addField('actionParam', new StringXMLField('actionParam', 'Action Param')
                .setEditable()
                .setRequired()
            )
            .addField('actionType', new EnumXMLField('actionType', 'Action Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Survey', 'SURVEY')
            )
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('developerName', new StringXMLField('developerName', 'Developer Name')
            .setEditable()
            .setRequired()
            .setUnique()
        )
        .addField('masterLabel', new StringXMLField('masterLabel', 'Master Label')
            .setEditable()
            .setRequired()
        )
        .addField('sequenceNumber', new IntegerXMLField('sequenceNumber', 'Sequence Number')
            .setEditable()
        ),
    customerSatisfactionMetric: new EnumXMLField('customerSatisfactionMetric', 'Customer Satisfaction Metric')
        .setMinApi(49)
        .setEditable()
        .setRequired()
        .addEnumValue('CSAT', 'CSAT')
        .addEnumValue('NPS', 'NPS'),
    description: new StringXMLField('description', 'Description')
        .setMinApi(49)
        .setEditable(),
    masterLabel: new StringXMLField('masterLabel', 'Master Label')
        .setMinApi(49)
        .setEditable()
        .setRequired(),
}