import { StringXMLField, ArrayXMLField, XMLDependencyField, DataValues, EnumXMLField, IntegerXMLField } from '@aurahelper/core';

export const CMSConnectSource = {
    cmsConnectAsset: new ArrayXMLField('cmsConnectAsset', 'CMS Connect Asset')
        .setMinApi(43)
        .setEditable()
        .setFieldKey('assetPath')
        .addField('assetPath', new StringXMLField('assetPath', 'Asset Path')
            .setEditable()
        )
        .addField('assetType', new EnumXMLField('assetType', 'Asset Type')
            .setEditable()
            .addEnumValue('CSS', 'CSS')
            .addEnumValue('JavaScript', 'Javascript')
        )
        .addField('sortOrder', new IntegerXMLField('sortOrder', 'Sort Order')
            .setEditable()
            .setMinValue(0)
        ),
    cmsConnectLanguage: new ArrayXMLField('cmsConnectLanguage', 'CMS Connect Language')
        .setMinApi(43)
        .setEditable()
        .setFieldKey('language')
        .addField('cmsLanguage', new StringXMLField('cmsLanguage', 'CMS Language')
            .setEditable()
        )
        .addField('language', new EnumXMLField('language', 'Language')
            .setEditable()
            .setEnumValues(DataValues.SF_LANGUAGES)
        ),
    cmsConnectPersonalization: new ArrayXMLField('cmsConnectPersonalization', 'CMS Connect Personalization')
        .setMinApi(43)
        .setEditable()
        .setFieldKey('connectorPage')
        .addField('connectorPage', new StringXMLField('connectorPage', 'Connector Page')
            .setEditable()
        )
        .addField('connectorPageAsset', new StringXMLField('connectorPageAsset', 'Connector Page Asset')
            .setEditable()
        ),
    cmsConnectResourceType: new ArrayXMLField('cmsConnectResourceType', 'CMS Connect Resource Type')
        .setMinApi(43)
        .setEditable()
        .setFieldKey('developerName')
        .addField('cmsConnectResourceDefinition', new ArrayXMLField('cmsConnectResourceDefinition', 'CMS Connect Resource Definition')
            .setEditable()
            .setFieldKey('developerName')
            .addField('developerName', new StringXMLField('developerName', 'Developer Name')
                .setEditable()
                .setUnique()
                .setRequired()
            )
            .addField('masterLabel', new StringXMLField('masterLabel', 'Master Label')
                .setEditable()
                .setRequired()
            )
            .addField('options', new IntegerXMLField('options', 'Options')
                .setEditable()
                .setRequired()
                .setMinValue(0)
                .setMaxValue(1)
            )
            .addField('payloadType', new EnumXMLField('payloadType', 'Payload Type')
                .setEditable()
                .setRequired()
                .addEnumValue('JSON', 'JSON')
            )
            .addField('resourceIdPath', new StringXMLField('resourceIdPath', 'Resource Id Path')
                .setEditable()
            )
            .addField('resourceNamePath', new StringXMLField('resourceNamePath', 'Resource Name Path')
                .setEditable()
            )
            .addField('resourcePath', new StringXMLField('resourcePath', 'Resource Path')
                .setEditable()
                .setRequired()
            )
            .addField('rootNodePath', new StringXMLField('rootNodePath', 'Root Node Path')
                .setEditable()
            )
        )
        .addField('developerName', new StringXMLField('developerName', 'Developer Name')
            .setEditable()
            .setRequired()
            .setUnique()
        )
        .addField('masterLabel', new StringXMLField('masterLabel', 'Master Label')
            .setEditable()
            .setRequired()
        )
        .addField('resourceType', new StringXMLField('resourceType', 'Resource Type')
            .setEditable()
        ),
    connectionType: new EnumXMLField('connectionType', 'Connection Type')
        .setMinApi(43)
        .setEditable()
        .addEnumValue('Public', 'Public')
        .addEnumValue('Authenticated', 'Authenticated'),
    cssScope: new StringXMLField('cssScope', 'CSS Scope')
        .setMinApi(43)
        .setEditable(),
    developerName: new StringXMLField('developerName', 'Developer Name')
        .setMinApi(43)
        .setEditable()
        .setRequired()
        .setUnique(),
    languageEnabled: new EnumXMLField('languageEnabled', 'Language Enabled')
        .setMinApi(43)
        .setEditable()
        .setRequired()
        .addEnumValue('Yes', 'Y')
        .addEnumValue('No', 'N'),
    masterLabel: new StringXMLField('masterLabel', 'Master Label')
        .setMinApi(43)
        .setEditable()
        .setRequired(),
    namedCredential: new StringXMLField('namedCredential', 'Named Credential')
        .setMinApi(43)
        .setEditable()
        .addDependencyField(new XMLDependencyField('connectionType', 'Authenticated', DataValues.NOT_NULL)),
    personalizationEnabled: new EnumXMLField('personalizationEnabled', 'Personalization Enabled')
        .setMinApi(43)
        .setEditable()
        .addEnumValue('Yes', 'Y')
        .addEnumValue('No', 'N'),
    rootPath: new StringXMLField('rootPath', 'Root Path')
        .setMinApi(43)
        .setEditable()
        .setRequired(),
    sortOrder: new IntegerXMLField('sortOrder', 'Sort Order')
        .setMinApi(43)
        .setEditable()
        .setRequired()
        .setMinValue(1),
    status: new EnumXMLField('status', 'Status')
        .setMinApi(43)
        .setEditable()
        .setRequired()
        .addEnumValue('Active', 'ACTIVE')
        .addEnumValue('Inactive', 'INACTIVE'),
    type: new EnumXMLField('type', 'Type')
        .setMinApi(43)
        .setEditable()
        .setRequired()
        .addEnumValue('AEM', 'AEM')
        .addEnumValue('Drupal', 'Drupal')
        .addEnumValue('WordPress', 'WordPress')
        .addEnumValue('SDL', 'SDL')
        .addEnumValue('Sitecore', 'Sitecore')
        .addEnumValue('Other', 'Other'),
    websiteUrl: new StringXMLField('websiteUrl', 'website URL')
        .setMinApi(43)
        .setEditable()
        .addDependencyField(new XMLDependencyField('connectionType', 'Public', DataValues.NOT_NULL)),
}