const { StringXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField, BooleanXMLField, XMLDependencyField } = require('@ah/core').Types;
const { MetadataTypes, DataValues } = require('@ah/core').Values;
const KeyboardShortcutsType = require('./types/keyboardShortcuts');

module.exports = {
    actionOverrides: new ArrayXMLField('actionOverrides', 'Action Overrides')
        .setMinApi(38)
        .setEditable()
        .addField('actionName', new EnumXMLField('actionName', 'Action Name')
            .setEditable()
            .addEnumValue('View', 'view')
            .addEnumValue('Tab', 'tab', 44)
        )
        .addField('comment', new StringXMLField('comment', 'Comment')
            .setEditable()
        )
        .addField('content', new StringXMLField('content', 'content')
            .setEditable()
            .addDependencyField(new XMLDependencyField('type', 'flexipage', DataValues.NOT_NULL))
            .setMetadataType(MetadataTypes.FLEXI_PAGE)
        )
        .addField('formFactor', new EnumXMLField('formFactor', 'Form Factor')
            .setEditable()
            .addEnumValue('Large', 'Large')
            .addEnumValue('Medium', 'Medium')
            .addEnumValue('Small', 'Small')
            .addDependencyField(new XMLDependencyField('type', 'flexipage', 'Large'))
        )
        .addField('pageOrSobjectType', new StringXMLField('pageOrSobjectType', 'Page Or SObject Type')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
            .addDependencyField(new XMLDependencyField('actionName', 'tab', 'standard-home'))
        )
        .addField('skipRecordTypeSelect', new BooleanXMLField('skipRecordTypeSelect', 'Skip Record Type Select')
            .setEditable()
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Flexipage', 'Flexipage')
            .addEnumValue('Default', 'Default')
        ),
    brand: new ObjectXMLField('brand', 'Brand')
        .setMinApi(38)
        .setEditable()
        .addField('footerColor', new StringXMLField('footerColor', 'Footer Color')
            .setEditable()
        )
        .addField('headerColor', new StringXMLField('headerColor', 'Header Color')
            .setEditable()
        )
        .addField('logo', new StringXMLField('logo', 'Logo')
            .setEditable()
        )
        .addField('logoVersion', new IntegerXMLField('logoVersion', 'Logo Version')
            .setEditable()
        )
        .addField('shouldOverrideOrgTheme', new BooleanXMLField('shouldOverrideOrgTheme', 'Should Override Org Theme')
            .setEditable()
        ),
    consoleConfig: new ObjectXMLField('consoleConfig', 'Console Config')
        .setMinApi(42)
        .setEditable()
        .addField('componentList', new ObjectXMLField('componentList', 'Component List')
            .setEditable()
            .addField('alignment', new StringXMLField('alignment', 'Alignment')
                .setEditable()
                .setRequired()
            )
            .addField('components', new ArrayXMLField('components', 'components')
                .setMinApi(42)
                .setEditable()
                .setMetadataType(MetadataTypes.CUSTOM_APP_COMPONENT)
            )
            .addField('customApplicationComponent', new StringXMLField('customApplicationComponent', 'Custom Application Component')
                .setMaxApi(41)
                .setEditable()
                .setMetadataType(MetadataTypes.CUSTOM_APP_COMPONENT)
            )
        )
        .addField('detailPageRefreshMethod', new EnumXMLField('detailPageRefreshMethod', 'Detail Page Refresh Method')
            .setEditable()
            .addEnumValue('None', 'none')
            .addEnumValue('Auto Refresh', 'autoRefresh')
            .addEnumValue('Flag', 'flag')
            .addDependencyField(new XMLDependencyField('isServiceCloudConsole', true, DataValues.NOT_NULL))
        )
        .addField('footerColor', new StringXMLField('footerColor', 'Footer Color')
            .setEditable()
        )
        .addField('headerColor', new StringXMLField('headerColor', 'Header Color')
            .setEditable()
        )
        .addField('keyboardShortcuts', KeyboardShortcutsType('keyboardShortcuts', 'Keyboard Shortcuts', 42))
        .addField('listPlacement', new ObjectXMLField('listPlacement', 'List Placement')
            .setEditable()
            .addField('height', new IntegerXMLField('height', 'Height')
                .setEditable()
                .addDependencyField(new XMLDependencyField('location', 'top', DataValues.NOT_NULL))
            )
            .addField('location', new EnumXMLField('location', 'Location')
                .setEditable()
                .setRequired()
                .addEnumValue('Full', 'full')
                .addEnumValue('Top', 'top')
                .addEnumValue('Left', 'left')
            )
            .addField('units', new StringXMLField('units', 'Units')
                .setEditable()
                .setRequired()
            )
            .addField('width', new IntegerXMLField('width', 'Width')
                .setEditable()
                .addDependencyField(new XMLDependencyField('location', 'left', DataValues.NOT_NULL))
            )
            .addDependencyField(new XMLDependencyField('isServiceCloudConsole', true, DataValues.NOT_NULL))
        )
        .addField('listRefreshMethod', new EnumXMLField('listRefreshMethod', 'List Refresh Method')
            .setEditable()
            .addEnumValue('None', 'none')
            .addEnumValue('Refresh List', 'refreshList')
            .addEnumValue('Refresh List Rows', 'refreshListRows')
            .addDependencyField(new XMLDependencyField('isServiceCloudConsole', true, DataValues.NOT_NULL))
        )
        .addField('liveAgentConfig', new ObjectXMLField('liveAgentConfig', 'Live Agent Config')
            .setEditable()
            .addField('enableLiveChat', new BooleanXMLField('enableLiveChat', 'Enable Live Chat')
                .setEditable()
            )
            .addField('openNewAccountSubtab', new BooleanXMLField('openNewAccountSubtab', 'Open New Account Subtab')
                .setEditable()
            )
            .addField('openNewCaseSubtab', new BooleanXMLField('openNewCaseSubtab', 'Open New Case Subtab')
                .setEditable()
            )
            .addField('openNewContactSubtab', new BooleanXMLField('openNewContactSubtab', 'Open New Contact Subtab')
                .setEditable()
            )
            .addField('openNewLeadSubtab', new BooleanXMLField('openNewLeadSubtab', 'Open New Lead Subtab')
                .setEditable()
            )
            .addField('openNewVFPageSubtab', new BooleanXMLField('openNewVFPageSubtab', 'Open New Visualforce Page Subtab')
                .setEditable()
            )
            .addField('pageNamesToOpen', new ArrayXMLField('pageNamesToOpen', 'Page Names To Open')
                .setMinApi(42)
                .setEditable()
            )
            .addField('showKnowledgeArticles', new BooleanXMLField('showKnowledgeArticles', 'Show Knowledge Articles')
                .setEditable()
            )
        )
        .addField('primaryTabColor', new StringXMLField('primaryTabColor', 'Primary Tab Color')
            .setEditable()
        )
        .addField('pushNotifications', new ArrayXMLField('pushNotifications', 'Push Notifications')
            .setEditable()
            .addField('fieldNames', new ArrayXMLField('fieldNames', 'Field Names')
                .setEditable()
            )
            .addField('objectName', new StringXMLField('objectName', 'Object Name')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
            )
        )
        .addField('tabLimitConfig', new ObjectXMLField('tabLimitConfig', 'Tab Limit Config')
            .setEditable()
            .addField('maxNumberOfPrimaryTabs', new EnumXMLField('maxNumberOfPrimaryTabs', 'Max Number Of Primary Tabs')
                .setEditable()
                .addEnumValue('5', '5')
                .addEnumValue('10', '10')
                .addEnumValue('20', '20')
                .addEnumValue('30', '30')
            )
            .addField('maxNumberOfSubTabs', new EnumXMLField('maxNumberOfSubTabs', 'Max Number Of Sub Tabs')
                .setEditable()
                .addEnumValue('5', '5')
                .addEnumValue('10', '10')
                .addEnumValue('15', '15')
            )
            .addDependencyField(new XMLDependencyField('enableTabLimits', true, DataValues.NOT_NULL))
        )
        .addField('whiteListedDomains', new ArrayXMLField('whiteListedDomains', 'White Listed Domains')
            .setEditable()
        ),
    defaultLandingTab: new StringXMLField('defaultLandingTab', 'Default Landing Tab')
        .setMinApi(10)
        .setEditable()
        .setMetadataType(MetadataTypes.CUSTOM_TAB),
    description: new StringXMLField('description', 'Description')
        .setMinApi(10)
        .setEditable(),
    formFactors: new ArrayXMLField('formFactors', 'formFactors')
        .setMinApi(38)
        .setEditable()
        .addAllowedValue('Small', 'Small')
        .addAllowedValue('Medium', 'Medium')
        .addAllowedValue('Large', 'Large'),
    isNavAutoTempTabsDisabled: new BooleanXMLField('isNavAutoTempTabsDisabled', 'Is Navigation Auto Temp Tabs Disabled')
        .setMinApi(43)
        .setEditable(),
    isNavPersonalizationDisabled: new BooleanXMLField('isNavPersonalizationDisabled', 'Is Navigation Personalization Disabled')
        .setMinApi(43)
        .setEditable(),
    isServiceCloudConsole: new BooleanXMLField('isServiceCloudConsole', 'Is Service Cloud Console')
        .setMinApi(43)
        .setEditable(),
    label: new StringXMLField('label', 'Label')
        .setMinApi(10)
        .setEditable(),
    logo: new StringXMLField('logo', 'Logo')
        .setMinApi(10)
        .setEditable(),
    navType: new EnumXMLField('navType', 'Navigation Type')
        .setMinApi(38)
        .setEditable()
        .addEnumValue('Standard', 'Standard')
        .addEnumValue('Console', 'Console'),
    preferences: new ObjectXMLField('preferences', 'Preferences')
        .setMinApi(42)
        .setEditable()
        .setRequired()
        .addField('enableCustomizeMyTabs', new BooleanXMLField('enableCustomizeMyTabs', 'Enable Customize My Tabs')
            .setEditable()
            .setRequired()
        )
        .addField('enableKeyboardShortcuts', new BooleanXMLField('enableKeyboardShortcuts', 'Enable Keyboard Shortcuts')
            .setEditable()
            .addDependencyField(new XMLDependencyField('isServiceCloudConsole', true, DataValues.NOT_NULL))
        )
        .addField('enableListViewHover', new BooleanXMLField('enableListViewHover', 'Enable List View Hover')
            .setEditable()
            .setRequired()
        )
        .addField('enableListViewReskin', new BooleanXMLField('enableListViewReskin', 'Enable List View Reskin')
            .setEditable()
            .setRequired()
        )
        .addField('enableMultiMonitorComponents', new BooleanXMLField('enableMultiMonitorComponents', 'Enable Multi Monitor Components')
            .setEditable()
            .addDependencyField(new XMLDependencyField('isServiceCloudConsole', true, DataValues.NOT_NULL))
        )
        .addField('enablePinTabs', new BooleanXMLField('enablePinTabs', 'Enable Pin Tabs')
            .setEditable()
            .setRequired()
        )
        .addField('enableTabHover', new BooleanXMLField('enableTabHover', 'Enable Tab Hover')
            .setEditable()
            .setRequired()
        )
        .addField('enableTabLimits', new BooleanXMLField('enableTabLimits', 'Enable Tab Limits')
            .setEditable()
            .setRequired()
        )
        .addField('saveUserSessions', new BooleanXMLField('saveUserSessions', 'Save User Sessions')
            .setEditable()
            .addDependencyField(new XMLDependencyField('isServiceCloudConsole', true, DataValues.NOT_NULL))
        ),
    profileActionOverrides: new ArrayXMLField('profileActionOverrides', 'Profile Action Overrides')
        .setMinApi(45)
        .setEditable()
        .addField('actionName', new EnumXMLField('actionName', 'Action Name')
            .setEditable()
            .addEnumValue('View', 'view')
            .addEnumValue('Tab', 'tab', 44)
        )
        .addField('content', new StringXMLField('content', 'content')
            .setEditable()
            .addDependencyField(new XMLDependencyField('type', 'flexipage', DataValues.NOT_NULL))
        )
        .addField('formFactor', new EnumXMLField('formFactor', 'Form Factor')
            .setEditable()
            .addEnumValue('Large', 'Large')
            .addEnumValue('Medium', 'Medium')
            .addEnumValue('Small', 'Small')
            .addDependencyField(new XMLDependencyField('type', 'flexipage', 'Large'))
        )
        .addField('pageOrSobjectType', new StringXMLField('pageOrSobjectType', 'Page Or SObject Type')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
            .addDependencyField(new XMLDependencyField('actionName', 'tab', 'standard-home'))
        )
        .addField('profile', new StringXMLField('profile', 'Profile')
            .setEditable()
            .setMetadataType(MetadataTypes.PROFILE)
        )
        .addField('recordType', new StringXMLField('recordType', 'Record Type')
            .setEditable()
            .addDependencyField(new XMLDependencyField('pageOrSobjectType', 'standard-home', DataValues.NULL))
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setRequired()
            .addEnumValue('Flexipage', 'Flexipage')
        ),
    setupExperience: new EnumXMLField('setupExperience', 'Setup Experience')
        .setMinApi(39)
        .setEditable()
        .addEnumValue('All', 'all')
        .addEnumValue('Essentials', 'essentials')
        .addEnumValue('Service', 'service'),
    subscriberTabs: new ArrayXMLField('subscriberTabs', 'Subscriber Tabs')
        .setMinApi(41)
        .setEditable(),
    tabs: new ArrayXMLField('tabs', 'Tabs')
        .setMinApi(42)
        .setEditable(),
    tab: new ArrayXMLField('tab', 'Tab')
        .setMinApi(10)
        .setMaxApi(42)
        .setEditable(),
    uiType: new EnumXMLField('uiType', 'UI Type')
        .setMinApi(38)
        .setEditable()
        .addEnumValue('Aloha', 'Aloha')
        .addEnumValue('Lightning', 'Lightning'),
    utilityBar: new StringXMLField('utilityBar', 'Utility Bar')
        .setMinApi(38)
        .setEditable(),
    workspaceConfig: new ObjectXMLField('workspaceConfig', 'Workspace Config')
        .setMinApi(42)
        .addField('mappings', new ArrayXMLField('mappings', 'Mappings')
            .setEditable()
            .addField('fieldName', new StringXMLField('fieldName', 'Field Name')
                .setEditable()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('tab', new StringXMLField('tab', 'Tab')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_TAB)
            )
        )
        .addDependencyField(new XMLDependencyField('isServiceCloudConsole', true, DataValues.NOT_NULL)),
    workspaceMappings: new ObjectXMLField('workspaceMappings', 'Workspace Mappings')
        .setMinApi(10)
        .setMaxApi(41)
        .addField('workspaceMapping', new ArrayXMLField('workspaceMapping', 'Workspace Mapping')
            .setEditable()
            .addField('fieldName', new StringXMLField('fieldName', 'Field Name')
                .setEditable()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('tab', new StringXMLField('tab', 'Tab')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_TAB)
            )
        )
        .addDependencyField(new XMLDependencyField('isServiceCloudConsole', true, DataValues.NOT_NULL))
}