const { StringXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField, BooleanXMLField, XMLDependencyField } = require('../factory/xmlFactory');
const MetadataTypes = require('../values/metadataTypes');
const DataValues = require('../values/dataValues');

module.exports = {
    branding: new StringXMLField('branding', 'Branding')
        .setMinApi(47)
        .setEditable(),
    embeddedServiceCustomLabels: new ArrayXMLField('embeddedServiceCustomLabels', 'Embedded Service Custom Labels')
        .setMinApi(47)
        .setEditable()
        .setFieldKey('customLabel')
        .addField('customLabel', new StringXMLField('customLabel', 'Custom Label')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_LABEL)
        )
        .addField('feature', new EnumXMLField('feature', 'Feature')
            .setEditable()
            .addEnumValue('Channel Menu', 'ChannelMenu')
        )
        .addField('labelKey', new EnumXMLField('labelKey', 'Label Key')
            .setEditable()
            .addEnumValue('CM Container Header Primary Greeting', 'CM_Container_Header_Primary_Greeting')
            .addEnumValue('CM Container Header Secondary Greeting', 'CM_Container_Header_Secondary_Greeting')
            .addEnumValue('CM Container Menu Items WebChat Available', 'CM_Container_MenuItems_WebChatAvailable')
            .addEnumValue('CM Container Menu Items WebChat Unavailable', 'CM_Container_MenuItems_WebChatUnavailable')
            .addEnumValue('CM Container MenuItems WebChat Loading', 'CM_Container_MenuItems_WebChatLoading')
            .addEnumValue('CM Container Menu Items Channel Label', 'CM_Container_MenuItems_ChannelLabel')
            .addEnumValue('CM Container Button Assistive Text', 'CM_Container_Button_AssistiveText')
        ),
    embeddedServiceCustomizations: new ArrayXMLField('embeddedServiceCustomizations', 'Embedded Service Customizations')
        .setMinApi(50)
        .setEditable()
        .setFieldKey('customizationName')
        .addField('customizationName', new StringXMLField('customizationName', 'Customization Name')
            .setEditable()
            .setRequired()
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('embeddedServiceResources', new ArrayXMLField('embeddedServiceResources', 'Embedded Service Resources')
            .setEditable()
            .setRequired()
            .setFieldKey('resource')
            .addField('resource', new StringXMLField('resource', 'Resource')
                .setEditable()
                .setRequired()
                .linkFieldToSObject('StaticResource')
            )
            .addField('resourceType', new EnumXMLField('resourceType', 'Resource Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Chat Invitation', 'ChatInvitation')
            )
        ),
    embeddedServiceMenuItems: new ArrayXMLField('embeddedServiceMenuItems', 'Embedded Service Menu Items')
        .setMinApi(47)
        .setEditable()
        .setFieldKey('itemName')
        .addField('channel', new StringXMLField('channel', 'Channel')
            .setEditable()
            .addDependencyField(new XMLDependencyField('channelType', ['Phone', 'CustomURL'], DataValues.NULL))
        )
        .addField('channelType', new EnumXMLField('channelType', 'Channel Type')
            .setEditable()
            .addEnumValue('Embedded Service Config', 'EmbeddedServiceConfig')
            .addEnumValue('Messaging Channel', 'MessagingChannel')
            .addEnumValue('Phone', 'Phone')
            .addEnumValue('Custom URL', 'CustomURL')
        )
        .addField('customUrl', new StringXMLField('customUrl', 'Custom URL')
            .setEditable()
        )
        .addField('displayOrder', new IntegerXMLField('displayOrder', 'Display Order')
            .setEditable()
        )
        .addField('embeddedServiceCustomLabels', new ArrayXMLField('embeddedServiceCustomLabels', 'Embedded Service Custom Labels')
            .setEditable()
            .setFieldKey('customLabel')
            .addField('customLabel', new StringXMLField('customLabel', 'Custom Label')
                .setEditable()
                .setMetadataType(MetadataTypes.CUSTOM_LABEL)
            )
            .addField('feature', new EnumXMLField('feature', 'Feature')
                .setEditable()
                .addEnumValue('Channel Menu', 'ChannelMenu')
            )
            .addField('labelKey', new EnumXMLField('labelKey', 'Label Key')
                .setEditable()
                .addEnumValue('CM Container Header Primary Greeting', 'CM_Container_Header_Primary_Greeting')
                .addEnumValue('CM Container Header Secondary Greeting', 'CM_Container_Header_Secondary_Greeting')
                .addEnumValue('CM Container Menu Items WebChat Available', 'CM_Container_MenuItems_WebChatAvailable')
                .addEnumValue('CM Container Menu Items WebChat Unavailable', 'CM_Container_MenuItems_WebChatUnavailable')
                .addEnumValue('CM Container MenuItems WebChat Loading', 'CM_Container_MenuItems_WebChatLoading')
                .addEnumValue('CM Container Menu Items Channel Label', 'CM_Container_MenuItems_ChannelLabel')
                .addEnumValue('CM Container Button Assistive Text', 'CM_Container_Button_AssistiveText')
            )
        )
        .addField('iconUrl', new StringXMLField('iconUrl', 'Icon URL')
            .setEditable()
        )
        .addField('isDisplayedOnPageLoad', new BooleanXMLField('isDisplayedOnPageLoad', 'Is Displayed On Page Load')
            .setMinApi(49)
            .setEditable()
        )
        .addField('itemName', new StringXMLField('itemName', 'Item Name')
            .setEditable()
        )
        .addField('osOptionsHideInIOS', new BooleanXMLField('osOptionsHideInIOS', 'OS Options Hide In IOS')
            .setEditable()
        )
        .addField('osOptionsHideInLinuxOS', new BooleanXMLField('osOptionsHideInLinuxOS', 'OS Options Hide In Linux OS')
            .setEditable()
        )
        .addField('osOptionsHideInMacOS', new BooleanXMLField('osOptionsHideInMacOS', 'OS Options Hide In Mac OS')
            .setEditable()
        )
        .addField('osOptionsHideInOtherOS', new BooleanXMLField('osOptionsHideInOtherOS', 'OS Options Hide In Other OS')
            .setEditable()
        )
        .addField('osOptionsHideInWindowsOS', new BooleanXMLField('osOptionsHideInWindowsOS', 'OS Options Hide In Windows OS')
            .setEditable()
        )
        .addField('phoneNumber', new StringXMLField('phoneNumber', 'Phone Number')
            .setEditable()
        )
        .addField('shouldOpenUrlInSameTab', new BooleanXMLField('shouldOpenUrlInSameTab', 'Should Open URL In Same Tab')
            .setEditable()
        ),
    isEnabled: new BooleanXMLField('isEnabled', 'Is Enabled')
        .setMinApi(47)
        .setEditable()
        .setDefaultValue(true),
    masterLabel: new StringXMLField('masterLabel', 'Master Label')
        .setMinApi(47)
        .setEditable()
        .setRequired()
        .setUnique(),
    site: new BooleanXMLField('site', 'Site')
        .setMinApi(47)
        .setEditable()
        .setRequired()
        .setMetadataType(MetadataTypes.CUSTOM_SITE),

}