const { StringXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField, DoubleXMLField, EnumXMLField, BooleanXMLField, DateTimeXMLField, TimeXMLField } = require('@ah/core').Types;
const { MetadataTypes } = require('@ah/core').Values;

function referenceOrValue(valueName, valueLabel) {
    return new ObjectXMLField(valueName, valueLabel)
        .setRequired()
        .addField('booleanValue', new BooleanXMLField('booleanValue', 'Boolean Value')
            .setEditable()
        )
        .addField('dateTimeValue', new DateTimeXMLField('dateTimeValue', 'Date Time Value')
            .setMinApi(30)
            .setEditable()
            .setFormat('yyyy-mm-ddTHH:MM:SS')
        )
        .addField('dateValue', new DateTimeXMLField('dateValue', 'Date Value')
            .setEditable()
            .setFormat('yyyy-mm-dd')
        )
        .addField('elementReference', new StringXMLField('elementReference', 'Element Reference')
            .setEditable()
        )
        .addField('numberValue', new DoubleXMLField('numberValue', 'Number Value')
            .setEditable()
        )
        .addField('stringValue', new StringXMLField('stringValue', 'String Value')
            .setEditable()
        )
}

function processMetadataValues() {
    return new ArrayXMLField('processMetadataValues', 'Process Metadata Values')
        .setMinApi(31)
        .setEditable()
        .setCompress()
        .setFieldKey('name')
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('value', referenceOrValue('value', 'Value'));
}

module.exports = {
    actionCalls: new ArrayXMLField('actionCalls', 'Action Calls')
        .setMinApi(31)
        .setEditable()
        .setFieldKey('actionName')
        .addField('actionName', new StringXMLField('actionName', 'Action Name')
            .setEditable()
            .setRequired()
        )
        .addField('actionType', new EnumXMLField('actionType', 'Action Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Activate Session Permission Set', 'activateSessionPermSet')
            .addEnumValue('Add Message To Chat', 'addMessageToChat', 49)
            .addEnumValue('Add Message To Quip Chat', 'addMessageToQuipChat', 46)
            .addEnumValue('Add Message To Quip Document', 'addMessageToQuipDocument', 46)
            .addEnumValue('Add Quip Document To Folder', 'addQuipDocumentToFolder', 46)
            .addEnumValue('Add Users To Chat', 'addUsersToChat', 49)
            .addEnumValue('Add Users To Quip Document', 'addUsersToQuipDocument', 46)
            .addEnumValue('Add Users To Quip Chat', 'addUsersToQuipChat', 46)
            .addEnumValue('Attach Quip Document To Record', 'attachQuipDocumentToRecord', 46)
            .addEnumValue('Apex', 'apex')
            .addEnumValue('Archive Knowledge Articles', 'archiveKnowledgeArticles', 45)
            .addEnumValue('Assign Knowledge Articles', 'assignKnowledgeArticles', 44)
            .addEnumValue('Cancel Cart Async Operation', 'cancelCartAsyncOperation', 49)
            .addEnumValue('Chat', 'chat', 49)
            .addEnumValue('Chatter Post', 'chatterPost', 49)
            .addEnumValue('Checkout Session Action', 'checkoutSessionAction', 49)
            .addEnumValue('Choose Price book', 'choosePricebook')
            .addEnumValue('Contact Request Action', 'contactRequestAction', 45)
            .addEnumValue('Component', 'component', 43)
            .addEnumValue('Content Workspace Enable Folders', 'contentWorkspaceEnableFolders')
            .addEnumValue('Copy Quip Document', 'copyQuipDocument', 46)
            .addEnumValue('Create Draft From Online Knowledge Article', 'createDraftFromOnlineKnowledgeArticle', 45)
            .addEnumValue('Create Invoice From Fulfillment Order', 'createInvoiceFromFulfillmentOrder', 49)
            .addEnumValue('Create Quip Chat', 'createQuipChat', 46)
            .addEnumValue('Create Quip Document', 'createQuipDocument', 46)
            .addEnumValue('Create Quip Folder', 'createQuipFolder', 46)
            .addEnumValue('Custom Notification Action', 'customNotificationAction', 46)
            .addEnumValue('Deactivate Session Permission Set', 'deactivateSessionPermSet')
            .addEnumValue('Decision Studio Action', 'decisionStudioAction', 49)
            .addEnumValue('Delete Knowledge Article', 'deleteKnowledgeArticle', 46)
            .addEnumValue('Edit Quip Document', 'editQuipDocument', 46)
            .addEnumValue('Email Alert', 'emailAlert')
            .addEnumValue('Email Simple', 'emailSimple')
            .addEnumValue('External Service', 'externalService', 46)
            .addEnumValue('Flow', 'flow', 32)
            .addEnumValue('Marketing Email', 'marketingEmail', 49)
            .addEnumValue('Mass Update Account Forecast', 'massUpdateAccountForecast', 48)
            .addEnumValue('Mass Update Sales Agreement', 'massUpdateSalesAgreement', 48)
            .addEnumValue('Price Cart', 'priceCart', 47)
            .addEnumValue('Quick Action', 'quickAction')
            .addEnumValue('Publish Knowledge Articles', 'publishKnowledgeArticles', 44)
            .addEnumValue('Publish Pardot Content', 'publishPardotContent', 49)
            .addEnumValue('Restore Knowledge Article Version', 'restoreKnowledgeArticleVersion', 45)
            .addEnumValue('Send Alert', 'sendAlert', 49)
            .addEnumValue('Send Survey Invitation', 'sendSurveyInvitation', 49)
            .addEnumValue('Store Reply Recommendations Feedback', 'storeReplyRecommendationsFeedback', 49)
            .addEnumValue('Submit Knowledge Article For Translation', 'submitKnowledgeArticleForTranslation', 46)
            .addEnumValue('Submit', 'submit')
            .addEnumValue('Update Checkout Session State Action', 'updateCheckoutSessionStateAction', 49)
            .addEnumValue('Adjust Order Item Summaries Preview', 'adjustOrderItemSummariesPreview', 49)
            .addEnumValue('Adjust Order Item Summaries Submit', 'adjustOrderItemSummariesSubmit', 49)
            .addEnumValue('Cancel Fulfillment Order Item', 'cancelFulfillmentOrderItem', 48)
            .addEnumValue('Cancel Order Item Summaries Preview', 'cancelOrderItemSummariesPreview', 48)
            .addEnumValue('Cancel Order Item Summaries Submit', 'cancelOrderItemSummariesSubmit', 48)
            .addEnumValue('Create Credit Memo Order Summary', 'createCreditMemoOrderSummary', 48)
            .addEnumValue('Create Fulfillment Order', 'createFulfillmentOrder', 48)
            .addEnumValue('Create Invoice From Fulfillment Order', 'createInvoiceFromFulfillmentOrder', 48)
            .addEnumValue('Create Order Payment Summary', 'createOrderPaymentSummary', 48)
            .addEnumValue('Create Order Summary', 'createOrderSummary', 48)
            .addEnumValue('Ensure Funds Order Summary Async', 'ensureFundsOrderSummaryAsync', 48)
            .addEnumValue('Ensure Refunds Order Summary Async', 'ensureRefundsOrderSummaryAsync', 48)
            .addEnumValue('Return Order Item Summaries Preview', 'returnOrderItemSummariesPreview', 48)
            .addEnumValue('Return Order Item Summaries Submit', 'returnOrderItemSummariesSubmit', 48)
            .addEnumValue('Store Reply Recommendations Feedback', 'storeReplyRecommendationsFeedback', 49)
            .addEnumValue('Store Reply Recommendations Feedback', 'storeReplyRecommendationsFeedback', 49)
            .addEnumValue('Create Financial Records', 'createFinancialRecords', 49)
            .addEnumValue('Add Rebate Member List', 'addRebateMemberList', 51)
            .addEnumValue('Calculate Rebate Amount And Upsert Payout', 'calculateRebateAmountAndUpsertPayout', 51)
            .addEnumValue('Get Benefit And Calculate Rebate Amount', 'getBenefitAndCalculateRebateAmount', 51)
            .addEnumValue('Generate Rebate Payout Periods', 'generateRebatePayoutPeriods', 51)
            .addEnumValue('Process Rebates Batch Calculation Job', 'processRebatesBatchCalculationJob', 51)
            .addEnumValue('Rebates Process CSV', 'rebatesProcessCSV', 51)
            .addEnumValue('Upsert Custom Rebate Payout', 'upsertCustomRebatePayout', 51)
            .addEnumValue('Adjust Points', 'adjustPoints', 51)
            .addEnumValue('Assign Tier Benefits', 'assignTierBenefits', 51)
            .addEnumValue('Cancel Accrual', 'cancelAccrual')
            .addEnumValue('Credit Points', 'creditPoints', 51)
            .addEnumValue('Cancel Redemption', 'cancelRedemption', 51)
            .addEnumValue('Change Tier', 'changeTier', 51)
            .addEnumValue('Change Tier When No Errors', 'changeTierWhenNoErrors', 51)
            .addEnumValue('Debit Points', 'debitPoints', 51)
            .addEnumValue('Execute Member Benefit', 'executeMemberBenefit', 51)
            .addEnumValue('Get Tier', 'getTier', 51)
            .addEnumValue('Get Points Balance', 'getPointsBalance', 51)
            .addEnumValue('Issue Voucher', 'issueVoucher', 51)
            .addEnumValue('Decision Table Action', 'decisionTableAction', 51)
            .addEnumValue('Refresh Decision Table', 'refreshDecisionTable', 51)
            .addEnumValue('Batch Job Action', 'batchJobAction', 51)
            .addEnumValue('Data Processing Engine Action', 'dataProcessingEngineAction', 51)
        )
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('dataTypeMappings', new ArrayXMLField('dataTypeMappings', 'Data Type Mappings')
            .setMinApi(48)
            .setEditable()
            .setFieldKey('typeName')
            .addField('typeName', new StringXMLField('typeName', 'Type Name')
                .setEditable()
                .setRequired()
            )
            .addField('typeValue', new StringXMLField('typeValue', 'Type Value')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
            )
        )
        .addField('faultConnector', new ObjectXMLField('faultConnector', 'Fault Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('inputParameters', new ArrayXMLField('inputParameters', 'Input Parameters')
            .setEditable()
            .setFieldKey('name')
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
            .addField('processMetadataValues', processMetadataValues())
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('locationX', new IntegerXMLField('locationX', 'Location X')
            .setEditable()
        )
        .addField('locationY', new IntegerXMLField('locationY', 'Location Y')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
        )
        .addField('outputParameters', new ArrayXMLField('outputParameters', 'Output Parameters')
            .setEditable()
            .setFieldKey('name')
            .addField('assignToReference', new StringXMLField('assignToReference', 'Assign To Reference')
                .setEditable()
                .setRequired()
            )
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
        )
        .addField('processMetadataValues', processMetadataValues())
        .addField('storeOutputAutomatically', new BooleanXMLField('storeOutputAutomatically', 'Store Output Automatically')
            .setMinApi(48)
            .setEditable()
        ),
    apexPluginCalls: new ArrayXMLField('apexPluginCalls', 'Apex Plugin Calls')
        .setMinApi(24)
        .setEditable()
        .setFieldKey('apexClass')
        .addField('apexClass', new StringXMLField('apexClass', 'Apex Class')
            .setEditable()
            .setMetadataType(MetadataTypes.APEX_CLASS)
        )
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('faultConnector', new ObjectXMLField('faultConnector', 'Fault Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('inputParameters', new ArrayXMLField('inputParameters', 'Input Parameters')
            .setEditable()
            .setFieldKey('name')
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('locationX', new IntegerXMLField('locationX', 'Location X')
            .setEditable()
        )
        .addField('locationY', new IntegerXMLField('locationY', 'Location Y')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
        )
        .addField('outputParameters', new ArrayXMLField('outputParameters', 'Output Parameters')
            .setEditable()
            .setFieldKey('name')
            .addField('assignToReference', new StringXMLField('assignToReference', 'Assign To Reference')
                .setEditable()
                .setRequired()
            )
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
        )
        .addField('processMetadataValues', processMetadataValues()),
    apiVersion: new DoubleXMLField('apiVersion', 'API Version')
        .setMinApi(31)
        .setEditable()
        .setRequired(),
    assignments: new ArrayXMLField('assignments', 'Assignments')
        .setMinApi(24)
        .setEditable()
        .addField('assignmentItems', new ArrayXMLField('assignmentItems', 'Assignment Items')
            .setEditable()
            .addField('assignToReference', new StringXMLField('assignToReference', 'Assign To Reference')
                .setEditable()
                .setRequired()
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Add', 'Add')
                .addEnumValue('Add At Start', 'AddAtStart', 43)
                .addEnumValue('Add Item', 'AddItem', 34)
                .addEnumValue('Assign', 'Assign')
                .addEnumValue('Assign Count', 'AssignCount', 43)
                .addEnumValue('Remove After First', 'RemoveAfterFirst', 43)
                .addEnumValue('Remove All', 'RemoveAll', 43)
                .addEnumValue('Remove Before First', 'RemoveBeforeFirst', 43)
                .addEnumValue('Remove First', 'RemoveFirst', 43)
                .addEnumValue('Remove Position', 'RemovePosition', 43)
                .addEnumValue('Remove Uncommon', 'RemoveUncommon', 43)
                .addEnumValue('Subtract', 'Subtract')
            )
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('locationX', new IntegerXMLField('locationX', 'Location X')
            .setEditable()
        )
        .addField('locationY', new IntegerXMLField('locationY', 'Location Y')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
        )
        .addField('processMetadataValues', processMetadataValues()),
    choices: new ArrayXMLField('choices', 'Choices')
        .setMinApi(24)
        .setEditable()
        .addField('choiceText', new StringXMLField('choiceText', 'Choice Text')
            .setEditable()
            .setRequired()
        )
        .addField('dataType', new EnumXMLField('dataType', 'Data Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Currency', 'Currency')
            .addEnumValue('Date', 'Date')
            .addEnumValue('Number', 'Number')
            .addEnumValue('String', 'String')
            .addEnumValue('Boolean', 'Boolean')
        )
        .addField('userInput', new ObjectXMLField('userInput', 'User Input')
            .setEditable()
            .addField('isRequired', new BooleanXMLField('isRequired', 'Is Required')
                .setEditable()
            )
            .addField('promptText', new StringXMLField('promptText', 'Prompt Text')
                .setEditable()
            )
            .addField('validationRule', new ObjectXMLField('validationRule', 'Validation Rule')
                .setEditable()
                .addField('errorMessage', new StringXMLField('errorMessage', 'Error Message')
                    .setEditable()
                    .setRequired()
                )
                .addField('formulaExpression', new StringXMLField('formulaExpression', 'Formula Expression')
                    .setEditable()
                    .setRequired()
                )
            )
        )
        .addField('value', referenceOrValue('value', 'Value')
        ),
    constants: new ArrayXMLField('constants', 'Constants')
        .setMinApi(24)
        .setEditable()
        .addField('dataType', new EnumXMLField('dataType', 'Data Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Currency', 'Currency')
            .addEnumValue('Date', 'Date')
            .addEnumValue('Number', 'Number')
            .addEnumValue('String', 'String')
            .addEnumValue('Boolean', 'Boolean')
        )
        .addField('value', referenceOrValue('value', 'Value')
        ),
    decisions: new ArrayXMLField('decisions', 'Decisions')
        .setMinApi(24)
        .setEditable()
        .addField('defaultConnector', new ObjectXMLField('defaultConnector', 'Default Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('defaultConnectorLabel', new StringXMLField('defaultConnectorLabel', 'Default Connector Label')
            .setEditable()
            .setRequired()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('locationX', new IntegerXMLField('locationX', 'Location X')
            .setEditable()
        )
        .addField('locationY', new IntegerXMLField('locationY', 'Location Y')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
        )
        .addField('processMetadataValues', processMetadataValues())
        .addField('rules', new ArrayXMLField('rules', 'Rules')
            .setEditable()
            .setFieldKey('name')
            .setSortOrder(undefined)
            .addField('conditionLogic', new EnumXMLField('conditionLogic', 'Condition Logic')
                .setEditable()
                .addEnumValue('AND', 'and')
                .addEnumValue('OR', 'or')
            )
            .addField('conditions', new ArrayXMLField('conditions', 'Conditions')
                .setEditable()
                .addField('leftValueReference', new StringXMLField('leftValueReference', 'Left Value Reference')
                    .setEditable()
                    .setRequired()
                    .setUnique()
                )
                .addField('operator', new EnumXMLField('operator', 'Operator')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Equal To', 'EqualTo')
                    .addEnumValue('Not Equal To', 'NotEqualTo')
                    .addEnumValue('Greater Than', 'GreaterThan')
                    .addEnumValue('Less Than', 'LessThan')
                    .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo')
                    .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo')
                    .addEnumValue('Starts With', 'StartsWith')
                    .addEnumValue('Ends With', 'EndsWith')
                    .addEnumValue('Contains', 'Contains')
                    .addEnumValue('Is Null', 'IsNull')
                    .addEnumValue('Was Set', 'WasSet', 30)
                    .addEnumValue('Was Selected', 'WasSelected')
                    .addEnumValue('Was Visited', 'WasVisited')
                )
                .addField('processMetadataValues', processMetadataValues())
                .addField('rightValue', referenceOrValue('rightValue', 'Right Value'))
            )
            .addField('connector', new ObjectXMLField('connector', 'Connector')
                .setEditable()
                .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('label', new StringXMLField('label', 'Label')
                .setEditable()
                .setRequired()
            )
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
            )
            .addField('processMetadataValues', processMetadataValues())
        ),
    description: new StringXMLField('description', 'Description')
        .setMinApi(24)
        .setEditable(),
    dynamicChoiceSets: new ArrayXMLField('dynamicChoiceSets', 'Dynamic Choice Sets')
        .setMinApi(24)
        .setEditable()
        .addField('dataType', new EnumXMLField('dataType', 'Data Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Currency', 'Currency')
            .addEnumValue('Date', 'Date')
            .addEnumValue('Number', 'Number')
            .addEnumValue('String', 'String')
            .addEnumValue('Boolean', 'Boolean')
            .addEnumValue('Picklist', 'Picklist', 35)
            .addEnumValue('Multi Picklist', 'Multipicklist', 35)
        )
        .addField('displayField', new StringXMLField('displayField', 'Display Field')
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        )
        .addField('filters', new ArrayXMLField('filters', 'Filters')
            .setEditable()
            .setFieldKey('field')
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Equal To', 'EqualTo')
                .addEnumValue('Not Equal To', 'NotEqualTo')
                .addEnumValue('Greater Than', 'GreaterThan')
                .addEnumValue('Less Than', 'LessThan')
                .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo')
                .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo')
                .addEnumValue('Starts With', 'StartsWith')
                .addEnumValue('Ends With', 'EndsWith')
                .addEnumValue('Contains', 'Contains')
                .addEnumValue('Is Null', 'IsNull')
            )
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('limit', new IntegerXMLField('limit', 'Limit')
            .setMinApi(25)
            .setEditable()
            .setDefaultValue(200)
            .setMinValue(0)
            .setMaxValue(200)
        )
        .addField('object', new StringXMLField('object', 'Object')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('outputAssignments', new ArrayXMLField('outputAssignments', 'Output Assignments')
            .setEditable()
            .setFieldKey('field')
            .addField('assignToReference', new StringXMLField('assignToReference', 'Assign To Reference')
                .setEditable()
                .setRequired()
            )
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
            )
        )
        .addField('picklistField', new StringXMLField('picklistField', 'Picklist Field')
            .setMinApi(35)
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        )
        .addField('picklistObject', new StringXMLField('picklistObject', 'Picklist Object')
            .setMinApi(35)
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('sortField', new StringXMLField('sortField', 'Sort Field')
            .setMinApi(25)
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        )
        .addField('sortOrder', new EnumXMLField('sortOrder', 'Sort Order')
            .setMinApi(25)
            .setEditable()
            .addEnumValue('ASC', 'Asc')
            .addEnumValue('DESC', 'Desc')
        )
        .addField('valueField', new StringXMLField('valueField', 'Value Field')
            .setEditable()
        ),
    formulas: new ArrayXMLField('formulas', 'Formulas')
        .setMinApi(24)
        .setEditable()
        .addField('dataType', new EnumXMLField('dataType', 'Data Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Currency', 'Currency')
            .addEnumValue('Date', 'Date')
            .addEnumValue('Date Time', 'DateTime')
            .addEnumValue('Number', 'Number')
            .addEnumValue('String', 'String')
            .addEnumValue('Boolean', 'Boolean')
        )
        .addField('expression', new StringXMLField('expression', 'Expression')
            .setEditable()
        )
        .addField('processMetadataValues', processMetadataValues())
        .addField('scale', new IntegerXMLField('scale', 'Scale')
            .setEditable()
        ),
    fullName: new StringXMLField('fullName', 'Full Name')
        .setMinApi(24)
        .setEditable()
        .setRequired()
        .setUnique(),
    interviewLabel: new StringXMLField('interviewLabel', 'Interview Label')
        .setMinApi(24)
        .setEditable(),
    isAdditionalPermissionRequiredToRun: new BooleanXMLField('isAdditionalPermissionRequiredToRun', 'Is Additional Permission Required To Run')
        .setMinApi(47)
        .setEditable()
        .setDefaultValue(false),
    isTemplate: new BooleanXMLField('isTemplate', 'Is Template')
        .setMinApi(45)
        .setEditable()
        .setDefaultValue(false),
    label: new StringXMLField('label', 'Label')
        .setMinApi(24)
        .setEditable(),
    loops: new ArrayXMLField('loops', 'Loops')
        .setMinApi(30)
        .setEditable()
        .addField('nextValueConnector', new ObjectXMLField('nextValueConnector', 'Next Value Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('noMoreValuesConnector', new ObjectXMLField('noMoreValuesConnector', 'No More Values Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('collectionReference', new StringXMLField('collectionReference', 'Collection Reference')
            .setEditable()
            .setRequired()
        )
        .addField('assignNextValueToReference', new StringXMLField('assignNextValueToReference', 'Assign Next Value To Reference')
            .setEditable()
            .setRequired()
        )
        .addField('iterationOrder', new EnumXMLField('iterationOrder', 'Iteration Order')
            .setEditable()
            .addEnumValue('ASC', 'Asc')
            .addEnumValue('DESC', 'Desc')
        ),
    processMetadataValues: processMetadataValues(),
    processType: new EnumXMLField('processType', 'Process Type')
        .setMinApi(31)
        .setEditable()
        .setRequired()
        .addEnumValue('Appointments', 'Appointments', 44)
        .addEnumValue('Auto Launched Flow', 'AutoLaunchedFlow')
        .addEnumValue('Checkout Flow', 'CheckoutFlow', 48)
        .addEnumValue('Contact Request Flow', 'ContactRequestFlow', 45)
        .addEnumValue('Customer Lifecycle', 'CustomerLifecycle', 49)
        .addEnumValue('Custom Event', 'CustomEvent', 41)
        .addEnumValue('Field Service Mobile', 'FieldServiceMobile', 39)
        .addEnumValue('Field Service Web', 'FieldServiceWeb', 41)
        .addEnumValue('Flow', 'Flow')
        .addEnumValue('Financial Service Cloud Mortgage Lending', 'FSCLending', 46)
        .addEnumValue('Invocable Process', 'InvocableProcess', 38)
        .addEnumValue('Survey', 'Survey', 42)
        .addEnumValue('Survey Enrich', 'SurveyEnrich', 49)
        .addEnumValue('Workflow', 'Workflow'),
    recordCreates: new ArrayXMLField('recordCreates', 'Record Creates')
        .setMinApi(24)
        .setEditable()
        .addField('assignRecordIdToReference', new StringXMLField('assignRecordIdToReference', 'Assign Record Id To Reference')
            .setEditable()
        )
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('faultConnector', new ObjectXMLField('faultConnector', 'Fault Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('filters', new ArrayXMLField('filters', 'Filters')
            .setEditable()
            .setFieldKey('field')
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Equal To', 'EqualTo')
                .addEnumValue('Not Equal To', 'NotEqualTo')
                .addEnumValue('Greater Than', 'GreaterThan')
                .addEnumValue('Less Than', 'LessThan')
                .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo')
                .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo')
                .addEnumValue('Starts With', 'StartsWith')
                .addEnumValue('Ends With', 'EndsWith')
                .addEnumValue('Contains', 'Contains')
                .addEnumValue('Is Null', 'IsNull')
            )
            .addField('processMetadataValues', processMetadataValues())
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('inputAssignments', new ArrayXMLField('inputAssignments', 'Input Assignments')
            .setEditable()
            .setFieldKey('field')
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
            )
            .addField('processMetadataValues', processMetadataValues())
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('inputReference', new StringXMLField('inputReference', 'Input Reference')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('locationX', new IntegerXMLField('locationX', 'Location X')
            .setEditable()
        )
        .addField('locationY', new IntegerXMLField('locationY', 'Location Y')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
        )
        .addField('object', new StringXMLField('object', 'Object')
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('processMetadataValues', processMetadataValues())
        .addField('storeOutputAutomatically', new BooleanXMLField('storeOutputAutomatically', 'Store Output Automatically')
            .setMinApi(48)
            .setEditable()
        ),
    recordDeletes: new ArrayXMLField('recordDeletes', 'Record Deletes')
        .setMinApi(24)
        .setEditable()
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('faultConnector', new ObjectXMLField('faultConnector', 'Fault Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('filters', new ArrayXMLField('filters', 'Filters')
            .setEditable()
            .setFieldKey('field')
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Equal To', 'EqualTo')
                .addEnumValue('Not Equal To', 'NotEqualTo')
                .addEnumValue('Greater Than', 'GreaterThan')
                .addEnumValue('Less Than', 'LessThan')
                .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo')
                .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo')
                .addEnumValue('Starts With', 'StartsWith')
                .addEnumValue('Ends With', 'EndsWith')
                .addEnumValue('Contains', 'Contains')
                .addEnumValue('Is Null', 'IsNull')
            )
            .addField('processMetadataValues', processMetadataValues())
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('inputReference', new StringXMLField('inputReference', 'Input Reference')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('locationX', new IntegerXMLField('locationX', 'Location X')
            .setEditable()
        )
        .addField('locationY', new IntegerXMLField('locationY', 'Location Y')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
        )
        .addField('object', new StringXMLField('object', 'Object')
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('processMetadataValues', processMetadataValues()),
    recordLookups: new ArrayXMLField('recordLookups', 'Record Lookups')
        .setMinApi(24)
        .setEditable()
        .addField('assignNullValuesIfNoRecordFound', new BooleanXMLField('assignNullValuesIfNoRecordFound', 'Assign Null Values If No Record Found')
            .setMinApi(30)
            .setEditable()
        )
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('faultConnector', new ObjectXMLField('faultConnector', 'Fault Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('filters', new ArrayXMLField('filters', 'Filters')
            .setEditable()
            .setFieldKey('field')
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Equal To', 'EqualTo')
                .addEnumValue('Not Equal To', 'NotEqualTo')
                .addEnumValue('Greater Than', 'GreaterThan')
                .addEnumValue('Less Than', 'LessThan')
                .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo')
                .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo')
                .addEnumValue('Starts With', 'StartsWith')
                .addEnumValue('Ends With', 'EndsWith')
                .addEnumValue('Contains', 'Contains')
                .addEnumValue('Is Null', 'IsNull')
            )
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('getFirstRecordOnly', new BooleanXMLField('getFirstRecordOnly', 'Get First Record Only')
            .setMinApi(47)
            .setEditable()
        )
        .addField('limit', new IntegerXMLField('limit', 'Limit')
            .setMinApi(30)
            .setEditable()
        )
        .addField('object', new StringXMLField('object', 'Object')
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('outputAssignments', new ArrayXMLField('outputAssignments', 'Output Assignments')
            .setEditable()
            .setFieldKey('field')
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
            )
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('outputReference', new StringXMLField('outputReference', 'Output Reference')
            .setEditable()
        )
        .addField('queriedFields', new ArrayXMLField('queriedFields', 'Queried Fields')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        )
        .addField('sortField', new StringXMLField('sortField', 'Sort Field')
            .setMinApi(25)
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        )
        .addField('sortOrder', new EnumXMLField('sortOrder', 'Sort Order')
            .setMinApi(25)
            .setEditable()
            .addEnumValue('ASC', 'Asc')
            .addEnumValue('DESC', 'Desc')
        )
        .addField('storeOutputAutomatically', new BooleanXMLField('storeOutputAutomatically', 'Store Output Automatically')
            .setMinApi(47)
            .setEditable()
        ),
    recordUpdates: new ArrayXMLField('recordUpdates', 'Record Updates')
        .setMinApi(24)
        .setEditable()
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('faultConnector', new ObjectXMLField('faultConnector', 'Fault Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('filters', new ArrayXMLField('filters', 'Filters')
            .setEditable()
            .setFieldKey('field')
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Equal To', 'EqualTo')
                .addEnumValue('Not Equal To', 'NotEqualTo')
                .addEnumValue('Greater Than', 'GreaterThan')
                .addEnumValue('Less Than', 'LessThan')
                .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo')
                .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo')
                .addEnumValue('Starts With', 'StartsWith')
                .addEnumValue('Ends With', 'EndsWith')
                .addEnumValue('Contains', 'Contains')
                .addEnumValue('Is Null', 'IsNull')
            )
            .addField('processMetadataValues', processMetadataValues())
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('inputAssignments', new ArrayXMLField('inputAssignments', 'Input Assignments')
            .setEditable()
            .setFieldKey('field')
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
            )
            .addField('processMetadataValues', processMetadataValues())
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('inputReference', new StringXMLField('inputReference', 'Input Reference')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('locationX', new IntegerXMLField('locationX', 'Location X')
            .setEditable()
        )
        .addField('locationY', new IntegerXMLField('locationY', 'Location Y')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
        )
        .addField('object', new StringXMLField('object', 'Object')
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('processMetadataValues', processMetadataValues()),
    runInMode: new EnumXMLField('runInMode', 'Run In Mode')
        .setMinApi(48)
        .setEditable()
        .addEnumValue('Default Mode', 'DefaultMode')
        .addEnumValue('System Mode With Sharing', 'SystemModeWithSharing'),
    screens: new ArrayXMLField('screens', 'Screens')
        .setMinApi(24)
        .setEditable()
        .addField('allowBack', new BooleanXMLField('allowBack', 'Allow Back')
            .setMinApi(26)
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('allowFinish', new BooleanXMLField('allowFinish', 'Allow Finish')
            .setMinApi(26)
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('allowPause', new BooleanXMLField('allowPause', 'Allow Pause')
            .setMinApi(26)
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('fields', new ArrayXMLField('fields', 'Fields')
            .setEditable()
            .addField('choiceReferences', new ArrayXMLField('choiceReferences', 'Choice References')
                .setMinApi(26)
                .setEditable()
            )
            .addField('dataType', new EnumXMLField('dataType', 'Data Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Currency', 'Currency')
                .addEnumValue('Date', 'Date')
                .addEnumValue('Date Time', 'DateTime', 43)
                .addEnumValue('Number', 'Number')
                .addEnumValue('String', 'String')
                .addEnumValue('Boolean', 'Boolean', 26)
            )
            .addField('dataTypeMappings', new ArrayXMLField('dataTypeMappings', 'Data Type Mappings')
                .setEditable()
                .setFieldKey('typeName')
                .addField('typeName', new StringXMLField('typeName', 'Type Name')
                    .setEditable()
                    .setRequired()
                )
                .addField('typeValue', new StringXMLField('typeValue', 'Type Value')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('defaultSelectedChoiceReference', new ArrayXMLField('defaultSelectedChoiceReference', 'Default Selected Choice Reference')
                .setMinApi(26)
                .setEditable()
            )
            .addField('defaultValue', referenceOrValue('defaultValue', 'Default Value'))
            .addField('extensionName', new StringXMLField('extensionName', 'Extension Name')
                .setMinApi(42)
                .setEditable()
            )
            .addField('fieldText', new StringXMLField('fieldText', 'Field Text')
                .setEditable()
            )
            .addField('fieldType', new EnumXMLField('fieldType', 'Field Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Display Text', 'DisplayText')
                .addEnumValue('Input Field', 'InputField')
                .addEnumValue('Large Text Area', 'LargeTextArea')
                .addEnumValue('Password Field', 'PasswordField')
                .addEnumValue('Radio Buttons', 'RadioButtons')
                .addEnumValue('Dropdown Box', 'DropdownBox')
                .addEnumValue('Multi Select Checkboxes', 'MultiSelectCheckboxes', 26)
                .addEnumValue('Multi Select Picklist', 'MultiSelectPicklist', 26)
                .addEnumValue('Component Instance', 'ComponentInstance', 42)
                .addEnumValue('Component Choice', 'ComponentChoice', 48)
                .addEnumValue('Component Input', 'ComponentInput', 48)
            )
            .addField('helpText', new StringXMLField('helpText', 'Help Text')
                .setMinApi(26)
                .setEditable()
            )
            .addField('inputParameters', new ArrayXMLField('inputParameters', 'Input Parameters')
                .setMinApi(42)
                .setEditable()
                .setFieldKey('name')
                .addField('name', new StringXMLField('name', 'Name')
                    .setEditable()
                    .setRequired()
                )
                .addField('value', new StringXMLField('value', 'Value')
                    .setEditable()
                )
            )
            .addField('isRequired', new BooleanXMLField('isRequired', 'Is Required')
                .setEditable()
            )
            .addField('isVisible', new BooleanXMLField('isVisible', 'Is Visible')
                .setEditable()
            )
            .addField('outputParameters', new ArrayXMLField('outputParameters', 'Output Parameters')
                .setMinApi(42)
                .setEditable()
                .setFieldKey('name')
                .addField('assignToReference', new StringXMLField('assignToReference', 'Assign To Reference')
                    .setEditable()
                    .setRequired()
                )
                .addField('name', new StringXMLField('name', 'Name')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('scale', new IntegerXMLField('scale', 'Scale')
                .setEditable()
            )
            .addField('storeOutputAutomatically', new BooleanXMLField('storeOutputAutomatically', 'Store Output Automatically')
                .setMinApi(47)
                .setEditable()
            )
            .addField('validationRule', new ObjectXMLField('validationRule', 'Validation Rule')
                .setEditable()
                .addField('errorMessage', new StringXMLField('errorMessage', 'Error Message')
                    .setEditable()
                    .setRequired()
                )
                .addField('formulaExpression', new StringXMLField('formulaExpression', 'Formula Expression')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('visibilityRule', new ObjectXMLField('visibilityRule', 'Visibility Rule')
                .setMinApi(47)
                .setEditable()
                .addField('conditionLogic', new EnumXMLField('conditionLogic', 'Condition Logic')
                    .setEditable()
                    .addEnumValue('AND', 'and')
                    .addEnumValue('OR', 'or')
                )
                .addField('conditions', new ArrayXMLField('conditions', 'Conditions')
                    .setEditable()
                    .addField('leftValueReference', new StringXMLField('leftValueReference', 'Left Value Reference')
                        .setEditable()
                        .setRequired()
                        .setUnique()
                    )
                    .addField('operator', new EnumXMLField('operator', 'Operator')
                        .setEditable()
                        .setRequired()
                        .addEnumValue('Equal To', 'EqualTo')
                        .addEnumValue('Not Equal To', 'NotEqualTo')
                        .addEnumValue('Greater Than', 'GreaterThan')
                        .addEnumValue('Less Than', 'LessThan')
                        .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo')
                        .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo')
                        .addEnumValue('Starts With', 'StartsWith')
                        .addEnumValue('Ends With', 'EndsWith')
                        .addEnumValue('Contains', 'Contains')
                        .addEnumValue('Is Null', 'IsNull')
                        .addEnumValue('Was Set', 'WasSet', 30)
                        .addEnumValue('Was Selected', 'WasSelected')
                        .addEnumValue('Was Visited', 'WasVisited')
                    )
                    .addField('rightValue', referenceOrValue('rightValue', 'Right Value'))
                )
            )
        )
        .addField('helpText', new StringXMLField('helpText', 'Help Text')
            .setMinApi(26)
            .setEditable()
        )
        .addField('pausedText', new StringXMLField('pausedText', 'Paused Text')
            .setMinApi(33)
            .setEditable()
        )
        .addField('showFooter', new BooleanXMLField('showFooter', 'Show Footer')
            .setMinApi(42)
            .setEditable()
        )
        .addField('showHeader', new BooleanXMLField('showHeader', 'Show Header')
            .setMinApi(42)
            .setEditable()
        ),
    stages: new ArrayXMLField('stages', 'Stages')
        .setMinApi(42)
        .setEditable()
        .setFieldKey('label')
        .addField('isActive', new BooleanXMLField('isActive', 'Is Active')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('stageOrder', new IntegerXMLField('stageOrder', 'Stage Order')
            .setEditable()
            .setUnique()
        ),
    start: new ObjectXMLField('start', 'Start')
        .setMinApi(47)
        .setEditable()
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('filters', new ArrayXMLField('filters', 'Filters')
            .setEditable()
            .setFieldKey('field')
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Equal To', 'EqualTo')
                .addEnumValue('Not Equal To', 'NotEqualTo')
                .addEnumValue('Greater Than', 'GreaterThan')
                .addEnumValue('Less Than', 'LessThan')
                .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo')
                .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo')
                .addEnumValue('Starts With', 'StartsWith')
                .addEnumValue('Ends With', 'EndsWith')
                .addEnumValue('Contains', 'Contains')
                .addEnumValue('Is Null', 'IsNull')
            )
            .addField('value', referenceOrValue('value', 'Value'))
            .addField('object', new StringXMLField('object', 'Object')
                .setEditable()
                .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
            )
            .addField('recordTriggerType', new EnumXMLField('recordTriggerType', 'Record Trigger Type')
                .setMinApi(48)
                .setEditable()
                .addEnumValue('Create', 'Create')
                .addEnumValue('Update', 'Update')
                .addEnumValue('Create And Update', 'CreateAndUpdate')
            )
            .addField('schedule', new ObjectXMLField('schedule', 'Schedule')
                .setEditable()
                .addField('frequency', new EnumXMLField('frequency', 'Frequency')
                    .setEditable()
                    .addEnumValue('Once', 'Once')
                    .addEnumValue('Daily', 'Daily')
                    .addEnumValue('Weekly', 'Weekly')
                )
                .addField('startDate', new DateTimeXMLField('startDate', 'Start Date')
                    .setEditable()
                    .setFormat('yyyy-mm-dd')
                )
                .addField('startTime', new TimeXMLField('startTime', 'Start Time')
                    .setEditable()
                )
            )
            .addField('triggerType', new EnumXMLField('triggerType', 'Trigger Type')
                .setMinApi(47)
                .setEditable()
                .addEnumValue('Platform Event', 'PlatformEvent', 49)
                .addEnumValue('Record After Save', 'RecordAfterSave', 49)
                .addEnumValue('Record Before Save', 'RecordBeforeSave', 48)
                .addEnumValue('Scheduled', 'Scheduled')
            )
        ),
    startElementReference: new StringXMLField('startElementReference', 'Start Element Reference')
        .setMinApi(24)
        .setEditable(),
    status: new EnumXMLField('status', 'Status')
        .setMinApi(24)
        .setEditable()
        .addEnumValue('Active', 'Active')
        .addEnumValue('Draft', 'Draft')
        .addEnumValue('Obsolete', 'Obsolete')
        .addEnumValue('InvalidDraft', 'InvalidDraft'),
    steps: new ArrayXMLField('steps', 'Steps')
        .setMinApi(24)
        .setEditable()
        .addField('connectors', new ArrayXMLField('connectors', 'Connectors')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        ),
    subflows: new ArrayXMLField('subflows', 'Subflows')
        .setMinApi(25)
        .setEditable()
        .setFieldKey('flowName')
        .addField('connector', new ObjectXMLField('connector', 'Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('flowName', new StringXMLField('flowName', 'Flow Name')
            .setEditable()
            .setRequired()
        )
        .addField('inputAssignments', new ArrayXMLField('inputAssignments', 'Input Assignments')
            .setEditable()
            .setFieldKey('name')
            .addField('name', new StringXMLField('name', 'name')
                .setEditable()
                .setRequired()
            )
            .addField('value', referenceOrValue('value', 'Value'))
        )
        .addField('outputAssignments', new ArrayXMLField('outputAssignments', 'Output Assignments')
            .setEditable()
            .setFieldKey('name')
            .addField('assignToReference', new StringXMLField('assignToReference', 'Assign To Reference')
                .setEditable()
                .setRequired()
            )
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
        ),
    textTemplates: new ArrayXMLField('textTemplates', 'Text Templates')
        .setMinApi(24)
        .setEditable()
        .addField('isViewedAsPlainText', new BooleanXMLField('isViewedAsPlainText', 'Is Viewed As Plain Text')
            .setEditable()
            .setDefaultValue(false)
        )
        .addField('text', new StringXMLField('text', 'Text')
            .setEditable()
        ),
    variables: new ArrayXMLField('variables', 'Variables')
        .setMinApi(24)
        .setEditable()
        .addField('apexClass', new StringXMLField('apexClass', 'Apex Class')
            .setMinApi(46)
            .setEditable()
        )
        .addField('dataType', new EnumXMLField('dataType', 'Data Type')
            .setMinApi(24)
            .setRequired()
            .addEnumValue('Apex', 'Apex', 46)
            .addEnumValue('Boolean', 'Boolean')
            .addEnumValue('Currency', 'Currency')
            .addEnumValue('Date', 'Date')
            .addEnumValue('DateTime', 'DateTime', 30)
            .addEnumValue('Number', 'Number')
            .addEnumValue('Multi Picklist', 'Multipicklist', 34)
            .addEnumValue('Picklist', 'Picklist', 34)
            .addEnumValue('String', 'String')
            .addEnumValue('sObject', 'sObject')
        )
        .addField('isCollection', new BooleanXMLField('isCollection', 'Is Collection')
            .setMinApi(30)
            .setEditable()
            .setDefaultValue(false)
        )
        .addField('isInput', new BooleanXMLField('isInput', 'Is Input')
            .setMinApi(25)
            .setEditable()
            .setDefaultValue(false)
        )
        .addField('isOutput', new BooleanXMLField('isOutput', 'Is Output')
            .setMinApi(25)
            .setEditable()
            .setDefaultValue(false)
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('objectType', new StringXMLField('objectType', 'Object Type')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('scale', new IntegerXMLField('scale', 'Scale')
            .setEditable()
        )
        .addField('value', referenceOrValue('value', 'Value')),
    waits: new ArrayXMLField('waits', 'Waits')
        .setMinApi(32)
        .setEditable()
        .setFieldKey('defaultConnectorLabel')
        .addField('defaultConnector', new ObjectXMLField('defaultConnector', 'Default Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('defaultConnectorLabel', new StringXMLField('defaultConnectorLabel', 'Default Connector Label')
            .setEditable()
        )
        .addField('faultConnector', new ObjectXMLField('faultConnector', 'Fault Connector')
            .setEditable()
            .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                .setEditable()
                .setRequired()
            )
        )
        .addField('waitEvents', new ArrayXMLField('waitEvents', 'Wait Events')
            .setEditable()
            .addField('conditionLogic', new EnumXMLField('conditionLogic', 'Condition Logic')
                .setEditable()
                .addEnumValue('AND', 'and')
                .addEnumValue('OR', 'or')
            )
            .addField('conditions', new ArrayXMLField('conditions', 'Conditions')
                .setEditable()
                .addField('leftValueReference', new StringXMLField('leftValueReference', 'Left Value Reference')
                    .setEditable()
                    .setRequired()
                    .setUnique()
                )
                .addField('operator', new EnumXMLField('operator', 'Operator')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Equal To', 'EqualTo')
                    .addEnumValue('Not Equal To', 'NotEqualTo')
                    .addEnumValue('Greater Than', 'GreaterThan')
                    .addEnumValue('Less Than', 'LessThan')
                    .addEnumValue('Greater Than Or Equal To', 'GreaterThanOrEqualTo')
                    .addEnumValue('Less Than Or Equal To', 'LessThanOrEqualTo')
                    .addEnumValue('Starts With', 'StartsWith')
                    .addEnumValue('Ends With', 'EndsWith')
                    .addEnumValue('Contains', 'Contains')
                    .addEnumValue('Is Null', 'IsNull')
                    .addEnumValue('Was Set', 'WasSet', 30)
                    .addEnumValue('Was Selected', 'WasSelected')
                    .addEnumValue('Was Visited', 'WasVisited')
                )
                .addField('rightValue', referenceOrValue('rightValue', 'Right Value'))
            )
            .addField('connector', new ObjectXMLField('connector', 'Connector')
                .setEditable()
                .addField('targetReference', new StringXMLField('targetReference', 'Target Reference')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('eventType', new EnumXMLField('eventType', 'Event Type')
                .setRequired()
                .setEditable()
                .addEnumValue('Alarm Event', 'AlarmEvent')
                .addEnumValue('Date Ref Alarm Event', 'DateRefAlarmEvent')
            )
            .addField('inputAssignments', new ArrayXMLField('inputAssignments', 'Input Assignments')
                .setEditable()
                .setFieldKey('name')
                .addField('name', new StringXMLField('name', 'name')
                    .setEditable()
                    .setRequired()
                )
                .addField('value', referenceOrValue('value', 'Value'))
            )
            .addField('label', new StringXMLField('label', 'Label')
                .setEditable()
                .setRequired()
            )
            .addField('outputAssignments', new ArrayXMLField('outputAssignments', 'Output Assignments')
                .setEditable()
                .setFieldKey('name')
                .addField('assignToReference', new StringXMLField('assignToReference', 'Assign To Reference')
                    .setEditable()
                    .setRequired()
                )
                .addField('name', new StringXMLField('name', 'Name')
                    .setEditable()
                    .setRequired()
                )
            )
        )
}