const { StringXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField, BooleanXMLField, XMLDependencyField } = require('@ah/core').Types;
const { MetadataTypes, DataValues } = require('@ah/core').Values;

module.exports = {
    customButtons: new ArrayXMLField('customButtons', 'Custom Buttons')
        .setMinApi(12)
        .setEditable()
        .setMetadataType(MetadataTypes.WEBLINK),
    customConsoleComponents: new ObjectXMLField('customConsoleComponents', 'Custom Console Components')
        .setMinApi(25)
        .setEditable()
        .setFieldKey('primaryTabComponents')
        .setSortOrder(undefined)
        .addField('primaryTabComponents', new ObjectXMLField('primaryTabComponents', 'Primary Tab Components')
            .setEditable()
            .setFieldKey('component')
            .setSortOrder(undefined)
            .addField('component', new ArrayXMLField('component', 'Component')
                .setMinApi(29)
                .setEditable()
                .setFieldKey('visualforcePage')
                .setSortOrder(undefined)
                .addField('height', new IntegerXMLField('height', 'Height')
                    .setEditable()
                    .setRequired()
                    .setMinValue(1)
                    .setMaxValue(999)
                )
                .addField('location', new EnumXMLField('location', 'Location')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Right', 'right')
                    .addEnumValue('Left', 'left')
                    .addEnumValue('Top', 'top')
                    .addEnumValue('Bottom', 'bottom')
                )
                .addField('visualforcePage', new StringXMLField('visualforcePage', 'Visualforce Page')
                    .setEditable()
                    .setRequired()
                    .setMetadataType(MetadataTypes.APEX_PAGE)
                )
                .addField('width', new IntegerXMLField('width', 'Width')
                    .setEditable()
                    .setRequired()
                    .setMinValue(1)
                    .setMaxValue(999)
                )
            )
            .addField('containers', new ArrayXMLField('containers', 'Containers')
                .setMinApi(30)
                .setEditable()
                .setFieldKey('region')
                .setSortOrder(undefined)
                .addField('height', new IntegerXMLField('height', 'Height')
                    .setEditable()
                    .setRequired()
                )
                .addField('isContainerAutoSizeEnabled', new BooleanXMLField('isContainerAutoSizeEnabled', 'Is Container Auto Size Enabled')
                    .setMinApi(32)
                    .setEditable()
                    .setRequired()
                )
                .addField('region', new EnumXMLField('region', 'Region')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Right', 'right')
                    .addEnumValue('Left', 'left')
                    .addEnumValue('Top', 'top')
                    .addEnumValue('Bottom', 'bottom')
                )
                .addField('sidebarComponents', new ArrayXMLField('sidebarComponents', 'Sidebar Components')
                    .setEditable()
                    .setFieldKey('label')
                    .setSortOrder(undefined)
                    .addField('componentType', new EnumXMLField('componentType', 'Component Type')
                        .setMinApi(31)
                        .setEditable()
                        .addEnumValue('Knowledge One', 'KnowledgeOne')
                        .addEnumValue('Lookup', 'Lookup')
                        .addEnumValue('Milestones', 'Milestones')
                        .addEnumValue('Related List', 'RelatedList')
                        .addEnumValue('Topics', 'Topics')
                        .addEnumValue('Files', 'Files', 32)
                        .addEnumValue('CaseExperts', 'CaseExperts', 32)
                        .addEnumValue('Bottom', 'bottom')
                    )
                    .addField('createAction', new StringXMLField('createAction', 'Create Action')
                        .setMinApi(42)
                        .setEditable()
                    )
                    .addField('enableLinking', new BooleanXMLField('enableLinking', 'Enable Linking')
                        .setMinApi(42)
                        .setEditable()
                    )
                    .addField('height', new IntegerXMLField('height', 'Height')
                        .setEditable()
                        .setRequired()
                    )
                    .addField('label', new StringXMLField('label', 'Label')
                        .setEditable()
                    )
                    .addField('lookup', new StringXMLField('lookup', 'Lookup')
                        .setEditable()
                        .setMetadataType(MetadataTypes.CUSTOM_FIELD)
                    )
                    .addField('page', new StringXMLField('page', 'Page')
                        .setEditable()
                        .setMetadataType(MetadataTypes.APEX_PAGE)
                    )
                    .addField('relatedlists', new ArrayXMLField('relatedlists', 'Related lists')
                        .setMinApi(31)
                        .setEditable()
                        .setFieldKey('name')
                        .setSortOrder(undefined)
                        .addField('hideOnDetail', new BooleanXMLField('hideOnDetail', 'Hide On Detail')
                            .setEditable()
                        )
                        .addField('name', new StringXMLField('name', 'Name')
                            .setEditable()
                        )
                    )
                    .addField('unit', new StringXMLField('unit', 'Unit')
                        .setEditable()
                        .setRequired()
                    )
                    .addField('updateAction', new BooleanXMLField('updateAction', 'Update Action')
                        .setMinApi(42)
                        .setEditable()
                    )
                    .addField('width', new IntegerXMLField('width', 'Width')
                        .setEditable()
                    )
                )
                .addField('style', new EnumXMLField('style', 'Style')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Stack', 'stack')
                    .addEnumValue('Tabs', 'tabs')
                    .addEnumValue('Accordian', 'accordian')
                )
                .addField('unit', new StringXMLField('unit', 'Unit')
                    .setEditable()
                    .setRequired()
                )
                .addField('width', new IntegerXMLField('width', 'Width')
                    .setEditable()
                    .setRequired()
                )
            )
        )
        .addField('subtabComponents', new ObjectXMLField('subtabComponents', 'Subtab Components')
            .setMinApi(29)
            .setFieldKey('component')
            .setSortOrder(undefined)
            .addField('component', new ArrayXMLField('component', 'Component')
                .setMinApi(29)
                .setEditable()
                .setFieldKey('visualforcePage')
            .setSortOrder(undefined)
                .addField('height', new IntegerXMLField('height', 'Height')
                    .setEditable()
                    .setRequired()
                    .setMinValue(1)
                    .setMaxValue(999)
                )
                .addField('location', new EnumXMLField('location', 'Location')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Right', 'right')
                    .addEnumValue('Left', 'left')
                    .addEnumValue('Top', 'top')
                    .addEnumValue('Bottom', 'bottom')
                )
                .addField('visualforcePage', new StringXMLField('visualforcePage', 'Visualforce Page')
                    .setEditable()
                    .setRequired()
                    .setMetadataType(MetadataTypes.APEX_PAGE)
                )
                .addField('width', new IntegerXMLField('width', 'Width')
                    .setEditable()
                    .setRequired()
                    .setMinValue(1)
                    .setMaxValue(999)
                )
            )
            .addField('containers', new ArrayXMLField('containers', 'Containers')
                .setMinApi(30)
                .setEditable()
                .setFieldKey('region')
                .setSortOrder(undefined)
                .addField('height', new IntegerXMLField('height', 'Height')
                    .setEditable()
                    .setRequired()
                )
                .addField('isContainerAutoSizeEnabled', new BooleanXMLField('isContainerAutoSizeEnabled', 'Is Container Auto Size Enabled')
                    .setMinApi(32)
                    .setEditable()
                    .setRequired()
                )
                .addField('region', new EnumXMLField('region', 'Region')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Right', 'right')
                    .addEnumValue('Left', 'left')
                    .addEnumValue('Top', 'top')
                    .addEnumValue('Bottom', 'bottom')
                )
                .addField('sidebarComponents', new ArrayXMLField('sidebarComponents', 'Sidebar Components')
                    .setEditable()
                    .setFieldKey('label')
                    .setSortOrder(undefined)
                    .addField('componentType', new EnumXMLField('componentType', 'Component Type')
                        .setMinApi(31)
                        .setEditable()
                        .addEnumValue('Knowledge One', 'KnowledgeOne')
                        .addEnumValue('Lookup', 'Lookup')
                        .addEnumValue('Milestones', 'Milestones')
                        .addEnumValue('Related List', 'RelatedList')
                        .addEnumValue('Topics', 'Topics')
                        .addEnumValue('Files', 'Files', 32)
                        .addEnumValue('CaseExperts', 'CaseExperts', 32)
                        .addEnumValue('Bottom', 'bottom')
                    )
                    .addField('createAction', new StringXMLField('createAction', 'Create Action')
                        .setMinApi(42)
                        .setEditable()
                    )
                    .addField('enableLinking', new BooleanXMLField('enableLinking', 'Enable Linking')
                        .setMinApi(42)
                        .setEditable()
                    )
                    .addField('height', new IntegerXMLField('height', 'Height')
                        .setEditable()
                        .setRequired()
                    )
                    .addField('label', new StringXMLField('label', 'Label')
                        .setEditable()
                    )
                    .addField('lookup', new StringXMLField('lookup', 'Lookup')
                        .setEditable()
                        .setMetadataType(MetadataTypes.CUSTOM_FIELD)
                    )
                    .addField('page', new StringXMLField('page', 'Page')
                        .setEditable()
                        .setMetadataType(MetadataTypes.APEX_PAGE)
                    )
                    .addField('relatedlists', new ArrayXMLField('relatedlists', 'Related lists')
                        .setMinApi(31)
                        .setEditable()
                        .setFieldKey('name')
                        .setSortOrder(undefined)
                        .addField('hideOnDetail', new BooleanXMLField('hideOnDetail', 'Hide On Detail')
                            .setEditable()
                        )
                        .addField('name', new StringXMLField('name', 'Name')
                            .setEditable()
                        )
                    )
                    .addField('unit', new StringXMLField('unit', 'Unit')
                        .setEditable()
                        .setRequired()
                    )
                    .addField('updateAction', new BooleanXMLField('updateAction', 'Update Action')
                        .setMinApi(42)
                        .setEditable()
                    )
                    .addField('width', new IntegerXMLField('width', 'Width')
                        .setEditable()
                    )
                )
                .addField('style', new EnumXMLField('style', 'Style')
                    .setEditable()
                    .setRequired()
                    .addEnumValue('Stack', 'stack')
                    .addEnumValue('Tabs', 'tabs')
                    .addEnumValue('Accordian', 'accordian')
                )
                .addField('unit', new StringXMLField('unit', 'Unit')
                    .setEditable()
                    .setRequired()
                )
                .addField('width', new IntegerXMLField('width', 'Width')
                    .setEditable()
                    .setRequired()
                )
            )
        ),
    emailDefault: new BooleanXMLField('emailDefault', 'Email Default')
        .setMinApi(13)
        .setEditable(),
    excludeButtons: new ArrayXMLField('excludeButtons', 'Exclude Buttons')
        .setMinApi(13)
        .setEditable(),
    feedLayout: new ObjectXMLField('feedLayout', 'Feed Layout')
        .setMinApi(30)
        .setEditable()
        .setFieldKey('autocollapsePublisher')
        .setSortOrder(undefined)
        .addField('autocollapsePublisher', new BooleanXMLField('autocollapsePublisher', 'Autocollapse Publisher')
            .setEditable()
        )
        .addField('compactFeed', new BooleanXMLField('compactFeed', 'Compact Feed')
            .setEditable()
        )
        .addField('feedFilterPosition', new EnumXMLField('feedFilterPosition', 'Feed Filter Position')
            .setEditable()
            .addEnumValue('Center Drop Down', 'centerDropDown')
            .addEnumValue('Left Fixed', 'leftFixed')
            .addEnumValue('Left Float', 'leftFloat')
        )
        .addField('feedFilters', new ArrayXMLField('feedFilters', 'Feed Filters')
            .setEditable()
            .setFieldKey('feedFilterName')
            .setSortOrder(undefined)
            .addField('feedFilterName', new StringXMLField('feedFilterName', 'Feed Filter Name')
                .setEditable()
            )
            .addField('feedFilterType', new EnumXMLField('feedFilterType', 'Feed Filter Type')
                .setEditable()
                .addEnumValue('All Updates', 'AllUpdates')
                .addEnumValue('Feed Item Type', 'FeedItemType')
            )
            .addField('feedItemType', new EnumXMLField('feedItemType', 'Feed Item Type')
                .setEditable()
                .addEnumValue('Activity Event', 'ActivityEvent')
                .addEnumValue('Advanced Text Post', 'AdvancedTextPost', 31)
                .addEnumValue('Announcement Post', 'AnnouncementPost')
                .addEnumValue('Approval Post', 'ApprovalPost')
                .addEnumValue('Attach Article Event', 'AttachArticleEvent')
                .addEnumValue('Basic Template Feed Item', 'BasicTemplateFeedItem')
                .addEnumValue('Call Log Post', 'CallLogPost')
                .addEnumValue('Canvas Post', 'CanvasPost')
                .addEnumValue('Case Comment Post', 'CaseCommentPost')
                .addEnumValue('Change Status Post', 'ChangeStatusPost')
                .addEnumValue('Chat Transcript Post', 'ChatTranscriptPost')
                .addEnumValue('Collaboration Group Created', 'CollaborationGroupCreated')
                .addEnumValue('Collaboration Group Unarchived', 'CollaborationGroupUnarchived')
                .addEnumValue('Content Post', 'ContentPost')
                .addEnumValue('Created Record Event', 'CreatedRecordEvent')
                .addEnumValue('Dashboard Component Snapshot', 'DashboardComponentSnapshot')
                .addEnumValue('Email Message Event', 'EmailMessageEvent')
                .addEnumValue('Facebook Post', 'FacebookPost')
                .addEnumValue('Link Post', 'LinkPost')
                .addEnumValue('Milestone Event', 'MilestoneEvent')
                .addEnumValue('Poll Post', 'PollPost')
                .addEnumValue('Profile Skill Post', 'ProfileSkillPost', 31)
                .addEnumValue('Question Post', 'QuestionPost', 31)
                .addEnumValue('Reply Post', 'ReplyPost')
                .addEnumValue('Rypple Post', 'RypplePost')
                .addEnumValue('Social Post', 'SocialPost')
                .addEnumValue('Text Post', 'TextPost')
                .addEnumValue('Tracked Change', 'TrackedChange')
                .addEnumValue('User Status', 'UserStatus')
            )
        )
        .addField('fullWidthFeed', new BooleanXMLField('fullWidthFeed', 'Full Width Feed')
            .setEditable()
        )
        .addField('hideSidebar', new BooleanXMLField('hideSidebar', 'Hide Sidebar')
            .setEditable()
        )
        .addField('leftComponents', new ArrayXMLField('leftComponents', 'Left Components')
            .setEditable()
            .setFieldKey('page')
            .setSortOrder(undefined)
            .addField('componentType', new EnumXMLField('componentType', 'Component Type')
                .setEditable()
                .addEnumValue('Help And Tool Links', 'HelpAndToolLinks')
                .addEnumValue('Custom Buttons', 'CustomButtons')
                .addEnumValue('Following', 'Following')
                .addEnumValue('Followers', 'Followers')
                .addEnumValue('Custom Links', 'CustomLinks')
                .addEnumValue('Milestones', 'Milestones')
                .addEnumValue('Topics', 'Topics')
                .addEnumValue('Case Unified Files', 'CaseUnifiedFiles')
                .addEnumValue('Visualforce', 'Visualforce')
            )
            .addField('height', new IntegerXMLField('height', 'Height')
                .setEditable()
            )
            .addField('page', new StringXMLField('page', 'Page')
                .setEditable()
                .setMetadataType(MetadataTypes.APEX_PAGE)
            )
        )
        .addField('rightComponents', new ArrayXMLField('rightComponents', 'Right Components')
            .setEditable()
            .setFieldKey('page')
            .setSortOrder(undefined)
            .addField('componentType', new EnumXMLField('componentType', 'Component Type')
                .setEditable()
                .addEnumValue('Help And Tool Links', 'HelpAndToolLinks')
                .addEnumValue('Custom Buttons', 'CustomButtons')
                .addEnumValue('Following', 'Following')
                .addEnumValue('Followers', 'Followers')
                .addEnumValue('Custom Links', 'CustomLinks')
                .addEnumValue('Milestones', 'Milestones')
                .addEnumValue('Topics', 'Topics')
                .addEnumValue('Case Unified Files', 'CaseUnifiedFiles')
                .addEnumValue('Visualforce', 'Visualforce')
            )
            .addField('height', new IntegerXMLField('height', 'Height')
                .setEditable()
            )
            .addField('page', new StringXMLField('page', 'Page')
                .setEditable()
                .setMetadataType(MetadataTypes.APEX_PAGE)
            )
        ),
    headers: new EnumXMLField('headers', 'Headers')
        .setMinApi(13)
        .addEnumValue('Personal Tagging', 'PersonalTagging')
        .addEnumValue('Public Tagging', 'PublicTagging'),
    layoutSections: new ArrayXMLField('layoutSections', 'Layout Sections')
        .setMinApi(13)
        .setFieldKey('label')
        .setSortOrder(undefined)
        .addField('customLabel', new StringXMLField('customLabel', 'Custom Label')
            .setEditable()
            .setRequired()
        )
        .addField('detailHeading', new BooleanXMLField('detailHeading', 'Detail Heading')
            .setEditable()
        )
        .addField('editHeading', new BooleanXMLField('editHeading', 'Edit Heading')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('layoutColumns', new ArrayXMLField('layoutColumns', 'Layout Columns')
            .setEditable()
            .setFieldKey('layoutItems')
            .setSortOrder(undefined)
            .addField('layoutItems', new ArrayXMLField('layoutItems', 'Layout Items')
                .setEditable()
                .setFieldKey('behavior')
                .setSortOrder(undefined)
                .addField('behavior', new EnumXMLField('behavior', 'Behavior')
                    .setEditable()
                    .addEnumValue('Edit', 'Edit')
                    .addEnumValue('Required', 'Required')
                    .addEnumValue('Read Only', 'Readonly')
                )
                .addField('canvas', new StringXMLField('canvas', 'Canvas')
                    .setMinApi(31)
                    .setEditable()
                )
                .addField('component', new StringXMLField('component', 'Component')
                    .setMinApi(30)
                    .setEditable()
                )
                .addField('customLink', new StringXMLField('customLink', 'Custom Link')
                    .setEditable()
                )
                .addField('emptySpace', new BooleanXMLField('emptySpace', 'Empty Space')
                    .setEditable()
                )
                .addField('field', new StringXMLField('field', 'Field')
                    .setEditable()
                    .setMetadataType(MetadataTypes.CUSTOM_FIELD)
                )
                .addField('height', new IntegerXMLField('height', 'Height')
                    .setEditable()
                )
                .addField('page', new StringXMLField('page', 'Page')
                    .setEditable()
                    .setMetadataType(MetadataTypes.APEX_PAGE)
                )
                .addField('analyticsCloudComponent', new ObjectXMLField('analyticsCloudComponent', 'Analytics Cloud Component')
                    .setMinApi(34)
                    .setEditable()
                    .setFieldKey('devName')
                    .setSortOrder(undefined)
                    .addField('assetType', new StringXMLField('assetType', 'Asset Type')
                        .setEditable()
                        .setRequired()
                    )
                    .addField('devName', new StringXMLField('devName', 'Developer Name')
                        .setEditable()
                        .setRequired()
                        .setUnique()
                    )
                    .addField('error', new StringXMLField('error', 'Error')
                        .setEditable()
                    )
                    .addField('filter', new StringXMLField('filter', 'Filter')
                        .setEditable()
                    )
                    .addField('height', new IntegerXMLField('height', 'Height')
                        .setEditable()
                    )
                    .addField('hideOnError', new BooleanXMLField('hideOnError', 'Hide On Error')
                        .setEditable()
                    )
                    .addField('showSharing', new BooleanXMLField('showSharing', 'Show Sharing')
                        .setEditable()
                    )
                    .addField('showTitle', new BooleanXMLField('showTitle', 'Show Title')
                        .setEditable()
                    )
                    .addField('height', new StringXMLField('height', 'Height')
                        .setEditable()
                    )
                )
                .addField('reportChartComponent', new ArrayXMLField('reportChartComponent', 'Report Chart Component')
                    .setEditable()
                    .setFieldKey('reportName')
                    .setSortOrder(undefined)
                    .addField('cacheData', new BooleanXMLField('cacheData', 'Cache Data')
                        .setEditable()
                    )
                    .addField('contextFilterableField', new StringXMLField('contextFilterableField', 'Context Filterable Field')
                        .setEditable()
                        .setMetadataType(MetadataTypes.CUSTOM_FIELD)
                    )
                    .addField('error', new StringXMLField('error', 'Error')
                        .setEditable()
                    )
                    .addField('hideOnError', new BooleanXMLField('hideOnError', 'Hide On Error')
                        .setEditable()
                    )
                    .addField('includeContext', new BooleanXMLField('includeContext', 'Include Context')
                        .setEditable()
                    )
                    .addField('reportName', new StringXMLField('reportName', 'Report Name')
                        .setEditable()
                        .setMetadataType(MetadataTypes.REPORT)
                    )
                    .addField('showTitle', new BooleanXMLField('showTitle', 'Show Title')
                        .setEditable()
                    )
                    .addField('size', new EnumXMLField('size', 'Size')
                        .setEditable()
                        .addEnumValue('Small', 'SMALL')
                        .addEnumValue('Medium', 'MEDIUM')
                        .addEnumValue('Large', 'LARGE')
                    )
                )

                .addField('showLabel', new BooleanXMLField('showLabel', 'Show Label')
                    .setEditable()
                )
                .addField('showScrollbars', new BooleanXMLField('showScrollbars', 'Show Scrollbars')
                    .setEditable()
                )
                .addField('scontrol', new StringXMLField('scontrol', 'S-Control')
                    .setEditable()
                    .setMetadataType(MetadataTypes.S_CONTROL)
                )
                .addField('height', new StringXMLField('height', 'Height')
                    .setEditable()
                )
            )
        )
        .addField('style', new EnumXMLField('style', 'Style')
            .setEditable()
            .addEnumValue('Two Columns Top To Bottom', 'TwoColumnsTopToBottom')
            .addEnumValue('Two Columns Left To Right', 'TwoColumnsLeftToRight')
            .addEnumValue('One Column', 'OneColumn')
            .addEnumValue('Custom Links', 'CustomLinks')
        ),
    miniLayout: new ObjectXMLField('miniLayout', 'Mini Layout')
        .setMinApi(13)
        .setEditable()
        .setFieldKey('fields')
        .setSortOrder(undefined)
        .addField('fields', new ArrayXMLField('fields', 'Fields')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        )
        .addField('relatedLists', new ArrayXMLField('relatedLists', 'Related Lists')
            .setEditable()
            .setFieldKey('fields')
            .setSortOrder(undefined)
            .addField('customButtons', new ArrayXMLField('customButtons', 'Custom Buttons')
                .setEditable()
                .setMetadataType(MetadataTypes.WEBLINK)
            )
            .addField('excludeButtons', new ArrayXMLField('excludeButtons', 'Exclude Buttons')
                .setEditable()
            )
            .addField('fields', new ArrayXMLField('fields', 'Fields')
                .setEditable()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('relatedList', new StringXMLField('relatedList', 'Related List')
                .setEditable()
                .setRequired()
            )
            .addField('sortField', new StringXMLField('sortField', 'Sort Field')
                .setEditable()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('sortOrder', new EnumXMLField('sortOrder', 'Sort Order')
                .setEditable()
                .addEnumValue('ASC', 'Asc')
                .addEnumValue('DESC', 'Desc')
            )
        ),
    multilineLayoutFields: new ArrayXMLField('multilineLayoutFields', 'Multiline Layout Fields')
        .setMinApi(13)
        .setEditable(),
    platformActionList: new ObjectXMLField('platformActionList', 'Platform Action List')
        .setMinApi(34)
        .setEditable()
        .setFieldKey('actionListContext')
        .setSortOrder(undefined)
        .addField('actionListContext', new EnumXMLField('actionListContext', 'Action List Context')
            .setEditable()
            .setRequired()
            .addEnumValue('Action Definition', 'ActionDefinition')
            .addEnumValue('Assistant', 'Assistant')
            .addEnumValue('Banner Photo', 'BannerPhoto')
            .addEnumValue('Chatter', 'Chatter')
            .addEnumValue('Dockable', 'Dockable')
            .addEnumValue('Feed Element', 'FeedElement')
            .addEnumValue('Flexi Page', 'Flexipage')
            .addEnumValue('Global', 'Global')
            .addEnumValue('List View', 'ListView')
            .addEnumValue('List View Definition', 'ListViewDefinition')
            .addEnumValue('List View Record', 'ListViewRecord')
            .addEnumValue('Lookup', 'Lookup')
            .addEnumValue('MRU List', 'MruList')
            .addEnumValue('MRU Row', 'MruRow')
            .addEnumValue('Object Home Chart', 'ObjectHomeChart')
            .addEnumValue('Photo', 'Photo')
            .addEnumValue('Record', 'Record')
            .addEnumValue('Record Edit', 'RecordEdit')
            .addEnumValue('Related List', 'RelatedList')
            .addEnumValue('Related List Record', 'RelatedListRecord')
        )
        .addField('platformActionListItems', new ArrayXMLField('platformActionListItems', 'Platform Action List Items')
            .setEditable()
            .setFieldKey('actionName')
            .setSortOrder(['sortOrder', 'actionName'])
            .addField('actionName', new StringXMLField('actionName', 'Action Name')
                .setEditable()
                .setRequired()
            )
            .addField('actionType', new EnumXMLField('actionType', 'Action Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Action Link', 'ActionLink')
                .addEnumValue('Custom Button', 'CustomButton')
                .addEnumValue('Invocable Action', 'InvocableAction')
                .addEnumValue('Productivity Action', 'ProductivityAction')
                .addEnumValue('Quick Action', 'QuickAction')
                .addEnumValue('Standard Button', 'StandardButton')
            )
            .addField('sortOrder', new IntegerXMLField('sortOrder', 'Sort Order')
                .setEditable()
                .setRequired()
            )
            .addField('subtype', new EnumXMLField('subtype', 'Subtype')
                .setEditable()
                .addEnumValue('Weblink Type Enum', 'WebLinkTypeEnum')
                .addEnumValue('API', 'Api')
                .addEnumValue('API Async', 'ApiAsync')
                .addEnumValue('Download', 'Download')
                .addEnumValue('UI', 'Ui')
                .addDependencyField(new XMLDependencyField('actionType', 'QuickAction', 'QuickActionType'))
                .addDependencyField(new XMLDependencyField('actionType', 'CustomButton', 'WebLinkTypeEnum'))
                .addDependencyField(new XMLDependencyField('actionType', 'ActionLink', ['Api', 'ApiAsync', 'Download', 'Ui']))
                .addDependencyField(new XMLDependencyField('actionType', ['StandardButton', 'ProductivityAction', 'InvocableAction'], DataValues.NOT_AVAILABLE))
            )
        )
        .addField('relatedSourceEntity', new StringXMLField('relatedSourceEntity', 'Related Source Entity')
            .setEditable()
        ),
    quickActionList: new ObjectXMLField('quickActionList', 'Quick Action List')
        .setMinApi(28)
        .setEditable()
        .setFieldKey('quickActionListItems')
        .setSortOrder(undefined)
        .addField('quickActionListItems', new ArrayXMLField('quickActionListItems', 'Quick Action List Items')
            .setEditable()
            .setFieldKey('quickActionName')
            .addField('quickActionName', new StringXMLField('quickActionName', 'Quick Action Name')
                .setEditable()
                .setRequired()
            )
        ),
    relatedContent: new ObjectXMLField('relatedContent', 'Related Content')
        .setMinApi(29)
        .setEditable()
        .setFieldKey('relatedContentItems')
        .setSortOrder(undefined)
        .addField('relatedContentItems', new ArrayXMLField('relatedContentItems', 'Related Content Items')
            .setEditable()
            .setFieldKey('layoutItem')
            .setSortOrder(undefined)
            .addField('layoutItem', new ObjectXMLField('layoutItem', 'Layout Item')
                .setEditable()
                .setFieldKey('behavior')
                .setSortOrder(undefined)
                .addField('behavior', new EnumXMLField('behavior', 'Behavior')
                    .setEditable()
                    .addEnumValue('Edit', 'Edit')
                    .addEnumValue('Required', 'Required')
                    .addEnumValue('Read Only', 'Readonly')
                )
                .addField('canvas', new StringXMLField('canvas', 'Canvas')
                    .setMinApi(31)
                    .setEditable()
                )
                .addField('component', new StringXMLField('component', 'Component')
                    .setMinApi(30)
                    .setEditable()
                )
                .addField('customLink', new StringXMLField('customLink', 'Custom Link')
                    .setEditable()
                )
                .addField('emptySpace', new BooleanXMLField('emptySpace', 'Empty Space')
                    .setEditable()
                )
                .addField('field', new StringXMLField('field', 'Field')
                    .setEditable()
                    .setMetadataType(MetadataTypes.CUSTOM_FIELD)
                )
                .addField('height', new IntegerXMLField('height', 'Height')
                    .setEditable()
                )
                .addField('page', new StringXMLField('page', 'Page')
                    .setEditable()
                    .setMetadataType(MetadataTypes.APEX_PAGE)
                )
                .addField('analyticsCloudComponent', new ObjectXMLField('analyticsCloudComponent', 'Analytics Cloud Component')
                    .setMinApi(34)
                    .setEditable()
                    .setFieldKey('devName')
                    .setSortOrder(undefined)
                    .addField('assetType', new StringXMLField('assetType', 'Asset Type')
                        .setEditable()
                        .setRequired()
                    )
                    .addField('devName', new StringXMLField('devName', 'Developer Name')
                        .setEditable()
                        .setRequired()
                        .setUnique()
                    )
                    .addField('error', new StringXMLField('error', 'Error')
                        .setEditable()
                    )
                    .addField('filter', new StringXMLField('filter', 'Filter')
                        .setEditable()
                    )
                    .addField('height', new IntegerXMLField('height', 'Height')
                        .setEditable()
                    )
                    .addField('hideOnError', new BooleanXMLField('hideOnError', 'Hide On Error')
                        .setEditable()
                    )
                    .addField('showSharing', new BooleanXMLField('showSharing', 'Show Sharing')
                        .setEditable()
                    )
                    .addField('showTitle', new BooleanXMLField('showTitle', 'Show Title')
                        .setEditable()
                    )
                    .addField('height', new StringXMLField('height', 'Height')
                        .setEditable()
                    )
                )
                .addField('reportChartComponent', new ArrayXMLField('reportChartComponent', 'Report Chart Component')
                    .setEditable()
                    .setFieldKey('reportName')
                    .setSortOrder(undefined)
                    .addField('cacheData', new BooleanXMLField('cacheData', 'Cache Data')
                        .setEditable()
                    )
                    .addField('contextFilterableField', new StringXMLField('contextFilterableField', 'Context Filterable Field')
                        .setEditable()
                        .setMetadataType(MetadataTypes.CUSTOM_FIELD)
                    )
                    .addField('error', new StringXMLField('error', 'Error')
                        .setEditable()
                    )
                    .addField('hideOnError', new BooleanXMLField('hideOnError', 'Hide On Error')
                        .setEditable()
                    )
                    .addField('includeContext', new BooleanXMLField('includeContext', 'Include Context')
                        .setEditable()
                    )
                    .addField('reportName', new StringXMLField('reportName', 'Report Name')
                        .setEditable()
                        .setMetadataType(MetadataTypes.REPORT)
                    )
                    .addField('showTitle', new BooleanXMLField('showTitle', 'Show Title')
                        .setEditable()
                    )
                    .addField('size', new EnumXMLField('size', 'Size')
                        .setEditable()
                        .addEnumValue('Small', 'SMALL')
                        .addEnumValue('Medium', 'MEDIUM')
                        .addEnumValue('Large', 'LARGE')
                    )
                )

                .addField('showLabel', new BooleanXMLField('showLabel', 'Show Label')
                    .setEditable()
                )
                .addField('showScrollbars', new BooleanXMLField('showScrollbars', 'Show Scrollbars')
                    .setEditable()
                )
                .addField('scontrol', new StringXMLField('scontrol', 'S-Control')
                    .setEditable()
                    .setMetadataType(MetadataTypes.S_CONTROL)
                )
                .addField('height', new StringXMLField('height', 'Height')
                    .setEditable()
                )
            )
        ),
    relatedLists: new ArrayXMLField('relatedLists', 'Related Lists')
        .setMinApi(13)
        .setEditable()
        .setFieldKey('fields')
        .setSortOrder(undefined)
        .addField('customButtons', new ArrayXMLField('customButtons', 'Custom Buttons')
            .setEditable()
            .setMetadataType(MetadataTypes.WEBLINK)
        )
        .addField('excludeButtons', new ArrayXMLField('excludeButtons', 'Exclude Buttons')
            .setEditable()
        )
        .addField('fields', new ArrayXMLField('fields', 'Fields')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        )
        .addField('relatedList', new StringXMLField('relatedList', 'Related List')
            .setEditable()
            .setRequired()
        )
        .addField('sortField', new StringXMLField('sortField', 'Sort Field')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        )
        .addField('sortOrder', new EnumXMLField('sortOrder', 'Sort Order')
            .setEditable()
            .addEnumValue('ASC', 'Asc')
            .addEnumValue('DESC', 'Desc')
        ),
    relatedObjects: new ArrayXMLField('relatedObjects', 'Related Objects')
        .setMinApi(13)
        .setEditable()
        .setMetadataType(MetadataTypes.CUSTOM_OBJECT),
    runAssignmentRulesDefault: new BooleanXMLField('runAssignmentRulesDefault', 'Run Assignment Rules Default')
        .setEditable()
        .setMinApi(13),
    showEmailCheckbox: new BooleanXMLField('showEmailCheckbox', 'Show Email Checkbox')
        .setEditable()
        .setMinApi(13),
    showHighlightsPanel: new BooleanXMLField('showHighlightsPanel', 'show Highlights Panel')
        .setMinApi(22)
        .setEditable(),
    showInteractionLogPanel: new BooleanXMLField('showInteractionLogPanel', 'Show Interaction Log Panel')
        .setMinApi(22)
        .setEditable(),
    showKnowledgeComponent: new BooleanXMLField('showKnowledgeComponent', 'Show Knowledge Component')
        .setMinApi(22)
        .setEditable(),
    showRunAssignmentRulesCheckbox: new BooleanXMLField('showRunAssignmentRulesCheckbox', 'Show un Assignment Rules Checkbox')
        .setEditable()
        .setMinApi(13),
    showSolutionSection: new BooleanXMLField('showSolutionSection', 'Show Solution Section')
        .setMinApi(22)
        .setEditable(),
    showSubmitAndAttachButton: new BooleanXMLField('showSubmitAndAttachButton', 'Show Submit And Attach Button')
        .setEditable()
        .setMinApi(13),
    summaryLayout: new ObjectXMLField('summaryLayout', 'Summary Layout')
        .setMinApi(18)
        .setEditable()
        .setFieldKey('masterLabel')
        .setSortOrder(undefined)
        .addField('masterLabel', new StringXMLField('masterLabel', 'Master Label')
            .setEditable()
            .setRequired()
            .setUnique()
        )
        .addField('sizeX', new IntegerXMLField('sizeX', 'Size X')
            .setEditable()
            .setRequired()
            .setMinValue(1)
            .setMaxValue(4)
        )
        .addField('sizeY', new IntegerXMLField('sizeY', 'Size Y')
            .setEditable()
            .setRequired()
            .setMinValue(1)
            .setMaxValue(2)
        )
        .addField('summaryLayoutItems', new ArrayXMLField('summaryLayoutItems', 'Summary Layout Items')
            .setEditable()
            .setFieldKey('field')
            .setSortOrder(undefined)
            .addField('customLink', new StringXMLField('customLink', 'Custom Link')
                .setEditable()
            )
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setMetadataType(MetadataTypes.CUSTOM_FIELD)
            )
            .addField('posX', new IntegerXMLField('posX', 'Pos X')
                .setEditable()
                .setRequired()
                .setMinValue(1)
                .setMaxValue(4)
            )
            .addField('posY', new IntegerXMLField('posY', 'Pos Y')
                .setEditable()
                .setRequired()
                .setMinValue(1)
                .setMaxValue(2)
            )
        )
        .addField('summaryLayoutStyle', new EnumXMLField('summaryLayoutStyle', 'Summary Layout Style')
            .setEditable()
            .addEnumValue('Default', 'Default')
            .addEnumValue('Quote Template', 'QuoteTemplate')
            .addEnumValue('Default Quote Template', 'DefaultQuoteTemplate')
            .addEnumValue('Case Interaction', 'CaseInteraction')
            .addEnumValue('Quick Action Layout Left Right', 'QuickActionLayoutLeftRight', 28)
            .addEnumValue('Quick Action Layout Top Down', 'QuickActionLayoutTopDown', 28)
        )
}