const { StringXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField } = require('@ah/core').Types;
const { MetadataTypes } = require('@ah/core').Values;

module.exports = {
    category: new EnumXMLField('category', 'Category')
        .setMinApi(43)
        .setEditable()
        .setRequired()
        .addEnumValue('Communications', 'Communications')
        .addEnumValue('Education', 'Education')
        .addEnumValue('Financial Services', 'FinancialServices')
        .addEnumValue('General Business', 'GeneralBusiness')
        .addEnumValue('Government', 'Government')
        .addEnumValue('Healthcare Life Sciences', 'HealthcareLifeSciences')
        .addEnumValue('High Tech', 'HighTech')
        .addEnumValue('Manufacturing', 'Manufacturing')
        .addEnumValue('Media', 'Media')
        .addEnumValue('Nonprofits', 'Nonprofits')
        .addEnumValue('Professional Services', 'ProfessionalServices')
        .addEnumValue('Real Estate', 'RealEstate')
        .addEnumValue('Retail', 'Retail')
        .addEnumValue('Travel Transportation Hospitality', 'TravelTransportationHospitality'),
    lightningBoltFeatures: new ArrayXMLField('lightningBoltFeatures', 'Lightning Bolt Features')
        .setMinApi(43)
        .setEditable()
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('order', new IntegerXMLField('order', 'Order')
            .setEditable()
            .setRequired()
            .setMinValue(1)
            .setMaxValue(4)
        )
        .addField('title', new StringXMLField('title', 'Title')
            .setEditable()
            .setRequired()
        ),
    lightningBoltImages: new ArrayXMLField('lightningBoltImages', 'Lightning Bolt Images')
        .setMinApi(43)
        .setEditable()
        .addField('image', new StringXMLField('image', 'Image')
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CONTENT_ASSET)
        )
        .addField('order', new IntegerXMLField('order', 'Order')
            .setEditable()
            .setRequired()
            .setMinValue(1)
            .setMaxValue(3)
        ),
    lightningBoltItems: new ArrayXMLField('lightningBoltItems', 'Lightning Bolt Items')
        .setMinApi(43)
        .setEditable()
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Community Template Definition', 'CommunityTemplateDefinition')
            .addEnumValue('Custom Application', 'CustomApplication')
            .addEnumValue('Flow Category', 'FlowCategory')
        ),
    masterLabel: new StringXMLField('masterLabel', 'Master Label')
        .setMinApi(43)
        .setEditable()
        .setRequired()
        .setUnique(),
    publisher: new StringXMLField('publisher', 'Publisher')
        .setMinApi(43)
        .setEditable()
        .setRequired(),
    summary: new StringXMLField('summary', 'Summary')
        .setMinApi(43)
        .setEditable()
        .setRequired(),

}