const { StringXMLField, ArrayXMLField, EnumXMLField, BooleanXMLField, XMLDataControlledField } = require('@ah/core').Types;
const { MetadataTypes, DataValues } = require('@ah/core').Values;

module.exports = {
    label: new StringXMLField('label', 'label'),
    userLicense: new StringXMLField('userLicense', 'User License')
        .setMinApi(46),
    license: new StringXMLField('license', 'License')
        .setMinApi(46),
    description: new StringXMLField('description', 'Description')
        .setMinApi(46)
        .setEditable(),
    hasActivationRequired: new BooleanXMLField('hasActivationRequired', 'Has Activation Required')
        .setMinApi(46),
    applicationVisibilities: new ArrayXMLField('applicationVisibilities', 'Application ')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.CUSTOM_APPLICATION)
        .setEditable()
        .setMergeable()
        .setFieldKey('application')
        .addField('application', new StringXMLField('application', 'Application')
            .setUnique()
        )
        .addField('visible', new BooleanXMLField('visible', 'Visible')
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('default', new BooleanXMLField('default', 'Default')
            .setEditable()
            .setUnique()
            .addControlledField(new XMLDataControlledField('visible', true, true))
        ),
    classAccesses: new ArrayXMLField('classAccesses', 'Class Accesses')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.APEX_CLASS)
        .setEditable()
        .setMergeable()
        .setFieldKey('apexClass')
        .addField('apexClass', new StringXMLField('apexClass', 'Apex Class')
            .setUnique()
        )
        .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
            .setEditable()
            .setDefaultValue(true)
        ),
    customMetadataTypeAccesses: new ArrayXMLField('customMetadataTypeAccesses', 'Custom Metadata Type Accesses')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.CUSTOM_METADATA)
        .setEditable()
        .setFieldKey('name')
        .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setUnique()
        ),
    customPermissions: new ArrayXMLField('customPermissions', 'Custom Permissions')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.CUSTOM_PERMISSION)
        .setEditable()
        .setFieldKey('name')
        .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setUnique()
        ),
    customSettingAccesses: new ArrayXMLField('customSettingAccesses', 'Custom Settings Accesses')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        .setEditable()
        .setFieldKey('name')
        .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setUnique()
        ),
    externalDataSourceAccesses: new ArrayXMLField('externalDataSourceAccesses', 'External Data Source Accesses')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        .setEditable()
        .setFieldKey('externalDataSource')
        .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('externalDataSource', new StringXMLField('externalDataSource', 'externalDataSource')
            .setUnique()
        ),
    fieldPermissions: new ArrayXMLField('fieldPermissions', 'Field Permissions')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        .setEditable()
        .setMergeable()
        .setFieldKey('field')
        .addField('readable', new BooleanXMLField('readable', 'Readable')
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('field', new StringXMLField('field', 'Field')
            .setUnique()
            .setSeparator(DataValues.POINT)
        )
        .addField('editable', new BooleanXMLField('editable', 'Editable')
            .setEditable()
            .setDefaultValue(false)
            .addControlledField(new XMLDataControlledField('readable', true, true))
        ),
    flowAccesses: new ArrayXMLField('flowAccesses', 'Flow Accesses')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.FLOWS)
        .setEditable()
        .setMergeable()
        .setFieldKey('flow')
        .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('flow', new StringXMLField('flow', 'Flow')
            .setUnique()
        ),
    objectPermissions: new ArrayXMLField('objectPermissions', 'Object Permissions')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        .setEditable()
        .setMergeable()
        .setFieldKey('object')
        .addField('allowRead', new BooleanXMLField('allowRead', 'Allow Read')
            .setEditable()
            .setDefaultValue(true)
            .addControlledField(new XMLDataControlledField('allowCreate', false, false))
            .addControlledField(new XMLDataControlledField('allowEdit', false, false))
            .addControlledField(new XMLDataControlledField('allowDelete', false, false))
            .addControlledField(new XMLDataControlledField('viewAllRecords', false, false))
            .addControlledField(new XMLDataControlledField('modifyAllRecords', false, false))
        )
        .addField('allowCreate', new BooleanXMLField('allowCreate', 'Allow Create')
            .setEditable()
            .setDefaultValue(true)
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
        )
        .addField('allowEdit', new BooleanXMLField('allowEdit', 'Allow Edit')
            .setEditable()
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
            .addControlledField(new XMLDataControlledField('allowDelete', false, false))
            .addControlledField(new XMLDataControlledField('modifyAllRecords', false, false))
        )
        .addField('allowDelete', new BooleanXMLField('allowDelete', 'Allow Delete')
            .setEditable()
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
            .addControlledField(new XMLDataControlledField('allowEdit', true, true))
            .addControlledField(new XMLDataControlledField('modifyAllRecords', false, false))
        )
        .addField('object', new StringXMLField('object', 'Object')
            .setUnique()
        )
        .addField('viewAllRecords', new BooleanXMLField('viewAllRecords', 'View All Records')
            .setEditable()
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
            .addControlledField(new XMLDataControlledField('modifyAllRecords', false, false))
        )
        .addField('modifyAllRecords', new BooleanXMLField('modifyAllRecords', 'Modify All Records')
            .setEditable()
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
            .addControlledField(new XMLDataControlledField('allowEdit', true, true))
            .addControlledField(new XMLDataControlledField('allowDelete', true, true))
            .addControlledField(new XMLDataControlledField('viewAllRecords', true, true))
        ),
    pageAccesses: new ArrayXMLField('pageAccesses', 'Visualforce Accesses')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.APEX_PAGE)
        .setEditable()
        .setMergeable()
        .setFieldKey('apexPage')
        .addField('apexPage', new StringXMLField('apexPage', 'Apex Page')
            .setUnique()
        )
        .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
            .setEditable()
            .setDefaultValue(true)
        ),
    recordTypeVisibilities: new ArrayXMLField('recordTypeVisibilities', 'Record Type Visibilities')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.RECORD_TYPE)
        .setEditable()
        .setFieldKey('recordType')
        .addField('default', new BooleanXMLField('default', 'Default')
            .setEditable()
            .setUnique()
        )
        .addField('personAccountDefault', new BooleanXMLField('personAccountDefault', 'Person Account Default')
            .setEditable()
            .setUnique()
        )
        .addField('recordType', new StringXMLField('recordType', 'Record Type')
            .setUnique()
            .setSeparator(DataValues.POINT)
        )
        .addField('visible', new BooleanXMLField('visible', 'Visible')
            .setEditable()
            .setDefaultValue(true)
        ),
    tabSettings: new ArrayXMLField('tabSettings', 'Tab Settings')
        .setMinApi(46)
        .setMetadataType(MetadataTypes.TAB)
        .setEditable()
        .addField('tab', new StringXMLField('tab', 'Tab')
            .setUnique()
        )
        .addField('visibility', new EnumXMLField('visibility', 'visibility')
            .setEditable()
            .setDefaultValue('DefaultOn')
            .addEnumValue('Default On', 'DefaultOn')
            .addEnumValue('Default Off', 'DefaultOff')
            .addEnumValue('Hidden', 'Hidden')
        ),
    userPermissions: new ArrayXMLField('userPermissions', 'User Permissions')
        .setMinApi(46)
        .setEditable()
        .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
            .setEditable()
            .setDefaultValue(true)
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setUnique()
        )
}