import { StringXMLField, BooleanXMLField, ArrayXMLField, XMLDependencyField, DataValues, MetadataTypes, EnumXMLField, IntegerXMLField, ObjectXMLField } from '@aurahelper/core';

export const NavigationMenu = {
    container: new StringXMLField('container', 'Container')
        .setMinApi(47)
        .setEditable(),
    containerType: new EnumXMLField('containerType', 'Container Type')
        .setMinApi(47)
        .setEditable()
        .addEnumValue('Network', 'Network')
        .addEnumValue('Community Template Definition', 'CommunityTemplateDefinition'),
    label: new StringXMLField('label', 'Label')
        .setMinApi(47)
        .setEditable(),
    navigationMenuItem: new ArrayXMLField('navigationMenuItem', 'Navigation Menu Item')
        .setMinApi(47)
        .setEditable()
        .setFieldKey('label')
        .setSortOrder()
        .addField('defaultListViewId', new ArrayXMLField('defaultListViewId', 'Default List View Id')
            .setEditable()
        )
        .addField('label', new ArrayXMLField('label', 'Label')
            .setEditable()
        )
        .addField('navigationMenuItemBranding', new ArrayXMLField('navigationMenuItemBranding', 'Navigation Menu Item Branding')
            .setEditable()
            .setMetadataType(MetadataTypes.CONTENT_ASSET)
        )
        .addField('position', new IntegerXMLField('position', 'Position')
            .setEditable()
            .setRequired()
        )
        .addField('publiclyAvailable', new BooleanXMLField('publiclyAvailable', 'Publicly Available')
            .setEditable()
        )
        .addField('subMenu', new ObjectXMLField('subMenu', 'Sub Menu')
            .setEditable()
            .setFieldKey('navigationMenuItem')
            .setSortOrder(undefined)
            .addField('navigationMenuItem', new ArrayXMLField('navigationMenuItem', 'Navigation Menu Item')
                .setEditable()
                .setDefinitionReference('this>navigationMenuItem')
            )
        )
        .addField('target', new StringXMLField('target', 'Target')
            .setEditable()
            .addDependencyField(new XMLDependencyField('type', ['ExternalLink', 'InternalLink', 'SalesforceObject'], DataValues.NOT_NULL))
        )
        .addField('targetPreference', new EnumXMLField('targetPreference', 'Target Preference')
            .setEditable()
            .addEnumValue('None', 'None')
            .addEnumValue('Open In External Tab', 'OpenInExternalTab')
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .addEnumValue('Salesforce Object', 'SalesforceObject')
            .addEnumValue('External Link', 'ExternalLink')
            .addEnumValue('Internal Link', 'InternalLink')
            .addEnumValue('Menu Label', 'MenuLabel')
            .addEnumValue('Navigational Topic', 'NavigationalTopic')
        )
};