const { StringXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField, BooleanXMLField, XMLDependencyField, DoubleXMLField } = require('@aurahelper/core').Types;
const { MetadataTypes, DataValues } = require('@aurahelper/core').Values;
const NetworkBranding = require('./networkBranding');

module.exports = {
    allowedExtensions: new StringXMLField('allowedExtensions', 'Allowed Extensions')
        .setMinApi(36)
        .setEditable(),
    allowInternalUserLogin: new BooleanXMLField('allowInternalUserLogin', 'Allow Internal User Login')
        .setMinApi(40)
        .setEditable(),
    allowMembersToFlag: new BooleanXMLField('allowMembersToFlag', 'Allow Members To Flag')
        .setMinApi(29)
        .setEditable(),
    branding: new ObjectXMLField('branding', 'Branding')
        .setMinApi(41)
        .setEditable()
        .setFieldKey('loginFooterText')
        .setSortOrder(undefined)
        .setFields(NetworkBranding),
    caseCommentEmailTemplate: new StringXMLField('caseCommentEmailTemplate', 'Case Comment Email Template')
        .setMinApi(28)
        .setEditable(),
    changePasswordTemplate: new StringXMLField('changePasswordTemplate', 'Change Password Template')
        .setMinApi(28)
        .setEditable(),
    communityRoles: new ObjectXMLField('communityRoles', 'Community Roles')
        .setMinApi(41)
        .setEditable()
        .setFieldKey('customerUserRole')
        .setSortOrder(undefined)
        .addField('customerUserRole', new StringXMLField('customerUserRole', 'Customer User Role')
            .setEditable()
        )
        .addField('employeeUserRole', new StringXMLField('employeeUserRole', 'Employee User Role')
            .setEditable()
        )
        .addField('partnerUserRole', new StringXMLField('partnerUserRole', 'Partner User Role')
            .setEditable()
        ),
    description: new StringXMLField('description', 'Description')
        .setMinApi(28)
        .setEditable(),
    disableReputationRecordConversations: new BooleanXMLField('disableReputationRecordConversations', 'Disable Reputation Record Conversations')
        .setMinApi(41)
        .setEditable(),
    emailFooterLogo: new StringXMLField('emailFooterLogo', 'Email Footer Logo')
        .setMinApi(41)
        .setEditable(),
    emailFooterText: new StringXMLField('emailFooterText', 'Email Footer Text')
        .setMinApi(41)
        .setEditable(),
    emailSenderAddress: new StringXMLField('emailSenderAddress', 'Email Sender Address')
        .setMinApi(28)
        .setEditable()
        .setRequired(),
    emailSenderName: new StringXMLField('emailSenderName', 'Email Sender Name')
        .setMinApi(28)
        .setEditable()
        .setRequired(),
    enableCustomVFErrorPageOverrides: new BooleanXMLField('enableCustomVFErrorPageOverrides', 'Enable Custom VF Error ​Page Overrides')
        .setMinApi(41)
        .setEditable(),
    enableDirectMessages: new BooleanXMLField('enableDirectMessages', 'Enable Direct Messages')
        .setMinApi(41)
        .setEditable(),
    enableGuestChatter: new BooleanXMLField('enableGuestChatter', 'Enable Guest Chatter')
        .setMinApi(28)
        .setEditable(),
    enableGuestFileAccess: new BooleanXMLField('enableGuestFileAccess', 'Enable Guest File Access')
        .setMinApi(41)
        .setEditable(),
    enableGuestMemberVisibility: new BooleanXMLField('enableGuestMemberVisibility', 'Enable Guest Member Visibility')
        .setMinApi(47)
        .setEditable(),
    enableInvitation: new BooleanXMLField('enableInvitation', 'Enable Invitation')
        .setMinApi(28)
        .setEditable(),
    enableKnowledgeable: new BooleanXMLField('enableKnowledgeable', 'Enable Knowledgeable')
        .setMinApi(30)
        .setEditable(),
    enableNicknameDisplay: new BooleanXMLField('enableNicknameDisplay', 'Enable Nickname Display')
        .setMinApi(32)
        .setEditable()
        .setDefaultValue(false),
    enablePrivateMessages: new BooleanXMLField('enablePrivateMessages', 'Enable Private Messages')
        .setMinApi(30)
        .setEditable(),
    enableReputation: new BooleanXMLField('enableReputation', 'Enable Reputation')
        .setMinApi(31)
        .setEditable(),
    enableShowAllNetworkSettings: new BooleanXMLField('enableShowAllNetworkSettings', 'Enable Show All Network Settings')
        .setMinApi(41)
        .setEditable(),
    enableSiteAsContainer: new BooleanXMLField('enableSiteAsContainer', 'Enable Site As Container')
        .setMinApi(28)
        .setEditable(),
    enableTalkingAboutStats: new BooleanXMLField('enableTalkingAboutStats', 'Enable Talking About Stats')
        .setMinApi(41)
        .setEditable(),
    enableTopicAssignmentRules: new BooleanXMLField('enableTopicAssignmentRules', 'Enable Topic Assignment Rules')
        .setMinApi(40)
        .setEditable(),
    enableTopicSuggestions: new BooleanXMLField('enableTopicSuggestions', 'Enable Topic Suggestions')
        .setMinApi(41)
        .setEditable(),
    enableUpDownVote: new BooleanXMLField('enableUpDownVote', 'Enable Up Down Vote')
        .setMinApi(41)
        .setEditable(),
    feedChannel: new StringXMLField('feedChannel', 'Feed Channel')
        .setMinApi(28)
        .setEditable(),
    forgotPasswordTemplate: new StringXMLField('forgotPasswordTemplate', 'Forgot Password Template')
        .setMinApi(28)
        .setEditable()
        .setRequired(),
    gatherCustomerSentimentData: new BooleanXMLField('gatherCustomerSentimentData', 'Gather Customer Sentiment Data')
        .setMinApi(40)
        .setEditable(),
    lockoutTemplate: new StringXMLField('lockoutTemplate', 'Lockout Template')
        .setMinApi(43)
        .setEditable(),
    logoutUrl: new StringXMLField('logoutUrl', 'Logout URL')
        .setMinApi(28)
        .setEditable(),
    maxFileSizeKb: new IntegerXMLField('maxFileSizeKb', 'Max File Size Kb')
        .setMinApi(36)
        .setEditable(),
    navigationLinkSet: new ObjectXMLField('navigationLinkSet', 'Navigation Link Set')
        .setMinApi(37)
        .setMaxApi(46)
        .setEditable()
        .setFieldKey('navigationMenuItem')
        .setSortOrder(undefined)
        .addField('navigationMenuItem', new ArrayXMLField('navigationMenuItem', 'Navigation Menu Item')
            .setEditable()
            .setFieldKey('label')
            .setSortOrder(undefined)
            .addField('defaultListViewId', new ArrayXMLField('defaultListViewId', 'Default List View Id')
                .setEditable()
            )
            .addField('label', new ArrayXMLField('label', 'Label')
                .setEditable()
            )
            .addField('navigationMenuItemBranding', new ArrayXMLField('navigationMenuItemBranding', 'Navigation Menu Item Branding')
                .setEditable()
                .setMetadataType(MetadataTypes.CONTENT_ASSET)
            )
            .addField('position', new IntegerXMLField('position', 'Position')
                .setEditable()
                .setRequired()
            )
            .addField('publiclyAvailable', new BooleanXMLField('publiclyAvailable', 'Publicly Available')
                .setEditable()
            )
            .addField('subMenu', new ObjectXMLField('subMenu', 'Sub Menu')
                .setEditable()
                .setFieldKey('navigationMenuItem')
                .setSortOrder(undefined)
                .addField('navigationMenuItem', new ArrayXMLField('navigationMenuItem', 'Navigation Menu Item')
                    .setEditable()
                    .setDefinitionReference('this>navigationLinkSet>navigationMenuItem')
                )
            )
            .addField('target', new StringXMLField('target', 'Target')
                .setEditable()
                .addDependencyField(new XMLDependencyField('type', ['ExternalLink', 'InternalLink', 'SalesforceObject'], DataValues.NOT_NULL))
            )
            .addField('targetPreference', new EnumXMLField('targetPreference', 'Target Preference')
                .setEditable()
                .addEnumValue('None', 'None')
                .addEnumValue('Open In External Tab', 'OpenInExternalTab')
            )
            .addField('type', new EnumXMLField('type', 'Type')
                .setEditable()
                .addEnumValue('Salesforce Object', 'SalesforceObject')
                .addEnumValue('External Link', 'ExternalLink')
                .addEnumValue('Internal Link', 'InternalLink')
                .addEnumValue('Menu Label', 'MenuLabel')
                .addEnumValue('Navigational Topic', 'NavigationalTopic')
            )
        ),
    networkMemberGroups: new ObjectXMLField('networkMemberGroups', 'Network Member Groups')
        .setMinApi(28)
        .setEditable()
        .setFieldKey('profile')
        .setSortOrder(undefined)
        .addField('permissionSet', new ArrayXMLField('permissionSet', 'Permission Set')
            .setEditable()
        )
        .addField('profile', new ArrayXMLField('profile', 'Profile')
            .setEditable()
        ),
    networkPageOverrides: new ObjectXMLField('networkPageOverrides', 'Network Page Overrides')
        .setMinApi(40)
        .setEditable()
        .setFieldKey('homePageOverrideSetting')
        .setSortOrder(undefined)
        .addField('changePasswordPageOverrideSetting', new EnumXMLField('changePasswordPageOverrideSetting', 'Change Password Page Override Setting')
            .setEditable()
            .setRequired()
            .addEnumValue('Configurable', 'Configurable')
            .addEnumValue('Designer', 'Designer')
            .addEnumValue('Standard', 'Standard')
            .addEnumValue('Visualforce', 'VisualForce')
        )
        .addField('forgotPasswordPageOverrideSetting', new EnumXMLField('forgotPasswordPageOverrideSetting', 'Forgot Password Page Override Setting')
            .setEditable()
            .setRequired()
            .addEnumValue('Configurable', 'Configurable')
            .addEnumValue('Designer', 'Designer')
            .addEnumValue('Standard', 'Standard')
            .addEnumValue('Visualforce', 'VisualForce')
        )
        .addField('homePageOverrideSetting', new EnumXMLField('homePageOverrideSetting', 'Home Page Override Setting')
            .setEditable()
            .setRequired()
            .addEnumValue('Configurable', 'Configurable')
            .addEnumValue('Designer', 'Designer')
            .addEnumValue('Standard', 'Standard')
            .addEnumValue('Visualforce', 'VisualForce')
        )
        .addField('loginPageOverrideSetting', new EnumXMLField('loginPageOverrideSetting', 'Login Page Override Setting')
            .setEditable()
            .setRequired()
            .addEnumValue('Configurable', 'Configurable')
            .addEnumValue('Designer', 'Designer')
            .addEnumValue('Standard', 'Standard')
            .addEnumValue('Visualforce', 'VisualForce')
        )
        .addField('selfRegProfilePageOverrideSetting', new EnumXMLField('selfRegProfilePageOverrideSetting', 'Self Registration Profile Page Override Setting')
            .setEditable()
            .setRequired()
            .addEnumValue('Configurable', 'Configurable')
            .addEnumValue('Designer', 'Designer')
            .addEnumValue('Standard', 'Standard')
            .addEnumValue('Visualforce', 'VisualForce')
        ),
    newSenderAddress: new StringXMLField('newSenderAddress', 'New Sender Address')
        .setMinApi(28)
        .setEditable(),
    enableMemberVisibility: new BooleanXMLField('enableMemberVisibility', 'Enable Member Visibility')
        .setMinApi(45)
        .setEditable(),
    picassoSite: new StringXMLField('picassoSite', 'Picasso Site')
        .setMinApi(28)
        .setEditable(),
    recommendationAudience: new ObjectXMLField('recommendationAudience', 'Recommendation Audience')
        .setMinApi(41)
        .setEditable()
        .setFieldKey('recommendationAudienceDetails')
        .setSortOrder(undefined)
        .addField('recommendationAudienceDetails', new ObjectXMLField('recommendationAudienceDetails', 'Recommendation Audience Details')
            .setEditable()
            .setFieldKey('setupName')
            .setSortOrder(undefined)
            .addField('audienceCriteriaType', new EnumXMLField('audienceCriteriaType', 'Audience Criteria Type')
                .setEditable()
                .addEnumValue('Custom List', 'CustomList')
                .addEnumValue('Max Days In Community', 'MaxDaysInCommunity')
            )
            .addField('audienceCriteriaValue', new StringXMLField('audienceCriteriaValue', 'Audience Criteria Value')
                .setEditable()
            )
            .addField('setupName', new StringXMLField('setupName', 'Setup Name')
                .setEditable()
            )
        ),
    recommendationDefinition: new ObjectXMLField('recommendationDefinition', 'Recommendation Definition')
        .setMinApi(41)
        .setEditable()
        .setFieldKey('recommendationDefinitionDetails')
        .setSortOrder(undefined)
        .addField('recommendationDefinitionDetails', new ArrayXMLField('recommendationDefinitionDetails', 'Recommendation Definition Details')
            .setEditable()
            .setFieldKey('title')
            .setSortOrder(undefined)
            .addField('actionUrl', new StringXMLField('actionUrl', 'Action URL')
                .setEditable()
            )
            .addField('description', new StringXMLField('description', 'Description')
                .setEditable()
            )
            .addField('linkText', new StringXMLField('linkText', 'Link Text')
                .setEditable()
            )
            .addField('scheduledRecommendations', new ObjectXMLField('scheduledRecommendations', 'Scheduled Recommendations')
                .setEditable()
                .setFieldKey('scheduledRecommendationDetails')
                .setSortOrder(undefined)
                .addField('scheduledRecommendationDetails', new ArrayXMLField('scheduledRecommendationDetails', 'Scheduled Recommendation Details')
                    .setEditable()
                    .setFieldKey('rank')
                    .setSortOrder(undefined)
                    .addField('channel', new EnumXMLField('channel', 'Channel')
                        .setEditable()
                        .addEnumValue('Default Channel', 'DefaultChannel')
                        .addEnumValue('Custom Channel 1', 'CustomChannel1')
                        .addEnumValue('Custom Channel 2', 'CustomChannel2')
                        .addEnumValue('Custom Channel 3', 'CustomChannel3')
                        .addEnumValue('Custom Channel 4', 'CustomChannel4')
                        .addEnumValue('Custom Channel 5', 'CustomChannel5')
                    )
                    .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
                        .setEditable()
                    )
                    .addField('rank', new IntegerXMLField('rank', 'Rank')
                        .setEditable()
                    )
                    .addField('recommendationAudience', new BooleanXMLField('recommendationAudience', 'Recommendation Audience')
                        .setEditable()
                    )
                )
            )
            .addField('setupName', new StringXMLField('setupName', 'Setup Name')
                .setEditable()
            )
            .addField('title', new StringXMLField('title', 'Title')
                .setEditable()
            )
        ),
    reputationLevels: new ObjectXMLField('reputationLevels', 'Reputation Levels')
        .setMinApi(28)
        .setEditable()
        .setFieldKey('level')
        .setSortOrder(undefined)
        .addField('level', new ArrayXMLField('level', 'Level')
            .setMinApi(32)
            .setEditable()
            .setFieldKey('label')
            .setSortOrder(undefined)
            .addField('branding', new ArrayXMLField('branding', 'Branding')
                .setEditable()
                .setFieldKey('smallImage')
                .setSortOrder(undefined)
                .addField('smallImage', new StringXMLField('smallImage', 'Small Image')
                    .setEditable()
                )
            )
            .addField('label', new StringXMLField('label', 'Label')
                .setEditable()
            )
            .addField('lowerThreshold', new DoubleXMLField('lowerThreshold', 'Lower Threshold')
                .setEditable()
                .setRequired()
                .setMinValue(1)
                .setMaxValue(50)
            )
        ),
    reputationPointsRules: new ObjectXMLField('reputationPointsRules', 'Reputation Points Rules')
        .setMinApi(28)
        .setEditable()
        .setFieldKey('pointsRule')
        .setSortOrder(undefined)
        .addField('pointsRule', new ArrayXMLField('pointsRule', 'Points Rule')
            .setEditable()
            .setFieldKey('points')
            .setSortOrder(undefined)
            .addField('eventType', new EnumXMLField('eventType', 'Event Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Feed Item Write A Post', 'FeedItemWriteAPost')
                .addEnumValue('Feed Item Write A Comment', 'FeedItemWriteAComment')
                .addEnumValue('Feed Item Receive A Comment', 'FeedItemReceiveAComment')
                .addEnumValue('Feed Item Like Something', 'FeedItemLikeSomething')
                .addEnumValue('Feed Item Receive A Like', 'FeedItemReceiveALike')
                .addEnumValue('Feed Item Mention Someone', 'FeedItemMentionSomeone')
                .addEnumValue('Feed Item Someone Mentions You', 'FeedItemSomeoneMentionsYou')
                .addEnumValue('Feed Item Share A Post', 'FeedItemShareAPost')
                .addEnumValue('Feed Item Someone Shares Your Post', 'FeedItemSomeoneSharesYourPost')
                .addEnumValue('Feed Item Post A Question', 'FeedItemPostAQuestion')
                .addEnumValue('Feed Item Answer A Question', 'FeedItemAnswerAQuestion')
                .addEnumValue('Feed Item Receive An Answer', 'FeedItemReceiveAnAnswer')
                .addEnumValue('Feed Item Mark Answer As Best', 'FeedItemMarkAnswerAsBest')
                .addEnumValue('Feed Item Your Answer Marked Best', 'FeedItemYourAnswerMarkedBest')
                .addEnumValue('Feed Item Endorse Someone For Knowledge On A Topic', 'FeedItemEndorseSomeoneForKnowledgeOnATopic')
                .addEnumValue('Feed Item Endorsed For KnowledgeOn A Topic', 'FeedItemEndorsedForKnowledgeOnATopic')
            )
            .addField('points', new IntegerXMLField('points', 'Points')
                .setEditable()
                .setRequired()
            )
        ),
    selfRegProfile: new StringXMLField('selfRegProfile', 'Self Registration Profile')
        .setMinApi(29)
        .setEditable()
        .addDependencyField(new XMLDependencyField('selfRegistration', true, DataValues.AVAILABLE)),
    selfRegistration: new BooleanXMLField('selfRegistration', 'Self Registration')
        .setMinApi(28)
        .setEditable(),
    sendWelcomeEmail: new BooleanXMLField('sendWelcomeEmail', 'Send Welcome Email')
        .setMinApi(28)
        .setEditable(),
    site: new StringXMLField('site', 'Site')
        .setMinApi(28)
        .setEditable()
        .setMetadataType(MetadataTypes.CUSTOM_SITE),
    status: new EnumXMLField('status', 'Status')
        .setMinApi(28)
        .setEditable()
        .setRequired()
        .addEnumValue('Live', 'Live')
        .addEnumValue('Down For Maintenance', 'DownForMaintenance')
        .addEnumValue('Under Construction', 'UnderConstruction'),
    tabs: new ObjectXMLField('tabs', 'Tabs')
        .setMinApi(28)
        .setEditable()
        .setFieldKey('defaultTab')
        .setSortOrder(undefined)
        .addField('customTab', new ArrayXMLField('customTab', 'Custom Tab')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_TAB)
        )
        .addField('defaultTab', new StringXMLField('defaultTab', 'Default Tab')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_TAB)
        )
        .addField('standardTab', new ArrayXMLField('standardTab', 'Standard Tab')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_TAB)
        ),
    urlPathPrefix: new StringXMLField('urlPathPrefix', 'URL Path Prefix')
        .setMinApi(28)
        .setEditable(),
    verificationTemplate: new StringXMLField('verificationTemplate', 'Verification Template')
        .setMinApi(44)
        .setEditable(),
    welcomeTemplate: new StringXMLField('welcomeTemplate', 'Welcome Template')
        .setMinApi(28)
        .setEditable()

}