import { StringXMLField, ArrayXMLField, IntegerXMLField, DoubleXMLField } from '@aurahelper/core';

export const OcrSampleDocument = {
    contentAsset: new StringXMLField('contentAsset', 'Content Asset')
        .setMinApi(52)
        .setEditable(),
    documentHeight: new DoubleXMLField('documentHeight', 'Document Height')
        .setMinApi(52)
        .setEditable(),
    documentType: new StringXMLField('documentType', 'Document Type')
        .setMinApi(52)
        .setEditable()
        .setRequired(),
    masterLabel: new StringXMLField('masterLabel', 'Master Label')
        .setMinApi(52)
        .setEditable()
        .setRequired(),
    ocrSampleDocumentFields: new ArrayXMLField('ocrSampleDocumentFields', 'OCR Sample Document Fields')
        .setMinApi(51)
        .setEditable()
        .addField('fieldLabelMaxX', new DoubleXMLField('fieldLabelMaxX', 'Field Label Max X')
            .setEditable()
        )
        .addField('fieldLabelMaxY', new DoubleXMLField('fieldLabelMaxY', 'Field Label Max Y')
            .setEditable()
        )
        .addField('fieldLabelMinX', new DoubleXMLField('fieldLabelMinX', 'Field Label Min X')
            .setEditable()
        )
        .addField('fieldLabelMinY', new DoubleXMLField('fieldLabelMinY', 'Field Label Min Y')
            .setEditable()
        )
        .addField('keyContent', new StringXMLField('keyContent', 'Key Content')
            .setEditable()
            .setRequired()
        )
        .addField('ocrSampleDocument', new StringXMLField('ocrSampleDocument', 'OCR Sample Document')
            .setEditable()
            .setRequired()
        )
        .addField('ocrSampleDocumentPage', new StringXMLField('ocrSampleDocumentPage', 'OCR Sample Document Page')
            .setEditable()
        ),
    ocrSampleDocumentPages: new ArrayXMLField('ocrSampleDocumentPages', 'OCR Sample Document Pages')
        .setMinApi(51)
        .setEditable()
        .addField('ocrSampleDocument', new StringXMLField('ocrSampleDocument', 'OCR Sample Document')
            .setEditable()
            .setRequired()
        )
        .addField('pageHeight', new DoubleXMLField('pageHeight', 'Page Height')
            .setEditable()
        )
        .addField('pageNumber', new IntegerXMLField('pageNumber', 'Page Number')
            .setEditable()
            .setRequired()
        )
}