import { StringXMLField, ArrayXMLField, IntegerXMLField, DoubleXMLField, BooleanXMLField } from '@aurahelper/core';

export const OcrTemplate = {
    active: new BooleanXMLField('active', 'Active')
        .setMinApi(52)
        .setEditable(),
    documentType: new StringXMLField('documentType', 'Document Type')
        .setMinApi(52)
        .setRequired()
        .setEditable(),
    masterLabel: new StringXMLField('masterLabel', 'Master Label')
        .setMinApi(52)
        .setRequired()
        .setEditable(),
    ocrTargetObjects: new ArrayXMLField('ocrTargetObjects', 'OCR Target Objects')
        .setMinApi(52)
        .setEditable()
        .setFieldKey('targetObject')
        .addField('ocrTargetObjectFieldMappings', new ArrayXMLField('ocrTargetObjectFieldMappings', 'OCR Target Object Field Mappings')
            .setRequired()
            .setEditable()
            .setFieldKey('targetField')
            .addField('ocrSampleDocField', new ArrayXMLField('ocrSampleDocField', 'OCR Sample Doc Field')
                .setRequired()
                .setEditable()
                .setFieldKey('ocrSampleDocument')
                .addField('fieldLabelMaxX', new DoubleXMLField('fieldLabelMaxX', 'Field Label Max X')
                    .setEditable()
                )
                .addField('fieldLabelMaxY', new DoubleXMLField('fieldLabelMaxY', 'Field Label Max Y')
                    .setEditable()
                )
                .addField('fieldLabelMinX', new DoubleXMLField('fieldLabelMinX', 'Field Label Min X')
                    .setEditable()
                )
                .addField('fieldLabelMinY', new DoubleXMLField('fieldLabelMinY', 'Field Label Min Y')
                    .setEditable()
                )
                .addField('keyContent', new StringXMLField('keyContent', 'Key Content')
                    .setEditable()
                    .setRequired()
                )
                .addField('ocrSampleDocument', new StringXMLField('ocrSampleDocument', 'OCR Sample Document')
                    .setEditable()
                    .setRequired()
                )
                .addField('ocrSampleDocumentPage', new StringXMLField('ocrSampleDocumentPage', 'OCR Sample Document Page')
                    .setEditable()
                )
            )
            .addField('targetField', new StringXMLField('targetField', 'Target Field')
                .setRequired()
                .setEditable()
            )
        )
        .addField('targetObject', new StringXMLField('targetObject', 'Target Object')
            .setRequired()
            .setEditable()
        ),
    ocrTemplateSampleDocuments: new ArrayXMLField('ocrTemplateSampleDocuments', 'OCR Template Sample Documents')
        .setMinApi(52)
        .setEditable()
        .setFieldKey('ocrSampleDocument')
        .addField('ocrSampleDocument', new StringXMLField('ocrSampleDocument', 'OCR Sample Document')
            .setEditable()
        ),
    pageCount: new StringXMLField('pageCount', 'Page Count')
        .setMinApi(52)
        .setEditable(),
    templateName: new StringXMLField('templateName', 'Template Name')
        .setMinApi(52)
        .setRequired()
        .setEditable(),
};