const { StringXMLField, ArrayXMLField, EnumXMLField, BooleanXMLField, XMLDataControlledField } = require('@ah/core').Types;
const { MetadataTypes } = require('@ah/core').Values;

module.exports = {
    apiAccessLevel: new EnumXMLField('apiAccessLevel', 'API Access Level')
        .setMinApi(10)
        .setEditable()
        .addEnumValue('Unrestricted', 'Unrestricted')
        .addEnumValue('Restricted', 'Restricted'),
    description: new StringXMLField('description', 'Description')
        .setMinApi(10)
        .setEditable(),
    fullName: new StringXMLField('fullName', 'Full Name')
        .setMinApi(10)
        .setEditable()
        .setRequired()
        .setUnique(),
    namespacePrefix: new StringXMLField('namespacePrefix', 'Namespace Prefix')
        .setMinApi(10)
        .setEditable(),
    objectPermissions: new ArrayXMLField('objectPermissions', 'Object Permissions')
        .setMinApi(10)
        .setEditable()
        .setMergeable()
        .setFieldKey('object')
        .addField('allowRead', new BooleanXMLField('allowRead', 'Allow Read')
            .setEditable()
            .setDefaultValue(true)
            .addControlledField(new XMLDataControlledField('allowCreate', false, false))
            .addControlledField(new XMLDataControlledField('allowEdit', false, false))
            .addControlledField(new XMLDataControlledField('allowDelete', false, false))
            .addControlledField(new XMLDataControlledField('viewAllRecords', false, false))
            .addControlledField(new XMLDataControlledField('modifyAllRecords', false, false))
        )
        .addField('allowCreate', new BooleanXMLField('allowCreate', 'Allow Create')
            .setEditable()
            .setDefaultValue(true)
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
        )
        .addField('allowEdit', new BooleanXMLField('allowEdit', 'Allow Edit')
            .setEditable()
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
            .addControlledField(new XMLDataControlledField('allowDelete', false, false))
            .addControlledField(new XMLDataControlledField('modifyAllRecords', false, false))
        )
        .addField('allowDelete', new BooleanXMLField('allowDelete', 'Allow Delete')
            .setEditable()
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
            .addControlledField(new XMLDataControlledField('allowEdit', true, true))
            .addControlledField(new XMLDataControlledField('modifyAllRecords', false, false))
        )
        .addField('object', new StringXMLField('object', 'Object')
            .setUnique()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('viewAllRecords', new BooleanXMLField('viewAllRecords', 'View All Records')
            .setEditable()
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
            .addControlledField(new XMLDataControlledField('modifyAllRecords', false, false))
        )
        .addField('modifyAllRecords', new BooleanXMLField('modifyAllRecords', 'Modify All Records')
            .setEditable()
            .addControlledField(new XMLDataControlledField('allowRead', true, true))
            .addControlledField(new XMLDataControlledField('allowEdit', true, true))
            .addControlledField(new XMLDataControlledField('allowDelete', true, true))
            .addControlledField(new XMLDataControlledField('viewAllRecords', true, true))
        ),
    packageType: new StringXMLField('packageType', 'Package Type')
        .setMinApi(10)
        .setEditable()
        .setReserved(),
    postInstallClass: new StringXMLField('postInstallClass', 'Post Install Class')
        .setMinApi(24)
        .setEditable()
        .setMetadataType(MetadataTypes.APEX_CLASS),
    setupWeblink: new StringXMLField('setupWeblink', 'Setup Weblink')
        .setMinApi(10)
        .setEditable()
        .setMetadataType(MetadataTypes.WEBLINK),
    types: new ArrayXMLField('types', 'Types')
        .setMinApi(10)
        .setEditable()
        .addField('members', new ArrayXMLField('members', 'Members')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
        ),
    uninstallClass: new StringXMLField('uninstallClass', 'Uninstall Class')
        .setMinApi(25)
        .setEditable()
        .setMetadataType(MetadataTypes.APEX_CLASS),
    version: new StringXMLField('version', 'Version')
        .setMinApi(10)
        .setEditable()
        .setRequired()

}