const { StringXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField, EnumXMLField, BooleanXMLField, DateTimeXMLField, XMLDependencyField } = require('../factory/xmlFactory');
const MetadataTypes = require('../values/metadataTypes');
const DataValues = require('../values/dataValues');

module.exports = {
    masterLabel: new StringXMLField('masterLabel', 'Master Label')
        .setMinApi(46)
        .setEditable()
        .setRequired()
        .setMaxLength(80),
    promptVersions: new ArrayXMLField('promptVersions', 'Prompt Versions')
        .setMinApi(46)
        .setEditable()
        .addField('actionButtonLabel', new StringXMLField('actionButtonLabel', 'Action Button Label')
            .setEditable()
            .setMaxLength(25)
        )
        .addField('actionButtonLink', new StringXMLField('actionButtonLink', 'Action Button Link')
            .setEditable()
            .setMaxLength(1000)
        )
        .addField('body', new StringXMLField('body', 'Body')
            .setEditable()
            .setRequired()
            .setMaxLength(4000)
        )
        .addField('delayDays', new IntegerXMLField('delayDays', 'Delay Days')
            .setEditable()
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
            .setMaxLength(255)
        )
        .addField('dismissButtonLabel', new StringXMLField('dismissButtonLabel', 'Dismiss Button Label')
            .setEditable()
            .setMaxLength(15)
        )
        .addField('displayPosition', new EnumXMLField('displayPosition', 'Display Position')
            .setEditable()
            .addEnumValue('Bottom Center', 'BottomCenter')
            .addEnumValue('Bottom Left', 'BottomLeft')
            .addEnumValue('Bottom Right', 'BottomRight')
            .addEnumValue('Top Center', 'TopCenter')
            .addEnumValue('Top Left', 'TopLeft')
            .addEnumValue('Top Right', 'TopRight')
        )
        .addField('displayPosition', new EnumXMLField('displayPosition', 'Display Position')
            .setEditable()
            .setRequired()
            .addEnumValue('Docked Composer', 'DockedComposer')
            .addEnumValue('Floating Panel', 'FloatingPanel')
        )
        .addField('endDate', new DateTimeXMLField('endDate', 'End Date')
            .setEditable()
            .setFormat('yyyy-mm-dd')
        )
        .addField('header', new StringXMLField('header', 'Header')
            .setEditable()
            .setMaxLength(36)
        )
        .addField('image', new StringXMLField('image', 'Image')
            .setEditable()
            .setMetadataType(MetadataTypes.CONTENT_ASSET)
        )
        .addField('imageAltText', new StringXMLField('imageAltText', 'Image Alternative Text')
            .setEditable()
            .setMetadataType(MetadataTypes.CONTENT_ASSET)
            .addDependencyField(new XMLDependencyField('imageLocation', DataValues.NOT_NULL, DataValues.NOT_NULL))
            .addDependencyField(new XMLDependencyField('image', DataValues.NOT_NULL, DataValues.NOT_NULL))
        )
        .addField('imageLocation', new EnumXMLField('imageLocation', 'Image Location')
            .setEditable()
            .setRequired()
            .addEnumValue('Top', 'Top')
            .addEnumValue('Bottom', 'Bottom')
            .addEnumValue('Right', 'Right')
            .addEnumValue('Left', 'Left')
        )
        .addField('indexWithIsPublished', new StringXMLField('indexWithIsPublished', 'Index With Is Published')
            .setEditable()
        )
        .addField('indexWithoutIsPublished', new StringXMLField('indexWithoutIsPublished', 'Index Without Is Published')
            .setEditable()
        )
        .addField('isPublished', new BooleanXMLField('isPublished', 'Is Published')
            .setEditable()
        )
        .addField('masterLabel', new StringXMLField('masterLabel', 'Master Label')
            .setEditable()
            .setRequired()
        )
        .addField('publishedDate', new DateTimeXMLField('publishedDate', 'Published Date')
            .setEditable()
            .setFormat('yyyy-mm-dd')
        )
        .addField('shouldDisplayActionButton', new BooleanXMLField('shouldDisplayActionButton', 'Should Display Action Button')
            .setEditable()
        )
        .addField('shouldIgnoreGlobalDelay', new BooleanXMLField('shouldIgnoreGlobalDelay', 'Should Ignore Global Delay')
            .setMinApi(48)
            .setEditable()
        )
        .addField('startDate', new DateTimeXMLField('startDate', 'Start Date')
            .setMinApi(48)
            .setEditable()
            .setFormat('yyyy-mm-dd')
        )
        .addField('stepNumber', new IntegerXMLField('stepNumber', 'Step Number')
            .setMinApi(49)
            .setEditable()
            .setMinValue(1)
            .setMaxValue(10)
        )
        .addField('targetAppDeveloperName', new StringXMLField('targetAppDeveloperName', 'Target App Developer Name')
            .setMaxApi(50)
            .setEditable()
        )
        .addField('targetAppNamespacePrefix', new StringXMLField('targetAppNamespacePrefix', 'Target App Namespace Prefix')
            .setMaxApi(50)
            .setEditable()
            .setMaxLength(15)
        )
        .addField('targetPageKey1', new StringXMLField('targetPageKey1', 'Target Page Key 1')
            .setEditable()
        )
        .addField('targetPageKey2', new StringXMLField('targetPageKey2', 'Target Page Key 2')
            .setEditable()
        )
        .addField('targetPageType', new StringXMLField('targetPageType', 'Target Page Type')
            .setRequired()
            .setEditable()
        )
        .addField('themeColor', new EnumXMLField('themeColor', 'Theme Color')
            .setEditable()
            .addEnumValue('Theme 1', 'Theme1')
            .addEnumValue('Theme 2', 'Theme2')
            .addEnumValue('Theme 3', 'Theme3')
            .addEnumValue('Theme 4', 'Theme4')
        )
        .addField('themeSaturation', new EnumXMLField('themeSaturation', 'Theme Saturation')
            .setEditable()
            .addEnumValue('Dark', 'Dark')
            .addEnumValue('Light', 'Light')
        )
        .addField('timesToDisplay', new IntegerXMLField('timesToDisplay', 'Times To Display')
            .setEditable()
            .setMinValue(1)
            .setMaxValue(30)
        )
        .addField('title', new StringXMLField('title', 'Title')
            .setEditable()
            .setMaxLength(36)
        )
        .addField('uiFormulaRule', new ObjectXMLField('uiFormulaRule', 'UI Formula Rule')
            .setEditable()
            .addField('booleanFilter', new StringXMLField('booleanFilter', 'Boolean Filter')
                .setEditable()
            )
            .addField('criteria', new ArrayXMLField('criteria', 'Criteria')
                .setEditable()
                .addField('leftValue', new StringXMLField('leftValue', 'Left Value')
                    .setEditable()
                    .setRequired()
                )
                .addField('operator', new EnumXMLField('operator', 'Operator')
                    .setEditable()
                    .setRequired()
                    .setDefaultValue('EQUAL')
                    .addEnumValue('Equal', 'EQUAL')
                )
                .addField('rightValue', new StringXMLField('rightValue', 'Right Value')
                    .setEditable()
                )
            )
        )
        .addField('userAccess', new EnumXMLField('userAccess', 'User Access')
            .setEditable()
            .addEnumValue('Everyone', 'Everyone')
            .addEnumValue('Specific Permissions', 'SpecificPermissions')
            .addDependencyField(new XMLDependencyField(DataValues.API_VALUE, [46, 47, 48], DataValues.NOT_NULL))
        )
        .addField('versionNumber', new IntegerXMLField('versionNumber', 'Version Number')
            .setEditable()
            .setRequired()
        )
        .addField('videoLink', new StringXMLField('videoLink', 'Video Link')
            .setMinApi(48)
            .setEditable()
            .setMaxLength(1000)
        )

}