const { StringXMLField, ArrayXMLField, BooleanXMLField } = require('@ah/core').Types;
const { MetadataTypes } = require('@ah/core').Values;

module.exports = {
    doesSendEmailToMembers: new BooleanXMLField('doesSendEmailToMembers', 'Does Send Email To Members')
        .setMinApi(24)
        .setEditable(),
    email: new StringXMLField('email', 'Email')
        .setMinApi(24)
        .setEditable(),
    name: new StringXMLField('name', 'Name')
        .setMinApi(24)
        .setEditable()
        .setRequired(),
    queueMembers: new ArrayXMLField('queueMembers', 'Queue Members')
        .setMinApi(42)
        .setEditable()
        .addField('publicGroups', new ArrayXMLField('publicGroups', 'Public Groups')
            .setEditable()
            .addField('publicGroup', new StringXMLField('publicGroup', 'Public Group')
                .setEditable()
                .setMetadataType(MetadataTypes.GROUP)
            )
        )
        .addField('roleAndSubordinates', new ArrayXMLField('roleAndSubordinates', 'Role And Subordinates')
            .setEditable()
            .addField('roleAndSubordinate', new StringXMLField('roleAndSubordinate', 'Role And Subordinate')
                .setEditable()
                .setMetadataType(MetadataTypes.ROLE)
            )
        )
        .addField('roleAndSubordinatesInternal', new ArrayXMLField('roleAndSubordinatesInternal', 'Role And Subordinates Internal')
            .setEditable()
            .addField('roleAndSubordinateInternal', new StringXMLField('roleAndSubordinateInternal', 'Role And Subordinate Internal')
                .setEditable()
                .setMetadataType(MetadataTypes.ROLE)
            )
        )
        .addField('roles', new ArrayXMLField('roles', 'Roles')
            .setEditable()
            .addField('role', new StringXMLField('role', 'Role')
                .setEditable()
                .setMetadataType(MetadataTypes.ROLE)
            )
        )
        .addField('users', new ArrayXMLField('users', 'Users')
            .setEditable()
            .addField('user', new StringXMLField('user', 'User')
                .setEditable()
                .linkFieldToSObject('User', 'Username')
            )
        ),
    queueRoutingConfig: new StringXMLField('queueRoutingConfig', 'Queue Routing Config')
        .setMinApi(24)
        .setEditable()
        .setMetadataType(MetadataTypes.QUEUE_ROUTING_CONFIG),
    queueSobject: new ArrayXMLField('queueSobject', 'Queue SObject')
        .setMinApi(24)
        .setEditable()
        .addField('sobjectType', new StringXMLField('sobjectType', 'SObject Type')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
}