import { StringXMLField, BooleanXMLField, ArrayXMLField, MetadataTypes, ObjectXMLField } from '@aurahelper/core';

export const Queue = {
    doesSendEmailToMembers: new BooleanXMLField('doesSendEmailToMembers', 'Does Send Email To Members')
        .setMinApi(24)
        .setEditable(),
    email: new StringXMLField('email', 'Email')
        .setMinApi(24)
        .setEditable(),
    name: new StringXMLField('name', 'Name')
        .setMinApi(24)
        .setEditable()
        .setRequired(),
    queueMembers: new ArrayXMLField('queueMembers', 'Queue Members')
        .setMinApi(42)
        .setEditable()
        .setFieldKey('users')
        .setSortOrder(undefined)
        .addField('publicGroups', new ObjectXMLField('publicGroups', 'Public Groups')
            .setEditable()
            .setFieldKey('publicGroup')
            .setSortOrder(undefined)
            .addField('publicGroup', new ArrayXMLField('publicGroup', 'Public Group')
                .setEditable()
                .setMetadataType(MetadataTypes.GROUP)
            )
        )
        .addField('roleAndSubordinates', new ObjectXMLField('roleAndSubordinates', 'Role And Subordinates')
            .setEditable()
            .setFieldKey('roleAndSubordinate')
            .setSortOrder(undefined)
            .addField('roleAndSubordinate', new ArrayXMLField('roleAndSubordinate', 'Role And Subordinate')
                .setEditable()
                .setMetadataType(MetadataTypes.ROLE)
            )
        )
        .addField('roleAndSubordinatesInternal', new ObjectXMLField('roleAndSubordinatesInternal', 'Role And Subordinates Internal')
            .setEditable()
            .setFieldKey('roleAndSubordinateInternal')
            .setSortOrder(undefined)
            .addField('roleAndSubordinateInternal', new ArrayXMLField('roleAndSubordinateInternal', 'Role And Subordinate Internal')
                .setEditable()
                .setMetadataType(MetadataTypes.ROLE)
            )
        )
        .addField('roles', new ObjectXMLField('roles', 'Roles')
            .setEditable()
            .setFieldKey('role')
            .setSortOrder(undefined)
            .addField('role', new ArrayXMLField('role', 'Role')
                .setEditable()
                .setMetadataType(MetadataTypes.ROLE)
            )
        )
        .addField('users', new ObjectXMLField('users', 'Users')
            .setEditable()
            .setFieldKey('user')
            .setSortOrder(undefined)
            .addField('user', new ArrayXMLField('user', 'User')
                .setEditable()
                .linkFieldToSObject('User', 'Username')
            )
        ),
    queueRoutingConfig: new StringXMLField('queueRoutingConfig', 'Queue Routing Config')
        .setMinApi(24)
        .setEditable()
        .setMetadataType(MetadataTypes.QUEUE_ROUTING_CONFIG),
    queueSobject: new ArrayXMLField('queueSobject', 'Queue SObject')
        .setMinApi(24)
        .setEditable()
        .setFieldKey('sobjectType')
        .addField('sobjectType', new StringXMLField('sobjectType', 'SObject Type')
            .setEditable()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
}