const { StringXMLField, ObjectXMLField, ArrayXMLField, EnumXMLField, BooleanXMLField } = require('@ah/core').Types;
const { MetadataTypes } = require('@ah/core').Values;

module.exports = {
    actionContext: new ArrayXMLField('actionContext', 'Action Context')
        .setMinApi(45)
        .setEditable()
        .setFieldKey('name')
        .addField('action', new StringXMLField('action', 'Action')
            .setEditable()
            .setRequired()
        )
        .addField('argument', new ArrayXMLField('argument', 'Argument')
            .setEditable()
            .setFieldKey('name')
            .setSortOrder(undefined)
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
            .addField('value', new StringXMLField('value', 'Value')
                .setEditable()
                .setRequired()
            )
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Activate Session Permission Set', 'activateSessionPermSet')
            .addEnumValue('Add Message To Chat', 'addMessageToChat', 49)
            .addEnumValue('Add Message To Quip Chat', 'addMessageToQuipChat', 46)
            .addEnumValue('Add Message To Quip Document', 'addMessageToQuipDocument', 46)
            .addEnumValue('Add Quip Document To Folder', 'addQuipDocumentToFolder', 46)
            .addEnumValue('Add Users To Chat', 'addUsersToChat', 49)
            .addEnumValue('Add Users To Quip Document', 'addUsersToQuipDocument', 46)
            .addEnumValue('Add Users To Quip Chat', 'addUsersToQuipChat', 46)
            .addEnumValue('Attach Quip Document To Record', 'attachQuipDocumentToRecord', 46)
            .addEnumValue('Apex', 'apex')
            .addEnumValue('Archive Knowledge Articles', 'archiveKnowledgeArticles', 45)
            .addEnumValue('Assign Knowledge Articles', 'assignKnowledgeArticles', 44)
            .addEnumValue('Cancel Cart Async Operation', 'cancelCartAsyncOperation', 49)
            .addEnumValue('Chat', 'chat', 49)
            .addEnumValue('Chatter Post', 'chatterPost', 49)
            .addEnumValue('Checkout Session Action', 'checkoutSessionAction', 49)
            .addEnumValue('Choose Price book', 'choosePricebook')
            .addEnumValue('Contact Request Action', 'contactRequestAction', 45)
            .addEnumValue('Component', 'component', 43)
            .addEnumValue('Content Workspace Enable Folders', 'contentWorkspaceEnableFolders')
            .addEnumValue('Copy Quip Document', 'copyQuipDocument', 46)
            .addEnumValue('Create Draft From Online Knowledge Article', 'createDraftFromOnlineKnowledgeArticle', 45)
            .addEnumValue('Create Invoice From Fulfillment Order', 'createInvoiceFromFulfillmentOrder', 49)
            .addEnumValue('Create Quip Chat', 'createQuipChat', 46)
            .addEnumValue('Create Quip Document', 'createQuipDocument', 46)
            .addEnumValue('Create Quip Folder', 'createQuipFolder', 46)
            .addEnumValue('Custom Notification Action', 'customNotificationAction', 46)
            .addEnumValue('Deactivate Session Permission Set', 'deactivateSessionPermSet')
            .addEnumValue('Decision Studio Action', 'decisionStudioAction', 49)
            .addEnumValue('Delete Knowledge Article', 'deleteKnowledgeArticle', 46)
            .addEnumValue('Edit Quip Document', 'editQuipDocument', 46)
            .addEnumValue('Email Alert', 'emailAlert')
            .addEnumValue('Email Simple', 'emailSimple')
            .addEnumValue('External Service', 'externalService', 46)
            .addEnumValue('Flow', 'flow', 32)
            .addEnumValue('Marketing Email', 'marketingEmail', 49)
            .addEnumValue('Mass Update Account Forecast', 'massUpdateAccountForecast', 48)
            .addEnumValue('Mass Update Sales Agreement', 'massUpdateSalesAgreement', 48)
            .addEnumValue('Price Cart', 'priceCart', 47)
            .addEnumValue('Quick Action', 'quickAction')
            .addEnumValue('Publish Knowledge Articles', 'publishKnowledgeArticles', 44)
            .addEnumValue('Publish Pardot Content', 'publishPardotContent', 49)
            .addEnumValue('Restore Knowledge Article Version', 'restoreKnowledgeArticleVersion', 45)
            .addEnumValue('Send Alert', 'sendAlert', 49)
            .addEnumValue('Send Survey Invitation', 'sendSurveyInvitation', 49)
            .addEnumValue('Store Reply Recommendations Feedback', 'storeReplyRecommendationsFeedback', 49)
            .addEnumValue('Submit Knowledge Article For Translation', 'submitKnowledgeArticleForTranslation', 46)
            .addEnumValue('Submit', 'submit')
            .addEnumValue('Update Checkout Session State Action', 'updateCheckoutSessionStateAction', 49)
            .addEnumValue('Adjust Order Item Summaries Preview', 'adjustOrderItemSummariesPreview', 49)
            .addEnumValue('Adjust Order Item Summaries Submit', 'adjustOrderItemSummariesSubmit', 49)
            .addEnumValue('Cancel Fulfillment Order Item', 'cancelFulfillmentOrderItem', 48)
            .addEnumValue('Cancel Order Item Summaries Preview', 'cancelOrderItemSummariesPreview', 48)
            .addEnumValue('Cancel Order Item Summaries Submit', 'cancelOrderItemSummariesSubmit', 48)
            .addEnumValue('Create Credit Memo Order Summary', 'createCreditMemoOrderSummary', 48)
            .addEnumValue('Create Fulfillment Order', 'createFulfillmentOrder', 48)
            .addEnumValue('Create Invoice From Fulfillment Order', 'createInvoiceFromFulfillmentOrder', 48)
            .addEnumValue('Create Order Payment Summary', 'createOrderPaymentSummary', 48)
            .addEnumValue('Create Order Summary', 'createOrderSummary', 48)
            .addEnumValue('Ensure Funds Order Summary Async', 'ensureFundsOrderSummaryAsync', 48)
            .addEnumValue('Ensure Refunds Order Summary Async', 'ensureRefundsOrderSummaryAsync', 48)
            .addEnumValue('Return Order Item Summaries Preview', 'returnOrderItemSummariesPreview', 48)
            .addEnumValue('Return Order Item Summaries Submit', 'returnOrderItemSummariesSubmit', 48)
            .addEnumValue('Store Reply Recommendations Feedback', 'storeReplyRecommendationsFeedback', 49)
            .addEnumValue('Store Reply Recommendations Feedback', 'storeReplyRecommendationsFeedback', 49)
            .addEnumValue('Create Financial Records', 'createFinancialRecords', 49)
            .addEnumValue('Add Rebate Member List', 'addRebateMemberList', 51)
            .addEnumValue('Calculate Rebate Amount And Upsert Payout', 'calculateRebateAmountAndUpsertPayout', 51)
            .addEnumValue('Get Benefit And Calculate Rebate Amount', 'getBenefitAndCalculateRebateAmount', 51)
            .addEnumValue('Generate Rebate Payout Periods', 'generateRebatePayoutPeriods', 51)
            .addEnumValue('Process Rebates Batch Calculation Job', 'processRebatesBatchCalculationJob', 51)
            .addEnumValue('Rebates Process CSV', 'rebatesProcessCSV', 51)
            .addEnumValue('Upsert Custom Rebate Payout', 'upsertCustomRebatePayout', 51)
            .addEnumValue('Adjust Points', 'adjustPoints', 51)
            .addEnumValue('Assign Tier Benefits', 'assignTierBenefits', 51)
            .addEnumValue('Cancel Accrual', 'cancelAccrual')
            .addEnumValue('Credit Points', 'creditPoints', 51)
            .addEnumValue('Cancel Redemption', 'cancelRedemption', 51)
            .addEnumValue('Change Tier', 'changeTier', 51)
            .addEnumValue('Change Tier When No Errors', 'changeTierWhenNoErrors', 51)
            .addEnumValue('Debit Points', 'debitPoints', 51)
            .addEnumValue('Execute Member Benefit', 'executeMemberBenefit', 51)
            .addEnumValue('Get Tier', 'getTier', 51)
            .addEnumValue('Get Points Balance', 'getPointsBalance', 51)
            .addEnumValue('Issue Voucher', 'issueVoucher', 51)
            .addEnumValue('Decision Table Action', 'decisionTableAction', 51)
            .addEnumValue('Refresh Decision Table', 'refreshDecisionTable', 51)
            .addEnumValue('Batch Job Action', 'batchJobAction', 51)
            .addEnumValue('Data Processing Engine Action', 'dataProcessingEngineAction', 51)
        ),
    contextRecordType: new StringXMLField('contextRecordType', 'Context Record Type')
        .setMinApi(45)
        .setEditable()
        .setMetadataType(MetadataTypes.CUSTOM_OBJECT),
    description: new StringXMLField('description', 'Description')
        .setMinApi(45)
        .setEditable(),
    filter: new ArrayXMLField('filter', 'Filter')
        .setMinApi(45)
        .setEditable()
        .setFieldKey('expression')
        .setSortOrder(undefined)
        .addField('expression', new StringXMLField('expression', 'Expression')
            .setEditable()
            .setRequired()
        ),
    if: new ArrayXMLField('if', 'If')
        .setMinApi(45)
        .setEditable()
        .setFieldKey('childNodeExpression')
        .setSortOrder(undefined)
        .addField('childNodeExpression', new ArrayXMLField('childNodeExpression', 'Child Node Expression')
            .setEditable()
            .setFieldKey('childName')
            .setSortOrder(undefined)
            .addField('childName', new StringXMLField('childName', 'Child Name')
                .setEditable()
                .setRequired()
            )
            .addField('expression', new StringXMLField('expression', 'Expression')
                .setEditable()
                .setRequired()
            )
        )
        .addField('onlyFirstMatch', new BooleanXMLField('onlyFirstMatch', 'Only First Match')
            .setEditable()
        ),
    invocableAction: new ArrayXMLField('invocableAction', 'Invocable Action')
        .setMinApi(46)
        .setEditable()
        .setFieldKey('action')
        .setSortOrder(undefined)
        .addField('action', new StringXMLField('action', 'Action')
            .setEditable()
            .setRequired()
        )
        .addField('argument', new ArrayXMLField('argument', 'Argument')
            .setFieldKey('name')
            .setSortOrder(undefined)
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
            .addField('value', new StringXMLField('value', 'Value')
                .setEditable()
                .setRequired()
            )
        )
        .addField('isGenerator', new BooleanXMLField('isGenerator', 'Is Generator')
            .setEditable()
            .setRequired()
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Activate Session Permission Set', 'activateSessionPermSet')
            .addEnumValue('Add Message To Chat', 'addMessageToChat', 49)
            .addEnumValue('Add Message To Quip Chat', 'addMessageToQuipChat', 46)
            .addEnumValue('Add Message To Quip Document', 'addMessageToQuipDocument', 46)
            .addEnumValue('Add Quip Document To Folder', 'addQuipDocumentToFolder', 46)
            .addEnumValue('Add Users To Chat', 'addUsersToChat', 49)
            .addEnumValue('Add Users To Quip Document', 'addUsersToQuipDocument', 46)
            .addEnumValue('Add Users To Quip Chat', 'addUsersToQuipChat', 46)
            .addEnumValue('Attach Quip Document To Record', 'attachQuipDocumentToRecord', 46)
            .addEnumValue('Apex', 'apex')
            .addEnumValue('Archive Knowledge Articles', 'archiveKnowledgeArticles', 45)
            .addEnumValue('Assign Knowledge Articles', 'assignKnowledgeArticles', 44)
            .addEnumValue('Cancel Cart Async Operation', 'cancelCartAsyncOperation', 49)
            .addEnumValue('Chat', 'chat', 49)
            .addEnumValue('Chatter Post', 'chatterPost', 49)
            .addEnumValue('Checkout Session Action', 'checkoutSessionAction', 49)
            .addEnumValue('Choose Price book', 'choosePricebook')
            .addEnumValue('Contact Request Action', 'contactRequestAction', 45)
            .addEnumValue('Component', 'component', 43)
            .addEnumValue('Content Workspace Enable Folders', 'contentWorkspaceEnableFolders')
            .addEnumValue('Copy Quip Document', 'copyQuipDocument', 46)
            .addEnumValue('Create Draft From Online Knowledge Article', 'createDraftFromOnlineKnowledgeArticle', 45)
            .addEnumValue('Create Invoice From Fulfillment Order', 'createInvoiceFromFulfillmentOrder', 49)
            .addEnumValue('Create Quip Chat', 'createQuipChat', 46)
            .addEnumValue('Create Quip Document', 'createQuipDocument', 46)
            .addEnumValue('Create Quip Folder', 'createQuipFolder', 46)
            .addEnumValue('Custom Notification Action', 'customNotificationAction', 46)
            .addEnumValue('Deactivate Session Permission Set', 'deactivateSessionPermSet')
            .addEnumValue('Decision Studio Action', 'decisionStudioAction', 49)
            .addEnumValue('Delete Knowledge Article', 'deleteKnowledgeArticle', 46)
            .addEnumValue('Edit Quip Document', 'editQuipDocument', 46)
            .addEnumValue('Email Alert', 'emailAlert')
            .addEnumValue('Email Simple', 'emailSimple')
            .addEnumValue('External Service', 'externalService', 46)
            .addEnumValue('Flow', 'flow', 32)
            .addEnumValue('Marketing Email', 'marketingEmail', 49)
            .addEnumValue('Mass Update Account Forecast', 'massUpdateAccountForecast', 48)
            .addEnumValue('Mass Update Sales Agreement', 'massUpdateSalesAgreement', 48)
            .addEnumValue('Price Cart', 'priceCart', 47)
            .addEnumValue('Quick Action', 'quickAction')
            .addEnumValue('Publish Knowledge Articles', 'publishKnowledgeArticles', 44)
            .addEnumValue('Publish Pardot Content', 'publishPardotContent', 49)
            .addEnumValue('Restore Knowledge Article Version', 'restoreKnowledgeArticleVersion', 45)
            .addEnumValue('Send Alert', 'sendAlert', 49)
            .addEnumValue('Send Survey Invitation', 'sendSurveyInvitation', 49)
            .addEnumValue('Store Reply Recommendations Feedback', 'storeReplyRecommendationsFeedback', 49)
            .addEnumValue('Submit Knowledge Article For Translation', 'submitKnowledgeArticleForTranslation', 46)
            .addEnumValue('Submit', 'submit')
            .addEnumValue('Update Checkout Session State Action', 'updateCheckoutSessionStateAction', 49)
            .addEnumValue('Adjust Order Item Summaries Preview', 'adjustOrderItemSummariesPreview', 49)
            .addEnumValue('Adjust Order Item Summaries Submit', 'adjustOrderItemSummariesSubmit', 49)
            .addEnumValue('Cancel Fulfillment Order Item', 'cancelFulfillmentOrderItem', 48)
            .addEnumValue('Cancel Order Item Summaries Preview', 'cancelOrderItemSummariesPreview', 48)
            .addEnumValue('Cancel Order Item Summaries Submit', 'cancelOrderItemSummariesSubmit', 48)
            .addEnumValue('Create Credit Memo Order Summary', 'createCreditMemoOrderSummary', 48)
            .addEnumValue('Create Fulfillment Order', 'createFulfillmentOrder', 48)
            .addEnumValue('Create Invoice From Fulfillment Order', 'createInvoiceFromFulfillmentOrder', 48)
            .addEnumValue('Create Order Payment Summary', 'createOrderPaymentSummary', 48)
            .addEnumValue('Create Order Summary', 'createOrderSummary', 48)
            .addEnumValue('Ensure Funds Order Summary Async', 'ensureFundsOrderSummaryAsync', 48)
            .addEnumValue('Ensure Refunds Order Summary Async', 'ensureRefundsOrderSummaryAsync', 48)
            .addEnumValue('Return Order Item Summaries Preview', 'returnOrderItemSummariesPreview', 48)
            .addEnumValue('Return Order Item Summaries Submit', 'returnOrderItemSummariesSubmit', 48)
            .addEnumValue('Store Reply Recommendations Feedback', 'storeReplyRecommendationsFeedback', 49)
            .addEnumValue('Store Reply Recommendations Feedback', 'storeReplyRecommendationsFeedback', 49)
            .addEnumValue('Create Financial Records', 'createFinancialRecords', 49)
            .addEnumValue('Add Rebate Member List', 'addRebateMemberList', 51)
            .addEnumValue('Calculate Rebate Amount And Upsert Payout', 'calculateRebateAmountAndUpsertPayout', 51)
            .addEnumValue('Get Benefit And Calculate Rebate Amount', 'getBenefitAndCalculateRebateAmount', 51)
            .addEnumValue('Generate Rebate Payout Periods', 'generateRebatePayoutPeriods', 51)
            .addEnumValue('Process Rebates Batch Calculation Job', 'processRebatesBatchCalculationJob', 51)
            .addEnumValue('Rebates Process CSV', 'rebatesProcessCSV', 51)
            .addEnumValue('Upsert Custom Rebate Payout', 'upsertCustomRebatePayout', 51)
            .addEnumValue('Adjust Points', 'adjustPoints', 51)
            .addEnumValue('Assign Tier Benefits', 'assignTierBenefits', 51)
            .addEnumValue('Cancel Accrual', 'cancelAccrual')
            .addEnumValue('Credit Points', 'creditPoints', 51)
            .addEnumValue('Cancel Redemption', 'cancelRedemption', 51)
            .addEnumValue('Change Tier', 'changeTier', 51)
            .addEnumValue('Change Tier When No Errors', 'changeTierWhenNoErrors', 51)
            .addEnumValue('Debit Points', 'debitPoints', 51)
            .addEnumValue('Execute Member Benefit', 'executeMemberBenefit', 51)
            .addEnumValue('Get Tier', 'getTier', 51)
            .addEnumValue('Get Points Balance', 'getPointsBalance', 51)
            .addEnumValue('Issue Voucher', 'issueVoucher', 51)
            .addEnumValue('Decision Table Action', 'decisionTableAction', 51)
            .addEnumValue('Refresh Decision Table', 'refreshDecisionTable', 51)
            .addEnumValue('Batch Job Action', 'batchJobAction', 51)
            .addEnumValue('Data Processing Engine Action', 'dataProcessingEngineAction', 51)
        ),
    isTemplate: new BooleanXMLField('isTemplate', 'Is Template')
        .setMinApi(47)
        .setEditable(),
    label: new StringXMLField('label', 'Label')
        .setMinApi(45)
        .setEditable()
        .setRequired(),
    map: new ArrayXMLField('map', 'Map')
        .setMinApi(46)
        .setEditable()
        .setFieldKey('mapExpression')
        .setSortOrder(undefined)
        .addField('mapExpression', new ArrayXMLField('mapExpression', 'Map Expression')
            .setEditable()
            .setFieldKey('name')
            .addField('expression', new StringXMLField('expression', 'Expression')
                .setEditable()
                .setRequired()
            )
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
            .addField('type', new EnumXMLField('type', 'Type')
                .setEditable()
                .setRequired()
                .addEnumValue('Boolean', 'BOOLEAN')
                .addEnumValue('Currency', 'CURRENCY')
                .addEnumValue('Date', 'DATE')
                .addEnumValue('Double', 'DOUBLE')
                .addEnumValue('Date Time', 'DATE_TIME')
                .addEnumValue('Integer', 'INTEGER')
                .addEnumValue('Long', 'LONG')
                .addEnumValue('Percent', 'PERCENT')
                .addEnumValue('Text', 'TEXT')
                .addEnumValue('Time', 'TIME')
            )
        ),
    mutuallyExclusive: new ArrayXMLField('mutuallyExclusive', 'Mutually Exclusive')
        .setMinApi(45)
        .setEditable(),
    onBehalfOfExpression: new StringXMLField('onBehalfOfExpression', 'On Behalf Of Expression')
        .setMinApi(45)
        .setEditable(),
    recommendationLimit: new ArrayXMLField('recommendationLimit', 'Recommendation Limit')
        .setMinApi(45)
        .setEditable()
        .setFieldKey('object')
        .setSortOrder(undefined)
        .addField('condition', new ArrayXMLField('condition', 'Condition')
            .setEditable()
            .setFieldKey('field')
            .setSortOrder(undefined)
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Equals', 'EQUALS')
                .addEnumValue('Greater Than', 'GREATER_THAN')
                .addEnumValue('Greater Than or Equal To', 'GREATER_THAN_OR_EQUAL_TO')
                .addEnumValue('Less Than', 'LESS_THAN')
                .addEnumValue('Less Than or Equal To', 'LESS_THAN_OR_EQUAL_TO')
                .addEnumValue('Not Equals', 'NOT_EQUALS')
                .addEnumValue('Like', 'LIKE')
                .addEnumValue('Starts With', 'STARTS_WITH')
                .addEnumValue('Ends With', 'ENDS_WITH')
                .addEnumValue('Contains', 'CONTAINS')
            )
            .addField('value', new ObjectXMLField('value', 'Value')
                .setEditable()
                .setRequired()
                .setFieldKey('value')
                .setSortOrder(undefined)
                .addField('type', new EnumXMLField('type', 'Type')
                    .setEditable()
                    .addEnumValue('Text', 'TEXT')
                    .addEnumValue('Number', 'NUMBER')
                    .addEnumValue('Boolean', 'BOOLEAN')
                    .addEnumValue('Date', 'DATE')
                    .addEnumValue('Date Time', 'DATE_TIME')
                    .addEnumValue('Time', 'TIME')
                )
                .addField('value', new StringXMLField('value', 'Value')
                    .setEditable()
                    .setRequired()
                )
            )
        )
        .addField('conditionLogic', new StringXMLField('conditionLogic', 'Condition Logic')
            .setEditable()
        )
        .addField('object', new StringXMLField('object', 'Object')
            .setMinApi(48)
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('sortField', new ObjectXMLField('sortField', 'Sort Field')
            .setMinApi(48)
            .setEditable()
            .setFieldKey('name')
            .setSortOrder(undefined)
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
            .addField('nullsFirst', new BooleanXMLField('nullsFirst', 'Nulls First')
                .setEditable()
                .setDefaultValue(false)
            )
            .addField('order', new EnumXMLField('order', 'Order')
                .setEditable()
                .setRequired()
                .setDefaultValue('Asc')
                .addEnumValue('ASC', 'Asc')
                .addEnumValue('DESC', 'Desc')
            )
        ),
    recommendationLoad: new ArrayXMLField('recommendationLoad', 'Recommendation Load')
        .setMinApi(45)
        .setEditable()
        .setFieldKey('object')
        .setSortOrder(undefined)
        .addField('condition', new ArrayXMLField('condition', 'Condition')
            .setEditable()
            .setFieldKey('field')
            .setSortOrder(undefined)
            .addField('field', new StringXMLField('field', 'Field')
                .setEditable()
                .setRequired()
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .setRequired()
                .addEnumValue('Equals', 'EQUALS')
                .addEnumValue('Greater Than', 'GREATER_THAN')
                .addEnumValue('Greater Than or Equal To', 'GREATER_THAN_OR_EQUAL_TO')
                .addEnumValue('Less Than', 'LESS_THAN')
                .addEnumValue('Less Than or Equal To', 'LESS_THAN_OR_EQUAL_TO')
                .addEnumValue('Not Equals', 'NOT_EQUALS')
                .addEnumValue('Like', 'LIKE')
                .addEnumValue('Starts With', 'STARTS_WITH')
                .addEnumValue('Ends With', 'ENDS_WITH')
                .addEnumValue('Contains', 'CONTAINS')
            )
            .addField('value', new ObjectXMLField('value', 'Value')
                .setEditable()
                .setRequired()
                .setFieldKey('value')
                .setSortOrder(undefined)
                .addField('type', new EnumXMLField('type', 'Type')
                    .setEditable()
                    .addEnumValue('Text', 'TEXT')
                    .addEnumValue('Number', 'NUMBER')
                    .addEnumValue('Boolean', 'BOOLEAN')
                    .addEnumValue('Date', 'DATE')
                    .addEnumValue('Date Time', 'DATE_TIME')
                    .addEnumValue('Time', 'TIME')
                )
                .addField('value', new StringXMLField('value', 'Value')
                    .setEditable()
                    .setRequired()
                )
            )
        )
        .addField('conditionLogic', new StringXMLField('conditionLogic', 'Condition Logic')
            .setEditable()
        )
        .addField('object', new StringXMLField('object', 'Object')
            .setMinApi(48)
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CUSTOM_OBJECT)
        )
        .addField('sortField', new ObjectXMLField('sortField', 'Sort Field')
            .setMinApi(48)
            .setEditable()
            .setFieldKey('name')
            .setSortOrder(undefined)
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
            .addField('nullsFirst', new BooleanXMLField('nullsFirst', 'Nulls First')
                .setEditable()
                .setDefaultValue(false)
            )
            .addField('order', new EnumXMLField('order', 'Order')
                .setEditable()
                .setRequired()
                .setDefaultValue('Asc')
                .addEnumValue('ASC', 'Asc')
                .addEnumValue('DESC', 'Desc')
            )
        ),
    sort: new ArrayXMLField('sort', 'Sort')
        .setMinApi(45)
        .setEditable()
        .setFieldKey('field')
        .setSortOrder(undefined)
        .addField('field', new ObjectXMLField('field', 'Field')
            .setEditable()
            .setRequired()
            .setFieldKey('name')
            .setSortOrder(undefined)
            .addField('name', new StringXMLField('name', 'Name')
                .setEditable()
                .setRequired()
            )
            .addField('nullsFirst', new BooleanXMLField('nullsFirst', 'Nulls First')
                .setEditable()
                .setDefaultValue(false)
            )
            .addField('order', new EnumXMLField('order', 'Order')
                .setEditable()
                .setRequired()
                .setDefaultValue('Asc')
                .addEnumValue('ASC', 'Asc')
                .addEnumValue('DESC', 'Desc')
            )
        ),
    union: new ArrayXMLField('union', 'Union')
        .setMinApi(45)
        .setEditable(),

}