import { StringXMLField, BooleanXMLField, ArrayXMLField, DataValues, MetadataTypes, EnumXMLField, IntegerXMLField, DoubleXMLField, ObjectXMLField, DateTimeXMLField } from '@aurahelper/core';

export const Report = {
    aggregates: new ArrayXMLField('aggregates', 'Aggregates')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('developerName')
        .addField('acrossGroupingContext', new StringXMLField('acrossGroupingContext', 'Across Grouping Context')
            .setMinApi(15)
            .setEditable()
        )
        .addField('calculatedFormula', new StringXMLField('calculatedFormula', 'Calculated Formula')
            .setEditable()
            .setRequired()
        )
        .addField('datatype', new EnumXMLField('datatype', 'Data Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Currency', 'currency')
            .addEnumValue('Number', 'number')
            .addEnumValue('Percent', 'percent')
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
            .setMaxLength(255)
        )
        .addField('developerName', new StringXMLField('developerName', 'Developer Name')
            .setEditable()
            .setRequired()
            .setUnique()
        )
        .addField('downGroupingContext', new StringXMLField('downGroupingContext', 'Down Grouping Context')
            .setMinApi(15)
            .setEditable()
        )
        .addField('isActive', new StringXMLField('isActive', 'Is Active')
            .setEditable()
            .setRequired()
        )
        .addField('isCrossBlock', new StringXMLField('isCrossBlock', 'Is Cross Block')
            .setMinApi(25)
            .setEditable()
        )
        .addField('masterLabel', new StringXMLField('masterLabel', 'Master Label')
            .setEditable()
            .setRequired()
        )
        .addField('reportType', new StringXMLField('reportType', 'Report Type')
            .setEditable()
            .setMetadataType(MetadataTypes.REPORT_TYPE)
        )
        .addField('scale', new IntegerXMLField('scale', 'Scale')
            .setEditable()
            .setMinValue(0)
            .setMaxValue(18)
        ),
    block: new ArrayXMLField('block', 'Block')
        .setMinApi(14)
        .setEditable()
        .setDefinitionReference('this'),
    blockInfo: new ObjectXMLField('blockInfo', 'Block Info')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('blockId')
        .setSortOrder(undefined)
        .addField('aggregateReferences', new ArrayXMLField('aggregateReferences', 'Aggregate References')
            .setEditable()
            .setFieldKey('aggregate')
            .setSortOrder(undefined)
            .addField('aggregate', new StringXMLField('aggregate', 'Aggregate')
                .setEditable()
                .setRequired()
            )
        )
        .addField('blockId', new EnumXMLField('blockId', 'Block Id')
            .setMinApi(25)
            .setEditable()
            .setRequired()
            .addEnumValue('Block 1', 'B1')
            .addEnumValue('Block 2', 'B2')
            .addEnumValue('Block 3', 'B3')
            .addEnumValue('Block 4', 'B4')
            .addEnumValue('Block 5', 'B5')
        )
        .addField('joinTable', new StringXMLField('joinTable', 'Join Table')
            .setEditable()
            .setRequired()
        ),
    buckets: new ArrayXMLField('buckets', 'Buckets')
        .setMinApi(24)
        .setEditable()
        .setFieldKey('developerName')
        .addField('bucketType', new EnumXMLField('bucketType', 'Bucket Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Text', 'text')
            .addEnumValue('Number', 'number')
            .addEnumValue('Picklist', 'picklist')
        )
        .addField('developerName', new StringXMLField('developerName', 'Developer Name')
            .setEditable()
            .setRequired()
            .setUnique()
        )
        .addField('masterLabel', new StringXMLField('masterLabel', 'Master Label')
            .setEditable()
            .setRequired()
            .setMaxLength(40)
        )
        .addField('nullTreatment', new EnumXMLField('nullTreatment', 'Null Treatment')
            .setEditable()
            .setRequired()
            .addEnumValue('Treat null as Zero', 'z')
            .addEnumValue('Treat null as Blank', 'n')
        )
        .addField('otherBucketLabel', new StringXMLField('otherBucketLabel', 'Other Bucket Label')
            .setEditable()
        )
        .addField('sourceColumnName', new StringXMLField('sourceColumnName', 'Source Column Name')
            .setEditable()
            .setRequired()
        )
        .addField('values', new ObjectXMLField('values', 'Values')
            .setEditable()
            .setRequired()
            .setFieldKey('value')
            .setSortOrder(undefined)
            .addField('sourceValues', new EnumXMLField('sourceValues', 'Source Values')
                .setEditable()
                .addEnumValue('Source Value', 'sourceValue')
                .addEnumValue('From', 'from')
                .addEnumValue('To', 'to')
            )
            .addField('value', new EnumXMLField('value', 'Value')
                .setEditable()
                .setRequired()
            )
        ),
    chart: new ObjectXMLField('chart', 'Chart')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('title')
        .setSortOrder(undefined)
        .addField('backgroundColor1', new StringXMLField('backgroundColor1', 'Background Color 1')
            .setEditable()
        )
        .addField('backgroundColor2', new StringXMLField('backgroundColor2', 'Background Color 2')
            .setEditable()
        )
        .addField('sourceValues', new EnumXMLField('sourceValues', 'Source Values')
            .setEditable()
            .addEnumValue('Diagonal', 'Diagonal')
            .addEnumValue('Left To Right', 'LeftToRight')
            .addEnumValue('Top To Bottom', 'TopToBottom')
        )
        .addField('chartSummaries', new ArrayXMLField('chartSummaries', 'Chart Summaries')
            .setMinApi(17)
            .setEditable()
            .setFieldKey('aggregate')
            .setSortOrder(undefined)
            .addField('aggregate', new EnumXMLField('aggregate', 'Aggregate')
                .setEditable()
                .setEnumValues(DataValues.REPORT_SUMMARY_TYPES)
            )
            .addField('axisBinding', new EnumXMLField('axisBinding', 'Axis Binding')
                .setEditable()
                .addEnumValue('X', 'x')
                .addEnumValue('Y', 'y')
                .addEnumValue('Y2', 'y2')
            )
            .addField('column', new StringXMLField('column', 'Column')
                .setEditable()
                .setRequired()
            )
        )
        .addField('chartType', new EnumXMLField('chartType', 'Chart Type')
            .setEditable()
            .addEnumValue('None', 'None')
            .addEnumValue('Horizontal Bar', 'HorizontalBar')
            .addEnumValue('Horizontal Bar Grouped', 'HorizontalBarGrouped')
            .addEnumValue('Horizontal Bar Stacked', 'HorizontalBarStacked')
            .addEnumValue('Horizontal Bar Stacked To 100', 'HorizontalBarStackedTo100')
            .addEnumValue('Vertical Column', 'VerticalColumn')
            .addEnumValue('Vertical Column Grouped', 'VerticalColumnGrouped')
            .addEnumValue('Vertical Column Stacked', 'VerticalColumnStacked')
            .addEnumValue('Vertical Column Stacked To 100', 'VerticalColumnStackedTo100')
            .addEnumValue('Line', 'Line')
            .addEnumValue('Line Grouped', 'LineGrouped')
            .addEnumValue('Line Cumulative', 'LineCumulative')
            .addEnumValue('Line Cumulative Grouped', 'LineCumulativeGrouped')
            .addEnumValue('Pie', 'Pie')
            .addEnumValue('Donut', 'Donut')
            .addEnumValue('Funnel', 'Funnel')
            .addEnumValue('Scatter', 'Scatter')
            .addEnumValue('Scatter Grouped', 'ScatterGrouped')
            .addEnumValue('Vertical Column Line', 'VerticalColumnLine')
            .addEnumValue('Vertical Column Grouped Line', 'VerticalColumnGroupedLine')
            .addEnumValue('Vertical Column Stacked Line', 'VerticalColumnStackedLine')
            .addEnumValue('Plugin', 'Plugin', 31)
        )
        .addField('enableHoverLabels', new BooleanXMLField('enableHoverLabels', 'Enable Hover Labels')
            .setMinApi(17)
            .setEditable()
        )
        .addField('expandOthers', new BooleanXMLField('expandOthers', 'Expand Others')
            .setMinApi(17)
            .setEditable()
        )
        .addField('groupingColumn', new StringXMLField('groupingColumn', 'Grouping Column')
            .setEditable()
        )
        .addField('legendPosition', new EnumXMLField('legendPosition', 'Legend Position')
            .setEditable()
            .setRequired()
            .addEnumValue('Bottom', 'Bottom')
            .addEnumValue('On Chart', 'OnChart')
            .addEnumValue('Right', 'Right')
        )
        .addField('location', new EnumXMLField('location', 'Location')
            .setEditable()
            .setRequired()
            .addEnumValue('Chart Top', 'CHART_TOP')
            .addEnumValue('Chart Bottom', 'CHART_BOTTOM')
        )
        .addField('secondaryGroupingColumn', new StringXMLField('secondaryGroupingColumn', 'Secondary Grouping Column')
            .setEditable()
        )
        .addField('showAxisLabels', new BooleanXMLField('showAxisLabels', 'Show Axis Labels')
            .setEditable()
        )
        .addField('showPercentage', new BooleanXMLField('showPercentage', 'Show Percentage')
            .setEditable()
        )
        .addField('showTotal', new BooleanXMLField('showTotal', 'Show Total')
            .setEditable()
        )
        .addField('showValues', new BooleanXMLField('showValues', 'Show Values')
            .setEditable()
        )
        .addField('size', new EnumXMLField('size', 'Size')
            .setMinApi(17)
            .setEditable()
            .setRequired()
            .addEnumValue('Tiny', 'Tiny')
            .addEnumValue('Small', 'Small')
            .addEnumValue('Medium', 'Medium')
            .addEnumValue('Large', 'Large')
            .addEnumValue('Huge', 'Huge')
        )
        .addField('summaryAggregate', new EnumXMLField('summaryAggregate', 'Summary Aggregate')
            .setMinApi(17)
            .setEditable()
            .setEnumValues(DataValues.REPORT_SUMMARY_TYPES)
        )
        .addField('summaryAxisManualRangeEnd', new DoubleXMLField('summaryAxisManualRangeEnd', 'Summary Axis Manual Range End')
            .setEditable()
        )
        .addField('summaryAxisManualRangeStart', new DoubleXMLField('summaryAxisManualRangeStart', 'Summary Axis Manual Range Start')
            .setEditable()
        )
        .addField('summaryAxisRange', new EnumXMLField('summaryAxisRange', 'Summary Axis Range')
            .setEditable()
            .setRequired()
            .addEnumValue('Auto', 'Auto')
            .addEnumValue('Manual', 'Manual')
        )
        .addField('summaryColumn', new StringXMLField('summaryColumn', 'Summary Column')
            .setMinApi(17)
            .setEditable()
            .setRequired()
        )
        .addField('textColor', new StringXMLField('textColor', 'Text Color')
            .setEditable()
        )
        .addField('textSize', new EnumXMLField('textSize', 'Text Size')
            .setEditable()
            .addEnumValue('8', '8')
            .addEnumValue('9', '9')
            .addEnumValue('10', '10')
            .addEnumValue('12', '12')
            .addEnumValue('14', '14')
            .addEnumValue('18', '18')
            .addEnumValue('24', '24')
            .addEnumValue('36', '36')
        )
        .addField('title', new StringXMLField('title', 'Title')
            .setEditable()
            .setMaxLength(255)
        )
        .addField('titleColor', new StringXMLField('titleColor', 'Title Color')
            .setEditable()
        )
        .addField('titleSize', new EnumXMLField('titleSize', 'Title Size')
            .setEditable()
            .addEnumValue('8', '8')
            .addEnumValue('9', '9')
            .addEnumValue('10', '10')
            .addEnumValue('12', '12')
            .addEnumValue('14', '14')
            .addEnumValue('18', '18')
            .addEnumValue('24', '24')
            .addEnumValue('36', '36')
        ),
    colorRanges: new ArrayXMLField('colorRanges', 'Color Ranges')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('aggregate')
        .setSortOrder(undefined)
        .addField('aggregate', new EnumXMLField('aggregate', 'Aggregate')
            .setEditable()
            .setEnumValues(DataValues.REPORT_SUMMARY_TYPES)
        )
        .addField('columnName', new StringXMLField('columnName', 'Column Name')
            .setEditable()
            .setRequired()
        )
        .addField('highBreakpoint', new DoubleXMLField('highBreakpoint', 'High Breakpoint')
            .setEditable()
            .setRequired()
        )
        .addField('highColor', new StringXMLField('highColor', 'High Color')
            .setEditable()
            .setRequired()
        )
        .addField('lowBreakpoint', new DoubleXMLField('lowBreakpoint', 'Low Breakpoint')
            .setEditable()
            .setRequired()
        )
        .addField('lowColor', new StringXMLField('lowColor', 'Low Color')
            .setEditable()
            .setRequired()
        )
        .addField('midColor', new StringXMLField('midColor', 'Mid Color')
            .setEditable()
            .setRequired()
        ),
    columns: new ArrayXMLField('columns', 'Columns')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('field')
        .setSortOrder(undefined)
        .addField('aggregateTypes', new EnumXMLField('aggregateTypes', 'Aggregate Types')
            .setEditable()
            .setEnumValues(DataValues.REPORT_SUMMARY_TYPES)
        )
        .addField('field', new StringXMLField('field', 'Field')
            .setEditable()
            .setRequired()
            .setMetadataType(MetadataTypes.CUSTOM_FIELD)
        )
        .addField('reverseColors', new BooleanXMLField('reverseColors', 'Reverse Colors')
            .setMinApi(29)
            .setEditable()
        )
        .addField('showChanges', new BooleanXMLField('showChanges', 'Show Changes')
            .setMinApi(29)
            .setEditable()
        ),
    crossFilters: new ArrayXMLField('crossFilters', 'Cross Filters')
        .setMinApi(51)
        .setEditable()
        .setFieldKey('relatedTable')
        .setSortOrder(undefined)
        .addField('criteriaItems', new ObjectXMLField('criteriaItems', 'Criteria Items')
            .setEditable()
            .setFieldKey('column')
            .setSortOrder(undefined)
            .addField('column', new StringXMLField('column', 'Column')
                .setEditable()
                .setRequired()
            )
            .addField('columnToColumn', new BooleanXMLField('columnToColumn', 'Column To Column')
                .setMinApi(29)
                .setEditable()
            )
            .addField('isUnlocked', new BooleanXMLField('isUnlocked', 'Is Unlocked')
                .setMinApi(38)
                .setEditable()
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .addEnumValue('Equals', 'equals')
                .addEnumValue('Not Equal', 'notEqual')
                .addEnumValue('Less Than', 'lessThan')
                .addEnumValue('Greater Than', 'greaterThan')
                .addEnumValue('Less Or Equal', 'lessOrEqual')
                .addEnumValue('Greater Or Equal', 'greaterOrEqual')
                .addEnumValue('Contains', 'contains')
                .addEnumValue('Not Contain', 'notContain')
                .addEnumValue('Starts With', 'startsWith')
                .addEnumValue('Includes', 'includes')
                .addEnumValue('Excludes', 'excludes')
                .addEnumValue('Within', 'within')
            )
            .addField('snapshot', new StringXMLField('snapshot', 'Snapshot')
                .setEditable()
            )
            .addField('value', new StringXMLField('value', 'Value')
                .setEditable()
            )
        )
        .addField('operation', new EnumXMLField('operation', 'Operation')
            .setEditable()
            .addEnumValue('With', 'with')
            .addEnumValue('Without', 'without')
        )
        .addField('primaryTableColumn', new StringXMLField('primaryTableColumn', 'Primary Table Column')
            .setEditable()
        )
        .addField('relatedTable', new StringXMLField('relatedTable', 'Related Table')
            .setEditable()
        )
        .addField('relatedTableJoinColumn', new StringXMLField('relatedTableJoinColumn', 'Related Table Join Column')
            .setEditable()
        ),
    currency: new StringXMLField('currency', 'Currency')
        .setMinApi(14)
        .setEditable(),
    dataCategoryFilters: new StringXMLField('dataCategoryFilters', 'Data Category Filters')
        .setMinApi(14)
        .setEditable(),
    description: new StringXMLField('description', 'Description')
        .setMinApi(14)
        .setEditable()
        .setMaxLength(255),
    division: new StringXMLField('division', 'Division')
        .setMinApi(17)
        .setEditable(),
    filter: new ObjectXMLField('filter', 'Filter')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('language')
        .setSortOrder(undefined)
        .addField('booleanFilter', new StringXMLField('booleanFilter', 'Boolean Filter')
            .setEditable()
        )
        .addField('criteriaItems', new ObjectXMLField('criteriaItems', 'Criteria Items')
            .setEditable()
            .setFieldKey('column')
            .setSortOrder(undefined)
            .addField('column', new StringXMLField('column', 'Column')
                .setEditable()
                .setRequired()
            )
            .addField('columnToColumn', new BooleanXMLField('columnToColumn', 'Column To Column')
                .setMinApi(29)
                .setEditable()
            )
            .addField('isUnlocked', new BooleanXMLField('isUnlocked', 'Is Unlocked')
                .setMinApi(38)
                .setEditable()
            )
            .addField('operator', new EnumXMLField('operator', 'Operator')
                .setEditable()
                .addEnumValue('Equals', 'equals')
                .addEnumValue('Not Equal', 'notEqual')
                .addEnumValue('Less Than', 'lessThan')
                .addEnumValue('Greater Than', 'greaterThan')
                .addEnumValue('Less Or Equal', 'lessOrEqual')
                .addEnumValue('Greater Or Equal', 'greaterOrEqual')
                .addEnumValue('Contains', 'contains')
                .addEnumValue('Not Contain', 'notContain')
                .addEnumValue('Starts With', 'startsWith')
                .addEnumValue('Includes', 'includes')
                .addEnumValue('Excludes', 'excludes')
                .addEnumValue('Within', 'within')
            )
            .addField('snapshot', new StringXMLField('snapshot', 'Snapshot')
                .setEditable()
            )
            .addField('value', new StringXMLField('value', 'Value')
                .setEditable()
            )
        )
        .addField('language', new EnumXMLField('language', 'Language')
            .setEditable()
            .setEnumValues(DataValues.SF_LANGUAGES)
        ),
    folderName: new StringXMLField('folderName', 'Folder Name')
        .setMinApi(35)
        .setEditable()
        .setMetadataType(MetadataTypes.FOLDER),
    format: new EnumXMLField('format', 'Format')
        .setMinApi(14)
        .setEditable()
        .addEnumValue('Matrix', 'Matrix')
        .addEnumValue('Summary', 'Summary')
        .addEnumValue('Tabular', 'Tabular')
        .addEnumValue('Joined', 'Joined'),
    formattingRules: new ArrayXMLField('formattingRules', 'Formatting Rules')
        .setEditable()
        .setFieldKey('aggregate')
        .setSortOrder(undefined)
        .addField('aggregate', new EnumXMLField('aggregate', 'Aggregate')
            .setEditable()
            .addEnumValue('Sum', 'Sum')
            .addEnumValue('Average', 'Average')
            .addEnumValue('Maximum', 'Maximum')
            .addEnumValue('Minimum', 'Minimum')
            .addEnumValue('Unique', 'Unique')
        )
        .addField('columnName', new StringXMLField('columnName', 'Column Name')
            .setEditable()
            .setRequired()
        )
        .addField('values', new ObjectXMLField('values', 'Values')
            .setEditable()
            .setFieldKey('backgroundColor')
            .setSortOrder(undefined)
            .addField('backgroundColor', new StringXMLField('backgroundColor', 'Background Color')
                .setEditable()
                .setRequired()
            )
            .addField('rangeUpperBound', new DoubleXMLField('rangeUpperBound', 'Range Upper Bound')
                .setEditable()
            )
        ),
    groupingsAcross: new ArrayXMLField('groupingsAcross', 'Groupings Across')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('field')
        .setSortOrder(undefined)
        .addField('aggregateType', new EnumXMLField('aggregateType', 'Aggregate Type')
            .setEditable()
            .addEnumValue('Sum', 'Sum')
            .addEnumValue('Average', 'Average')
            .addEnumValue('Maximum', 'Maximum')
            .addEnumValue('Minimum', 'Minimum')
            .addEnumValue('Row Count', 'RowCount')
            .addEnumValue('Unique', 'Unique')
        )
        .addField('dateGranularity', new EnumXMLField('dateGranularity', 'Date Granularity')
            .setEditable()
            .addEnumValue('None', 'None')
            .addEnumValue('By Day', 'Day')
            .addEnumValue('By Week', 'Week')
            .addEnumValue('By Month', 'Month')
            .addEnumValue('By Quarter', 'Quarter')
            .addEnumValue('By Year', 'Year')
            .addEnumValue('By Fiscal Quarter', 'FiscalQuarter')
            .addEnumValue('By Fiscal Year', 'FiscalYear')
            .addEnumValue('By Month In Year', 'MonthInYear')
            .addEnumValue('By Day In Month', 'DayInMonth')
            .addEnumValue('By Fiscal Period', 'FiscalPeriod')
            .addEnumValue('By Fiscal Week', 'FiscalWeek')
        )
        .addField('field', new StringXMLField('field', 'Field')
            .setEditable()
            .setRequired()
        )
        .addField('sortByName', new StringXMLField('sortByName', 'Sort By Name')
            .setEditable()
            .setRequired()
        )
        .addField('sortOrder', new EnumXMLField('sortOrder', 'Sort Order')
            .setEditable()
            .setRequired()
            .addEnumValue('ASC', 'Asc')
            .addEnumValue('DESC', 'Desc')
        )
        .addField('sortType', new EnumXMLField('sortType', 'Sort Type')
            .setEditable()
            .addEnumValue('Column', 'Column')
            .addEnumValue('Aggregate', 'Aggregate')
            .addEnumValue('Custom Summary Formula', 'CustomSummaryFormula')
        ),
    groupingsDown: new ArrayXMLField('groupingsDown', 'Groupings Down')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('field')
        .setSortOrder(undefined)
        .addField('aggregateType', new EnumXMLField('aggregateType', 'Aggregate Type')
            .setEditable()
            .addEnumValue('Sum', 'Sum')
            .addEnumValue('Average', 'Average')
            .addEnumValue('Maximum', 'Maximum')
            .addEnumValue('Minimum', 'Minimum')
            .addEnumValue('Row Count', 'RowCount')
            .addEnumValue('Unique', 'Unique')
        )
        .addField('dateGranularity', new EnumXMLField('dateGranularity', 'Date Granularity')
            .setEditable()
            .addEnumValue('None', 'None')
            .addEnumValue('By Day', 'Day')
            .addEnumValue('By Week', 'Week')
            .addEnumValue('By Month', 'Month')
            .addEnumValue('By Quarter', 'Quarter')
            .addEnumValue('By Year', 'Year')
            .addEnumValue('By Fiscal Quarter', 'FiscalQuarter')
            .addEnumValue('By Fiscal Year', 'FiscalYear')
            .addEnumValue('By Month In Year', 'MonthInYear')
            .addEnumValue('By Day In Month', 'DayInMonth')
            .addEnumValue('By Fiscal Period', 'FiscalPeriod')
            .addEnumValue('By Fiscal Week', 'FiscalWeek')
        )
        .addField('field', new StringXMLField('field', 'Field')
            .setEditable()
            .setRequired()
        )
        .addField('sortByName', new StringXMLField('sortByName', 'Sort By Name')
            .setEditable()
            .setRequired()
        )
        .addField('sortOrder', new EnumXMLField('sortOrder', 'Sort Order')
            .setEditable()
            .setRequired()
            .addEnumValue('ASC', 'Asc')
            .addEnumValue('DESC', 'Desc')
        )
        .addField('sortType', new EnumXMLField('sortType', 'Sort Type')
            .setEditable()
            .addEnumValue('Column', 'Column')
            .addEnumValue('Aggregate', 'Aggregate')
            .addEnumValue('Custom Summary Formula', 'CustomSummaryFormula')
        ),
    historicalSelector: new ObjectXMLField('historicalSelector', 'Historical Selector')
        .setMinApi(29)
        .setEditable()
        .setFieldKey('snapshot')
        .setSortOrder(undefined)
        .addField('snapshot', new StringXMLField('snapshot', 'Snapshot')
            .setEditable()
            .setRequired()
        ),
    name: new StringXMLField('name', 'Name')
        .setMinApi(14)
        .setEditable()
        .setRequired(),
    numSubscriptions: new IntegerXMLField('numSubscriptions', 'Number Subscriptions')
        .setMinApi(38)
        .setEditable(),
    params: new ArrayXMLField('params', 'Params')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('name')
        .setSortOrder(undefined)
        .addField('name', new StringXMLField('name', 'Name')
            .setEditable()
            .setRequired()
        )
        .addField('value', new StringXMLField('value', 'Value')
            .setEditable()
            .setRequired()
        ),
    reportCustomDetailFormula: new ObjectXMLField('reportCustomDetailFormula', 'Report Custom Detail Formula')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('developerName')
        .setSortOrder(undefined)
        .addField('calculatedFormula', new StringXMLField('calculatedFormula', 'Calculated Formula')
            .setEditable()
            .setRequired()
        )
        .addField('datatype', new EnumXMLField('datatype', 'Data Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Double', 'Double')
            .addEnumValue('Date Only', 'DateOnly')
            .addEnumValue('Date Time', 'DateTime')
            .addEnumValue('Text', 'Text')
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
            .setMaxLength(255)
        )
        .addField('developerName', new StringXMLField('developerName', 'Developer Name')
            .setEditable()
            .setRequired()
            .setUnique()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('scale', new IntegerXMLField('scale', 'Scale')
            .setEditable()
            .setMinValue(0)
            .setMaxValue(18)
        ),
    reportType: new StringXMLField('reportType', 'Report Type')
        .setMinApi(14)
        .setEditable()
        .setRequired()
        .setMetadataType(MetadataTypes.REPORT_TYPE),
    roleHierarchyFilter: new StringXMLField('roleHierarchyFilter', 'Role Hierarchy Filter')
        .setMinApi(17)
        .setEditable(),
    rowLimit: new IntegerXMLField('rowLimit', 'Row Limit')
        .setMinApi(14)
        .setEditable(),
    scope: new EnumXMLField('scope', 'Scope')
        .setMinApi(14)
        .setEditable()
        .addEnumValue('My Accounts', 'MyAccounts')
        .addEnumValue('My Teams Accounts', 'MyTeamsAccounts')
        .addEnumValue('All Accounts', 'AllAccounts'),
    showCurrentDate: new BooleanXMLField('showCurrentDate', 'Show Current Date')
        .setMinApi(29)
        .setEditable(),
    showDetails: new BooleanXMLField('showDetails', 'Show Details')
        .setMinApi(14)
        .setEditable()
        .setDefaultValue(true),
    showGrandTotal: new BooleanXMLField('showGrandTotal', 'Show Grand Total')
        .setMinApi(14)
        .setEditable(),
    showSubTotals: new BooleanXMLField('showSubTotals', 'Show Sub Totals')
        .setMinApi(14)
        .setEditable(),
    sortColumn: new StringXMLField('sortColumn', 'Sort Column')
        .setMinApi(14)
        .setEditable(),
    sortOrder: new EnumXMLField('sortOrder', 'Sort Order')
        .setMinApi(14)
        .setEditable()
        .addEnumValue('ASC', 'Asc')
        .addEnumValue('DESC', 'Desc'),
    territoryHierarchyFilter: new StringXMLField('territoryHierarchyFilter', 'Territory Hierarchy Filter')
        .setMinApi(17)
        .setEditable(),
    timeFrameFilter: new ObjectXMLField('timeFrameFilter', 'Time Frame Filter')
        .setMinApi(14)
        .setEditable()
        .setFieldKey('dateColumn')
        .setSortOrder(undefined)
        .addField('dateColumn', new StringXMLField('dateColumn', 'Date Column')
            .setEditable()
            .setRequired()
        )
        .addField('endDate', new DateTimeXMLField('endDate', 'End Date')
            .setEditable()
            .setFormat('yyyy-nn-dd')
        )
        .addField('interval', new EnumXMLField('interval', 'Interval')
            .setEditable()
            .setRequired()
            .addEnumValue('Current fiscal quarter', 'INTERVAL_CURRENT')
            .addEnumValue('Current and next fiscal quarters', 'INTERVAL_CURNEXT1')
            .addEnumValue('Current and previous fiscal quarters', 'INTERVAL_CURPREV1')
            .addEnumValue('Next fiscal quarter', 'INTERVAL_NEXT1')
            .addEnumValue('Previous fiscal quarter', 'INTERVAL_PREV1')
            .addEnumValue('Current and next three fiscal quarters', 'INTERVAL_CURNEXT3')
            .addEnumValue('Current fiscal year', 'INTERVAL_CURFY')
            .addEnumValue('Previous fiscal year', 'INTERVAL_PREVFY')
            .addEnumValue('Previous two fiscal years', 'INTERVAL_PREV2FY')
            .addEnumValue('Two fiscal years ago', 'INTERVAL_AGO2FY')
            .addEnumValue('Next fiscal year', 'INTERVAL_NEXTFY')
            .addEnumValue('Current and previous fiscal years', 'INTERVAL_PREVCURFY')
            .addEnumValue('Current and previous two fiscal years', 'INTERVAL_PREVCUR2FY')
            .addEnumValue('Current and next fiscal year', 'INTERVAL_CURNEXTFY')
            .addEnumValue('A custom time period', 'INTERVAL_CUSTOM')
            .addEnumValue('Yesterday', 'INTERVAL_YESTERDAY')
            .addEnumValue('Today', 'INTERVAL_TODAY')
            .addEnumValue('Tomorrow', 'INTERVAL_TOMORROW')
            .addEnumValue('Last calendar week', 'INTERVAL_LASTWEEK')
            .addEnumValue('This calendar week', 'INTERVAL_THISWEEK')
            .addEnumValue('Next calendar week', 'INTERVAL_NEXTWEEK')
            .addEnumValue('Last calendar month', 'INTERVAL_LASTMONTH')
            .addEnumValue('This calendar month', 'INTERVAL_THISMONTH')
            .addEnumValue('Next calendar month', 'INTERVAL_NEXTMONTH')
            .addEnumValue('Current and previous calendar months', 'INTERVAL_LASTTHISMONTH')
            .addEnumValue('Current and next calendar months', 'INTERVAL_THISNEXTMONTH')
            .addEnumValue('Current calendar quarter', 'INTERVAL_CURRENTQ')
            .addEnumValue('Current and next calendar quarters', 'INTERVAL_CURNEXTQ')
            .addEnumValue('Current and previous calendar quarters', 'INTERVAL_CURPREVQ')
            .addEnumValue('Next calendar quarter', 'INTERVAL_NEXTQ')
            .addEnumValue('Previous calendar quarter', 'INTERVAL_PREVQ')
            .addEnumValue('Current and next three calendar quarters', 'INTERVAL_CURNEXT3Q')
            .addEnumValue('Current calendar year', 'INTERVAL_CURY')
            .addEnumValue('Previous calendar year', 'INTERVAL_PREVY')
            .addEnumValue('Previous two calendar years', 'INTERVAL_PREV2Y')
            .addEnumValue('Two calendar years ago', 'INTERVAL_AGO2Y')
            .addEnumValue('Next calendar year', 'INTERVAL_NEXTY')
            .addEnumValue('Current and previous calendar years', 'INTERVAL_PREVCURY')
            .addEnumValue('Current and previous two calendar years', 'INTERVAL_PREVCUR2Y')
            .addEnumValue('Current and next calendar years', 'INTERVAL_CURNEXTY')
            .addEnumValue('Last 7 days', 'INTERVAL_LAST7')
            .addEnumValue('Last 30 days', 'INTERVAL_LAST30')
            .addEnumValue('Last 60 days', 'INTERVAL_LAST60')
            .addEnumValue('Last 90 days', 'INTERVAL_LAST90')
            .addEnumValue('Last 120 days', 'INTERVAL_LAST120')
            .addEnumValue('Next 7 days', 'INTERVAL_NEXT7')
            .addEnumValue('Next 30 days', 'INTERVAL_NEXT30')
            .addEnumValue('Next 60 days', 'INTERVAL_NEXT60')
            .addEnumValue('Next 90 days', 'INTERVAL_NEXT90')
            .addEnumValue('Next 120 days', 'INTERVAL_NEXT120')
            .addEnumValue('Last fiscal week', 'LAST_FISCALWEEK')
            .addEnumValue('This fiscal week', 'THIS_FISCALWEEK')
            .addEnumValue('Next fiscal week', 'NEXT_FISCALWEEK')
            .addEnumValue('Last fiscal period', 'LAST_FISCALPERIOD')
            .addEnumValue('This fiscal period', 'THIS_FISCALPERIOD')
            .addEnumValue('Next fiscal period', 'NEXT_FISCALPERIOD')
            .addEnumValue('This fiscal period and last fiscal period', 'LASTTHIS_FISCALPERIOD')
            .addEnumValue('This fiscal period and next fiscal period', 'THISNEXT_FISCALPERIOD')
            .addEnumValue('Current entitlement period', 'CURRENT_ENTITLEMENT_PERIOD')
            .addEnumValue('Previous entitlement period', 'PREVIOUS_ENTITLEMENT_PERIOD')
            .addEnumValue('Previous two entitlement periods', 'PREVIOUS_TWO_ENTITLEMENT_PERIODS')
            .addEnumValue('Two entitlement periods ago', 'TWO_ENTITLEMENT_PERIODS_AGO')
            .addEnumValue('Current and previous entitlement period', 'CURRENT_AND_PREVIOUS_ENTITLEMENT_PERIOD')
            .addEnumValue('Current and previous two entitlement periods', 'CURRENT_AND_PREVIOUS_TWO_ENTITLEMENT_PERIODS')

        )
        .addField('startDate', new DateTimeXMLField('startDate', 'Start Date')
            .setEditable()
            .setFormat('yyyy-nn-dd')
        ),
    userFilter: new StringXMLField('userFilter', 'User Filter')
        .setMinApi(17)
        .setEditable(),

};