const { StringXMLField, ObjectXMLField, ArrayXMLField, IntegerXMLField, DoubleXMLField, EnumXMLField, BooleanXMLField, DateTimeXMLField, XMLDataControlledField, XMLDependencyField } = require('../factory/xmlFactory');
const MetadataTypes = require('../values/metadataTypes');
const DataValues = require('../values/dataValues');
const Validator = require('../utils/validator');

module.exports = {
    application: new StringXMLField('application', 'Application')
        .setMinApi(39)
        .setEditable(),
    dataset: new StringXMLField('dataset', 'Dataset')
        .setMinApi(39)
        .setEditable()
        .setMetadataType(MetadataTypes.WAVE_DATASET),
    datasetConnector: new StringXMLField('datasetConnector', 'Dataset Connector')
        .setMinApi(39)
        .setEditable(),
    datasetFullyQualifiedName: new StringXMLField('datasetFullyQualifiedName', 'Dataset Fully Qualified Name')
        .setMinApi(39)
        .setEditable()
        .setMetadataType(MetadataTypes.WAVE_DATASET),
    dates: new ObjectXMLField('dates', 'Dates')
        .setMinApi()
        .setEditable()
        .addField('alias', new StringXMLField('alias', 'Alias')
            .setEditable()
            .setRequired()
        )
        .addField('compact', new BooleanXMLField('compact', 'Compact')
            .setEditable()
        )
        .addField('dateFieldDay', new StringXMLField('dateFieldDay', 'Date Field Day')
            .setEditable()
        )
        .addField('dateFieldEpochDay', new StringXMLField('dateFieldEpochDay', 'Date Field Epoch Day')
            .setEditable()
        )
        .addField('dateFieldEpochSecond', new StringXMLField('dateFieldEpochSecond', 'Date Field Epoch Second')
            .setEditable()
        )
        .addField('dateFieldFiscalMonth', new StringXMLField('dateFieldFiscalMonth', 'Date Field Fiscal Month')
            .setEditable()
        )
        .addField('dateFieldFiscalQuarter', new StringXMLField('dateFieldFiscalQuarter', 'Date Field Fiscal Quarter')
            .setEditable()
        )
        .addField('dateFieldFiscalWeek', new StringXMLField('dateFieldFiscalWeek', 'Date Field Fiscal Week')
            .setEditable()
        )
        .addField('dateFieldFiscalYear', new StringXMLField('dateFieldFiscalYear', 'Date Field Fiscal Year')
            .setEditable()
        )
        .addField('dateFieldFullYear', new StringXMLField('dateFieldFullYear', 'Date Field Full Year')
            .setEditable()
        )
        .addField('dateFieldHour', new StringXMLField('dateFieldHour', 'Date Field Hour')
            .setEditable()
        )
        .addField('dateFieldMinute', new StringXMLField('dateFieldMinute', 'Date Field Minute')
            .setEditable()
        )
        .addField('dateFieldMonth', new StringXMLField('dateFieldMonth', 'Date Field Month')
            .setEditable()
        )
        .addField('dateFieldQuarter', new StringXMLField('dateFieldQuarter', 'Date Field Quarter')
            .setEditable()
        )
        .addField('dateFieldSecond', new StringXMLField('dateFieldSecond', 'Date Field Second')
            .setEditable()
        )
        .addField('dateFieldWeek', new StringXMLField('dateFieldWeek', 'Date Field Week')
            .setEditable()
        )
        .addField('dateFieldYear', new StringXMLField('dateFieldYear', 'Date Field Year')
            .setEditable()
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('firstDayOfWeek', new IntegerXMLField('firstDayOfWeek', 'First Day Of Week')
            .setEditable()
            .setRequired()
            .setMinValue(1)
            .setMaxValue(7)
        )
        .addField('fiscalMonthOffset', new IntegerXMLField('fiscalMonthOffset', 'Fiscal Month Offset')
            .setEditable()
            .setRequired()
        )
        .addField('isYearEndFiscalYear', new BooleanXMLField('isYearEndFiscalYear', 'Is Year End Fiscal Year')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('showInExplorer', new BooleanXMLField('showInExplorer', 'Show In Explorer')
            .setEditable()
        )
        .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
            .setEditable()
            .setRequired()
        )
        .addField('type', new EnumXMLField('type', 'Type')
            .setEditable()
            .setRequired()
            .addEnumValue('Date', 'Date')
            .addEnumValue('Date Only', 'DateOnly')
            .addEnumValue('Date Time', 'DateTime')
        ),
    dimensions: new ObjectXMLField('dimensions', 'Dimensions')
        .setMinApi(39)
        .setEditable()
        .addField('conditionalFormatting', new ObjectXMLField('conditionalFormatting', 'Conditional Formatting')
            .setMinApi(43)
            .setEditable()
            .addField('formattingBins', new ObjectXMLField('formattingBins', 'Formatting Bins')
                .setEditable()
                .addField('bin', new StringXMLField('bin', 'Bin')
                    .setEditable()
                    .setRequired()
                )
                .addField('formatValue', new StringXMLField('formatValue', 'Format Value')
                    .setEditable()
                    .setRequired()
                )
                .addField('label', new StringXMLField('label', 'Label')
                    .setEditable()
                    .setRequired()
                )
                .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('formattingPredicates', new ObjectXMLField('formattingPredicates', 'Formatting Predicates')
                .setEditable()
                .addField('formatValue', new StringXMLField('formatValue', 'Format Value')
                    .setEditable()
                    .setRequired()
                )
                .addField('operator', new StringXMLField('operator', 'Operator')
                    .setEditable()
                    .setRequired()
                )
                .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                    .setEditable()
                    .setRequired()
                )
                .addField('value', new StringXMLField('value', 'Value')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('property', new StringXMLField('property', 'Property')
                .setEditable()
                .setRequired()
            )
            .addField('referenceField', new StringXMLField('referenceField', 'Reference Field')
                .setEditable()
                .setRequired()
            )
            .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                .setEditable()
                .setRequired()
            )
            .addField('type', new StringXMLField('type', 'Type')
                .setEditable()
                .setRequired()
            )
        )
        .addField('customActions', new ObjectXMLField('customActions', 'Custom Actions')
            .setEditable()
            .addField('customActionName', new StringXMLField('customActionName', 'Custom Action Name')
                .setEditable()
                .setRequired()
            )
            .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
                .setEditable()
                .setRequired()
            )
            .addField('icon', new StringXMLField('icon', 'Icon')
                .setEditable()
            )
            .addField('method', new StringXMLField('method', 'Method')
                .setEditable()
            )
            .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                .setEditable()
                .setRequired()
            )
            .addField('target', new StringXMLField('target', 'Target')
                .setEditable()
            )
            .addField('tooltip', new StringXMLField('tooltip', 'Tooltip')
                .setEditable()
            )
            .addField('url', new StringXMLField('url', 'URL')
                .setEditable()
            )
        )
        .addField('customActionsEnabled', new BooleanXMLField('customActionsEnabled', 'Custom Actions Enabled')
            .setEditable()
        )
        .addField('dateFormat', new StringXMLField('dateFormat', 'Date Format')
            .setEditable()
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('field', new StringXMLField('field', 'Field')
            .setEditable()
            .setRequired()
        )
        .addField('fullyQualifiedName', new StringXMLField('fullyQualifiedName', 'Fully Qualified Name')
            .setEditable()
        )
        .addField('imageTemplate', new StringXMLField('imageTemplate', 'Image Template')
            .setEditable()
        )
        .addField('isDerived', new BooleanXMLField('isDerived', 'Is Derived')
            .setEditable()
            .setRequired()
        )
        .addField('isMultiValue', new BooleanXMLField('isMultiValue', 'Is Multi Value')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('linkTemplate', new StringXMLField('linkTemplate', 'Link Template')
            .setEditable()
        )
        .addField('linkTemplateEnabled', new BooleanXMLField('linkTemplateEnabled', 'Link Template Enabled')
            .setEditable()
        )
        .addField('linkTooltip', new StringXMLField('linkTooltip', 'Link Tooltip')
            .setEditable()
        )
        .addField('members', new ObjectXMLField('members', 'members')
            .setEditable()
            .addField('color', new StringXMLField('color', 'Color')
                .setEditable()
            )
            .addField('label', new StringXMLField('label', 'Label')
                .setEditable()
            )
            .addField('member', new StringXMLField('member', 'Member')
                .setEditable()
                .setRequired()
            )
            .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                .setEditable()
                .setRequired()
            )
        )
        .addField('origin', new StringXMLField('origin', 'Origin')
            .setEditable()
        )
        .addField('recordDisplayFields', new ObjectXMLField('recordDisplayFields', 'Record Display Fields')
            .setEditable()
            .addField('recordDisplayField', new StringXMLField('recordDisplayField', 'Record Display Field')
                .setEditable()
                .setRequired()
            )
            .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                .setEditable()
                .setRequired()
            )
        )
        .addField('recordIdField', new StringXMLField('recordIdField', 'Record Id Field')
            .setEditable()
        )
        .addField('recordOrganizationIdField', new StringXMLField('recordOrganizationIdField', 'Record Organization Id Field')
            .setEditable()
        )
        .addField('salesforceActions', new ObjectXMLField('salesforceActions', 'Salesforce Actions')
            .setEditable()
            .addField('enabled', new BooleanXMLField('enabled', 'Enabled')
                .setEditable()
                .setRequired()
            )
            .addField('salesforceActionName', new StringXMLField('salesforceActionName', 'Salesforce Action Name')
                .setEditable()
                .setRequired()
            )
            .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                .setEditable()
                .setRequired()
            )
        )
        .addField('salesforceActionsEnabled', new BooleanXMLField('salesforceActionsEnabled', 'Salesforce Actions Enabled')
            .setEditable()
        )
        .addField('showDetailsDefaultFieldIndex', new IntegerXMLField('showDetailsDefaultFieldIndex', 'Show Details Default Field Index')
            .setEditable()
        )
        .addField('showInExplorer', new BooleanXMLField('showInExplorer', 'Show In Explorer')
            .setEditable()
        )
        .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
            .setEditable()
            .setRequired()
        ),
    measures: new ObjectXMLField('measures', 'Measures')
        .setMinApi(39)
        .setEditable()
        .addField('conditionalFormatting', new ObjectXMLField('conditionalFormatting', 'Conditional Formatting')
            .setMinApi(43)
            .setEditable()
            .addField('formattingBins', new ObjectXMLField('formattingBins', 'Formatting Bins')
                .setEditable()
                .addField('bin', new StringXMLField('bin', 'Bin')
                    .setEditable()
                    .setRequired()
                )
                .addField('formatValue', new StringXMLField('formatValue', 'Format Value')
                    .setEditable()
                    .setRequired()
                )
                .addField('label', new StringXMLField('label', 'Label')
                    .setEditable()
                    .setRequired()
                )
                .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('formattingPredicates', new ObjectXMLField('formattingPredicates', 'Formatting Predicates')
                .setEditable()
                .addField('formatValue', new StringXMLField('formatValue', 'Format Value')
                    .setEditable()
                    .setRequired()
                )
                .addField('operator', new StringXMLField('operator', 'Operator')
                    .setEditable()
                    .setRequired()
                )
                .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                    .setEditable()
                    .setRequired()
                )
                .addField('value', new StringXMLField('value', 'Value')
                    .setEditable()
                    .setRequired()
                )
            )
            .addField('property', new StringXMLField('property', 'Property')
                .setEditable()
                .setRequired()
            )
            .addField('referenceField', new StringXMLField('referenceField', 'Reference Field')
                .setEditable()
                .setRequired()
            )
            .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
                .setEditable()
                .setRequired()
            )
            .addField('type', new StringXMLField('type', 'Type')
                .setEditable()
                .setRequired()
            )
        )
        .addField('dateFormat', new StringXMLField('dateFormat', 'Date Format')
            .setEditable()
        )
        .addField('description', new StringXMLField('description', 'Description')
            .setEditable()
        )
        .addField('field', new StringXMLField('field', 'Field')
            .setEditable()
            .setRequired()
        )
        .addField('formatCustomFormat', new StringXMLField('formatCustomFormat', 'Format Custom Format')
            .setEditable()
        )
        .addField('formatDecimalDigits', new IntegerXMLField('formatDecimalDigits', 'Format Decimal Digits')
            .setEditable()
        )
        .addField('formatDecimalSeparator', new StringXMLField('formatDecimalSeparator', 'Format Decimal Separator')
            .setMinApi(48)
            .setEditable()
        )
        .addField('formatIsNegativeParens', new BooleanXMLField('formatIsNegativeParens', 'Format Is Negative Parens')
            .setEditable()
        )
        .addField('formatPrefix', new StringXMLField('formatPrefix', 'Format Prefix')
            .setEditable()
        )
        .addField('formatSuffix', new StringXMLField('formatSuffix', 'Format Suffix')
            .setEditable()
        )
        .addField('formatThousandsSeparator', new StringXMLField('formatThousandsSeparator', 'Format Thousands Separator')
            .setEditable()
        )
        .addField('formatUnit', new StringXMLField('formatUnit', 'Format Unit')
            .setEditable()
        )
        .addField('formatUnitMultiplier', new DoubleXMLField('formatUnitMultiplier', 'Format Unit Multiplier')
            .setEditable()
        )
        .addField('fullyQualifiedName', new StringXMLField('fullyQualifiedName', 'Fully Qualified Name')
            .setEditable()
        )
        .addField('isDerived', new BooleanXMLField('isDerived', 'Is Derived')
            .setEditable()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
        )
        .addField('origin', new StringXMLField('origin', 'Origin')
            .setEditable()
        )
        .addField('showDetailsDefaultFieldIndex', new IntegerXMLField('showDetailsDefaultFieldIndex', 'Show Details Default Field Index')
            .setEditable()
        )
        .addField('showInExplorer', new BooleanXMLField('showInExplorer', 'Show In Explorer')
            .setEditable()
        )
        .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
            .setEditable()
            .setRequired()
        ),
    organizations: new ObjectXMLField('organizations', 'Organizations')
        .setMinApi(39)
        .setEditable()
        .addField('instanceUrl', new StringXMLField('instanceUrl', 'Instance URL')
            .setEditable()
            .setRequired()
        )
        .addField('label', new StringXMLField('label', 'Label')
            .setEditable()
            .setRequired()
        )
        .addField('organizationIdentifier', new StringXMLField('organizationIdentifier', 'Organization Identifier')
            .setEditable()
            .setRequired()
        )
        .addField('sortIndex', new IntegerXMLField('sortIndex', 'Sort Index')
            .setEditable()
            .setRequired()
        ),
    origin: new StringXMLField('origin', 'Origin')
        .setMinApi(39)
        .setEditable(),
    type: new EnumXMLField('type', 'Type')
        .setMinApi(43)
        .setEditable()
        .addEnumValue('System', 'System')
        .addEnumValue('User', 'User')
        .addEnumValue('Main', 'Main')
        .addEnumValue('Asset', 'Asset'),
    waveVisualization: new EnumXMLField('waveVisualization', 'Wave Visualization')
        .setMinApi(43)
        .setEditable()
        .addEnumValue('Dashboard', 'dashboard')
        .addEnumValue('Lens', 'lens')
}